<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
///
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!
///
/// File generated by cvs://contrib/lang2installer/installer_builder
/// using strings defined in stringnames.txt (same dir)

$string['dataroot'] = 'Thư mục dữ liệu';
$string['dirroot'] = 'Thư mục Moodle';
$string['environment'] = 'Môi trường';
$string['environmentrequireinstall'] = 'cầnphải được cài hay kích hoạt.';
$string['installation'] = 'Cài đặt';
$string['language'] = 'Ngôn ngữ';
$string['phpversion'] = 'Phiên bản PHP';
$string['thischarset'] = 'UTF-8';
$string['thislanguage'] = 'Vietnamese';
$string['wwwroot'] = 'Địa chỉ web';
?>
