* [32mmaster[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/MOODLE_13_STABLE[m
  [31mremotes/origin/MOODLE_14_STABLE[m
  [31mremotes/origin/MOODLE_15_STABLE[m
  [31mremotes/origin/MOODLE_16_STABLE[m
  [31mremotes/origin/MOODLE_17_STABLE[m
  [31mremotes/origin/MOODLE_18_STABLE[m
  [31mremotes/origin/MOODLE_19_STABLE[m
  [31mremotes/origin/MOODLE_20_STABLE[m
  [31mremotes/origin/MOODLE_21_STABLE[m
  [31mremotes/origin/MOODLE_22_STABLE[m
  [31mremotes/origin/MOODLE_23_STABLE[m
  [31mremotes/origin/MOODLE_24_STABLE[m
  [31mremotes/origin/MOODLE_25_STABLE[m
  [31mremotes/origin/MOODLE_26_STABLE[m
  [31mremotes/origin/MOODLE_27_STABLE[m
  [31mremotes/origin/MOODLE_28_STABLE[m
  [31mremotes/origin/MOODLE_29_STABLE[m
  [31mremotes/origin/MOODLE_30_STABLE[m
  [31mremotes/origin/MOODLE_310_STABLE[m
  [31mremotes/origin/MOODLE_311_STABLE[m
  [31mremotes/origin/MOODLE_31_STABLE[m
  [31mremotes/origin/MOODLE_32_STABLE[m
  [31mremotes/origin/MOODLE_33_STABLE[m
  [31mremotes/origin/MOODLE_34_STABLE[m
  [31mremotes/origin/MOODLE_35_STABLE[m
  [31mremotes/origin/MOODLE_36_STABLE[m
  [31mremotes/origin/MOODLE_37_STABLE[m
  [31mremotes/origin/MOODLE_38_STABLE[m
  [31mremotes/origin/MOODLE_39_STABLE[m
  [31mremotes/origin/MOODLE_400_STABLE[m
  [31mremotes/origin/master[m
