// Iceland lang variables by Johannes Birgir Jensson

tinyMCE.addToLang('',{
theme_style_select : '-- St&iacute;lar --',
theme_code_desc : 'Breyta HTML k&oacute;&eth;a',
theme_code_title : 'HTML k&oacute;&eth;aritill',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : 'L&aacute;gskrift',
theme_sup_desc : 'H&aacute;skrift',
theme_hr_desc : 'Setja inn stiku',
theme_removeformat_desc : 'Fjarl&aelig;gja textasni&eth;',
theme_custom1_desc : 'Þ&iacute;n l&yacute;sing h&eacute;r',
insert_image_border : 'Rammi',
insert_image_dimensions : 'V&iacute;ddir',
insert_image_vspace : 'Bil fyrir ofan og ne&eth;an',
insert_image_hspace : 'Bil til vinstri og h&aelig;gri',
insert_image_align : 'J&ouml;fnun',
insert_image_align_default : '-- Ekki valin --',
insert_image_align_baseline : 'Sama l&iacute;na',
insert_image_align_top : 'Uppi',
insert_image_align_middle : 'Mi&eth;ja',
insert_image_align_bottom : 'Ni&eth;ri',
insert_image_align_texttop : 'Texti efst',
insert_image_align_absmiddle : 'Alveg &iacute; mi&eth;ju',
insert_image_align_absbottom : 'Alveg ne&eth;st',
insert_image_align_left : 'Vinstri',
insert_image_align_right : 'H&aelig;gri',
theme_font_size : '-- Textast&aelig;r&eth; --',
theme_fontdefault : '-- Leturger&eth; --',
theme_block : '-- Textasni&eth; --',
theme_paragraph : 'M&aacute;lsgrein',
theme_div : 'Div',
theme_address : 'Heimilisfang',
theme_pre : 'Ritv&eacute;l',
theme_h1 : 'Haus 1',
theme_h2 : 'Haus 2',
theme_h3 : 'Haus 3',
theme_h4 : 'Haus 4',
theme_h5 : 'Haus 5',
theme_h6 : 'Haus 6',
theme_colorpicker_title : 'Veldu lit',
theme_colorpicker_apply : 'Sta&eth;festa',
theme_forecolor_desc : 'Veldu textalit',
theme_backcolor_desc : 'Veldu bakgrunnslit',
theme_charmap_title : 'Veldu s&eacute;rstaf',
theme_charmap_desc : 'Setja s&eacute;rstaf inn',
theme_visualaid_desc : 'S&yacute;na/fela t&ouml;flur, akkeri og fleira',
insert_anchor_title : 'Setja inn/breyta akkeri',
insert_anchor_name : 'Heiti akkeris',
theme_anchor_desc : 'Setja inn/breyta akkeri',
theme_insert_link_titlefield : 'Titill',
theme_clipboard_msg : 'Afrita/klippa/l&iacute;ma er ekki virkt &iacute; Mozilla og Firefox.\nViltu f&aacute; uppl&yacute;singar um hvernig &thorn;&uacute; getur kveikt &aacute; &thorn;eim?',
theme_path : 'Sl&oacute;&eth;',
cut_desc : 'Klippa',
copy_desc : 'Afrita',
paste_desc : 'Skeyta',
link_list : 'Tenglalisti',
image_list : 'Myndalisti',
browse : 'Vafra',
image_props_desc : 'Stillingar myndar',
newdocument_desc : 'N&yacute;tt skjal',
class_name : 'Class',
newdocument : 'Ertu viss um a&eth; &thorn;&uacute; viljir hreinsa allt burtu?',
about_title : 'Um TinyMCE',
about : 'Um',
license : 'Leyfi',
plugins : 'Vi&eth;b&aelig;tur',
plugin : 'Vi&eth;b&oacute;t',
author : 'H&ouml;fundur',
version : '&Uacute;tg&aacute;fa',
loaded_plugins : 'Virkar vi&eth;b&aelig;tur',
help : 'Hj&aacute;lp',
not_set : '-- Ekki vali&eth; --',
close : 'Loka',
toolbar_focus : 'Fl&yacute;tilykill fyrir takka - Alt+Q, Fl&yacute;tilykill fyrir ritil - Alt-Z, Fl&yacute;tilykill fyrir sl&oacute;&eth; - Alt-X'
});
