<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle 2.1 installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.moodle.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['admindirname'] = 'Whaiaronga Whakahaere';
$string['availablelangs'] = 'Rārangi o ngā reo wātea ki db n';
$string['chooselanguagehead'] = 'Kōwhiritia tētahi reo';
$string['chooselanguagesub'] = 'Kōwhiritia koa tētahi reo mō te tāutanga ANAKE. Mā tētahi atu mata o muri mai, ka taea ai te kōwhiri i ngā reo a te pae, a te kaiwhakamahi hoki';
$string['databasehost'] = 'Kaihautū patengi raraunga';
$string['databasename'] = 'Ingoa patengi raraunga';
$string['dataroot'] = 'Whaiaronga Raraunga';
$string['dbprefix'] = 'Kuhimua o Ngā Ripanga';
$string['dirroot'] = 'Whaiaronga Moodle';
$string['environmenthead'] = 'E taki ana i tō taiao …';
$string['errorsinenvironment'] = 'He hapa i te taiao!n';
$string['installation'] = 'Tāutatanga';
$string['langdownloaderror'] = 'Kāore te reo "{$a}" i utaina. Ka tāuta tonu i te reo Ingarihi.';
$string['memorylimithelp'] = '<p>I tēnei wā ko te tepe pūmahara PHP mō tō tūmau ko te {$a}.</p><p>Mā tēnei pea ka raru ai te pūmahara o Moodle, inā ki te maha ake ngā kōwae e hohe ana, ngā kaiwhakamahi hoki/rānei.</p> <p>Ko tāku ki a koe, me whirihora te PHP ki te tepe teitei ake mēnā e taea ana, pēnei ake i te 40M. Arā atu ngā huarahi hei whakatutuki i tēnei:</p><ol><li>Mēnā ka taea, whakahiato anōtia te PHP ki te <i>--enable-memory-limit</i>. Mā tēnei ka taea e Moodle te tepe pūmahara te whakarite.</li><li>Mēnā he āheitanga tāu ki tō kōnae php.ini, ka taea te tautuhinga <b>memory_limit</b> te huri kia āhua 40M. Ki te kore ō āheitanga, pātaihia tō kaiwhakahaere, māna tērā āheitanga e hoatu ki a koe.</li><li>I runga i ētahi tūmau PHP ka taea te waihanga kōnae .htaccess ki roto i te whaiaronga Moodle e pupuru ana i tēnei rārangi: <p><blockquote>php_value memory_limit 40M</blockquote></p> <p>Heoi, i runga i ētahi tūmau ka kaupare pea te mahinga o ngā whārangi PHP <b>katoa</b> (ka kitea ngā hapa inā tirohia ngā whārangi) nō reira, me tango te kōnae .htaccess.</p></li></ol>';
$string['phpversion'] = 'Putanga PHP';
$string['phpversionhelp'] = '<p>E hiahiatia ana e Moodle kia  4.1.0 neke atu rānei te putanga PHP.</p><p>I tēnei wā kei te whakahaere koe i te putanga {$a}</p><p>Me whakahōu te PHP, nuku rānei ki tētahi kaihautū me te putanga hōu PHP hōu ake!</p>';
$string['welcomep10'] = '{$a->installername} ({$a->installerversion})';
$string['welcomep20'] = 'Ka taea e koe te kite i tēnei whārangi nātemea kua tāuta tika, whakarewa tika hoki koe i te pōkai <strong>{$a->packname} {$a->packversion}</strong> i tō rorohiko. Ngā mihi!';
$string['welcomep30'] = 'Kei roto hoki i tēnei <strong>{$a->installername}</strong> he taupānga hei hanga i tētahi taiao whakahaere tino pai mō <strong>Moodle</strong>, arā ko';
$string['welcomep40'] = 'Kei roto hoki i tēnei pōkai he <strong>Moodle {$a->moodlerelease}({$a->moodleversion})</strong>.';
$string['welcomep50'] = 'Kei raro katoa te whakamahinga o ia taupānga i āna ake raihana. He pūtake tuwhera <a href="http://www.opensource.org/docs/definition_plain.html"> te pōkai katoa <strong>{$a->installername}</strong>, ā,</a>ka tūaritia atu i raro i te raihana<a href="http://www.gnu.org/copyleft/gpl.html">GPL</a>.';
$string['welcomep60'] = 'Mā ngā whārangi e whai mai nei ka arataki i a koe ki te whirihora me te whakarite i a <strong>Moodle</strong> i runga i tō rorohiko.';
$string['welcomep70'] = 'Pāwhiritia te pātene "Panuku" kia whakarite tonu ai i a <strong>Moodle</strong>.';
$string['wwwroot'] = 'Wāhitau Tukutuku';
