<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
///
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!
///
/// File generated by cvs://contrib/lang2installer/installer_builder
/// using strings defined in stringnames.txt (same dir)

$string['bypassed'] = 'ជៀសវាង';
$string['check'] = 'ពិនិត្យ';
$string['closewindow'] = 'បិទ​បង្អួច​នេះ';
$string['continue'] = 'បន្ត';
$string['curlrecommended'] = 'ការ​ដំឡើង​បណ្ណាល័យ Curl ស្រេចចិត្ត គឺ​ត្រូវបាន​ផ្ដល់អនុសាសន៍​ដើម្បី​អនុញ្ញាត​មុខងារ​តបណ្ដាញ Moodle ។';
$string['customcheck'] = 'ការ​ពិនិត្យ​ផ្សេង​ទៀត';
$string['download'] = 'ទាញយក';
$string['environmenterrortodo'] = 'អ្នកត្រូវតែ​ដោះស្រាយ​បញ្ហា​បរិស្ថាន (កំហុស) ដែល​បាន​រកឃើញ​ខាងលើ មុនពេល​ធ្វើការ​ដំឡើង​កំណែ Moodle នេះ !';
$string['environmentrecommendcustomcheck'] = 'ប្រសិន​បើ​ការ​សាកល្បង​បរាជ័យ វា​នឹង​ចង្អុល​បង្ហាញ​ពី​បញ្ហា​ដ៏ចម្បង';
$string['environmentrecommendinstall'] = 'គួរ​តែ​ដំឡើង និង​អនុញ្ញាត​ដើម្បី​បាន​លទ្ធផល​ដ៏​ល្អ​បំផុត';
$string['environmentrecommendversion'] = 'កំណែ $a->needed គឺ​ត្រូវ​បាន​ផ្ដល់អនុសាសន៍ ហើយ​អ្នក​កំពុងរត់ $a->current';
$string['environmentrequirecustomcheck'] = 'ការ​សាកល្បង​នេះ​ត្រូវ​តែ​ឆ្លង​ផុត';
$string['environmentrequireinstall'] = 'ត្រូវ​តែ​បាន​ដំឡើង និង​អនុញ្ញាត';
$string['environmentrequireversion'] = 'ត្រូវការ​កំណែ $a->needed ហើយ​អ្នក​កំពុង​រត់ $a->current';
$string['environmentxmlerror'] = 'កំហុស​ក្នុង​ការ​អាន​ទិន្នន័យ​បរិស្ថាន ($a->error_code)';
$string['error'] = 'កំហុស';
$string['gdversion'] = 'កំណែ GD';
$string['help'] = 'ជំនួយ';
$string['iconvrecommended'] = 'ការ​ដំឡើង​បណ្ណាល័យ ICONV ស្រេចចិត្ត​​ត្រូវ​បាន​ផ្ដល់​អនុសាសន៍​ដើម្បី​ធ្វើ​ឲ្យ​ដំណើរការ​របស់​តំបន់​បណ្ដាញ​ប្រសើរ ជា​ពិសេស​នៅពេល​ដែល​តំបន់​បណ្ដាញ​របស់​អ្នក​គាំទ្រ​ភាសា​ដែល​មិនមែន​ជា​ភាសា​ឡាតាំង ។';
$string['info'] = 'ព័ត៌មាន';
$string['language'] = 'ភាសា';
$string['mbstringrecommended'] = 'ការ​ដំឡើង​បណ្ដាល័យ MBSTRING ស្រេចចិត្ត​​ត្រូវ​បាន​ផ្ដល់​អនុសាសន៍​ដើម្បី​ធ្វើ​ឲ្យ​ដំណើរការ​ប្រសើរ ជា​ពិសេស​នៅពេល​ដែល​តំបន់​បណ្ដាញ​របស់​អ្នក​គាំទ្រ​ភាសា​មិនមែន​ឡាតាំង ។';
$string['moodledocslink'] = 'ឯកសារ Moodle សម្រាប់​ទំព័រ​នេះ';
$string['mysql416bypassed'] = 'ទោះជា​យ៉ាងណា​ក៏ដោយ ប្រសិន​បើ​តំបន់​បណ្ដាញ​របស់​អ្នក​កំពុង​ប្រើ​តែ​​ភាសា iso-8859-1 (ឡាតាំង) នោះ​អ្នក​អាច​បន្ត​ប្រើ MySQL ៤.១.១២ (ឬ​ខ្ពស់ជាង) ដែល​បាន​ដំឡើង​បច្ចុប្បន្ន​របស់​អ្នក ។';
$string['mysql416required'] = 'MySQL ៤.១.១៦ ជា​កំណែ​អប្បបរមា​ដែល​ត្រូវការ​សម្រាប់ Moodle ១.៦ ដើម្បី​ធានា​ថា​ទិន្នន័យ​ទាំងអស់​អាច​ត្រូវ​បាន​បម្លែង​ទៅជា UTF-8 នៅពេល​ខាងមុខ ។';
$string['name'] = 'ឈ្មោះ';
$string['next'] = 'បន្ទាប់';
$string['ok'] = 'យល់ព្រម';
$string['opensslrecommended'] = 'ការ​ដំឡើងបណ្ណាល័យ OpenSSL ស្រេចចិត្ត​ ត្រូវ​បាន​ផ្ដល់​អនុសាសន៍  ដោយ​វា​អនុញ្ញាត​មុខងារ​តបណ្ដាញ​របស់ Moodle ។';
$string['password'] = 'ពាក្យ​សម្ងាត់';
$string['php50restricted'] = 'PHP ៤.០.x មាន​បញ្ហា​ដែល​ស្គាល់​មួយ​ចំនួន សូម​ធ្វើឲ្យ​ប្រសើរ​ទៅ ៥.១.x ឬ​បន្ទាប​ទៅ ៤.៣.x ឬ ៤.៤.x';
$string['previous'] = 'មុន​';
$string['qtyperqpwillberemoved'] = '​កំឡុង​ពេល​ធ្វើ​ឲ្យ​ប្រសើរ ប្រភេទ​សំណួរ RQP នឹង​ត្រូវ​បាន​យកចេញ ។ អ្នក​មិន​ប្រើ​ប្រភេទ​សំណួរ​នេះ​ទៀត​ទេ ដូច្នេះ​អ្នក​គួរតែ​មិន​ជួប​បញ្ហាទេ ។';
$string['qtyperqpwillberemovedanyway'] = 'កំឡុង​ពេល​ធ្វើ​ឲ្យ​ប្រសើរ ប្រភេទ​សំណួរ RQP នឹង​ត្រូវ​បាន​យកចេញ ។ អ្នក​មាន​ប្រភេទ​សំណួរ RQP មួយ​ចំនួន​នៅ​ក្នុង​មូលដ្ឋាន​ទិន្នន័យ​របស់​អ្នក ហើយ​សំណួរ​ទាំងនេះ​នឹង​ឈប់​ដំណើរការ​ រហូត​ទាល់តែ​អ្នក​ដំឡើង​កូដ​ពី http://moodle.org/mod/data/view.php?d=13&amp;rid=797 មុនពេល​​បន្ត​ធ្វើឲ្យ​​ប្រសើរ ។';
$string['report'] = 'របាយការណ៍';
$string['restricted'] = 'បាន​ដាក់​កម្រិត';
$string['serverchecks'] = 'ការ​ពិនិត្យ​ម៉ាស៊ីន​បម្រើ';
$string['status'] = 'ស្ថានភាព';
$string['thischarset'] = 'UTF-8';
$string['thisdirection'] = 'ltr';
$string['thislanguage'] = 'ខ្មែរ';
$string['unicoderecommended'] = 'អ្នក​ត្រូវ​បាន​ផ្ដល់​អនុសាសន៍​ឲ្យ​ទុក​ទិន្នន័យ​របស់​អ្នក​ទាំងអស់​ជា​យូនីកូដ (UTF-8) ។ ការ​ដំឡើង​ថ្មី​គួរតែ​ត្រូវ​បាន​ប្រព្រឹត្ត​ទៅក្នុង​មូលដ្ឋាន​ទិន្នន័យ​ដែល​​មាន​សំណុំ​តួអក្សរ​របស់​លំនាំដើម​ជា​យូនីកូដ ។ ប្រសិន​បើ​អ្នក​កំពុង​តែ​ធ្វើ​ឲ្យ​ប្រសើរ អ្នក​គួរតែ​អនុវត្ត​​ដំណើរការ​ប្ដូរ UTF-8 (សូម​មើល​ទំព័រ​អ្នក​គ្រប់គ្រង) ។';
$string['unicoderequired'] = 'វា​ត្រូវ​បានទាមទារ​ឲ្យ​អ្នក​ទុក​ទិន្នន័យ​របស់​អ្នក​ទាំងអស់​ជា​ទ្រង់ទ្រាយ​យូនីកូដ (UTF-8) ។ ការ​ដំឡើង​ថ្មី​ត្រូវតែ​បាន​ប្រព្រឹត្ត​ទៅក្នុង​មូលដ្ឋាន​ទិន្នន័យ​ដែល​មាន​សំណុំ​តួអក្សរ​លំនាំដើម​ជា​យូនីកូដ ។ ប្រសិន​បើ​អ្នក​កំពុង​ធ្វើ​ឲ្យ​ប្រសើរ អ្នក​គួរតែ​អនុវត្ត​ដំណើរការ​ប្ដូរ UTF-8 (សូម​មើល​ទំព័រ​អ្នក​គ្រប់គ្រង) ។';
$string['user'] = 'អ្នកប្រើ';
?>
