<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
///
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!
///
/// File generated by cvs://contrib/lang2installer/installer_builder
/// using strings defined in stringnames.txt (same dir)

$string['closewindow'] = 'इस विन्डो को बन्द कीजिए';
$string['continue'] = 'जारी रखें';
$string['database'] = 'डेटाबेस';
$string['language'] = 'भाषा';
$string['name'] = 'नाम';
$string['next'] = 'अगला';
$string['password'] = 'पासवर्ड';
$string['thischarset'] = 'UTF-8';
$string['thisdirection'] = 'ltr';
$string['thislanguage'] = 'िहन्दी';
$string['user'] = 'यूज़र';
?>
