<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
///
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!
///
/// File generated by cvs://contrib/lang2installer/installer_builder
/// using strings defined in stringnames.txt (same dir)

$string['availablelangs'] = 'Elenco delle lingue disponibili:'; // ORPHANED
$string['cannotcreatelangdir'] = 'Non è possibile creare la cartella delle lingue.';
$string['cannotdownloadcomponents'] = 'Non è possibile scaricare componenti.';
$string['cannotdownloadzipfile'] = 'Non è possibile scaricare file ZIP.';
$string['cannotfindcomponent'] = 'Non è possibile trovare il componente.';
$string['cannotsavemd5file'] = 'Non è possibile salvare il file md5.';
$string['cannotsavezipfile'] = 'Non è possibile salvare file ZIP.';
$string['cannotunzipfile'] = 'Non è possibile decomprimere il file.';
$string['chooselanguagehead'] = 'Scegli la lingua';
$string['chooselanguagesub'] = 'Scegliete la lingua da usare durante l\'installazione. La lingua usata nel sito e dagli utenti potrà essere modificata in seguito.';
$string['cliincorrectvalueerror'] = 'Errore, il valore \"$a->value\" non è corretto per \"$a->option\"'; // ORPHANED
$string['cliincorrectvalueretry'] = 'Valore non corretto, per favore riprova'; // ORPHANED
$string['cliinstallheader'] = 'Programma di installazione Moodle $a via linea di comando'; // ORPHANED
$string['clitypevalue'] = 'inserisci valore'; // ORPHANED
$string['clitypevaluedefault'] = 'inserisci valore oppure premi Invio per usare il valore di default ($a)'; // ORPHANED
$string['cliunknowoption'] = 'Opzione non riconosciuta:
$a
. Per favore utilizzate l\'opzione --help.'; // ORPHANED
$string['dataroot'] = 'Cartella dei dati';
$string['dirroot'] = 'Cartella di Moodle';
$string['environment'] = 'Ambiente';
$string['environmentrequireinstall'] = 'è necessaria l\'installazione/abilitazione';
$string['environmentrequireversion'] = 'è necessaria la versione $a->needed e la vostra versione attuale è $a->current';
$string['environmentsub2'] = 'Ciascuna release di Moodle prevede come requisito minimo una certa versione del PHP assieme ad una serie di estensioni. Prima di una installazione o di un aggiornamento viene eseguita la verifica di questi requisiti minimi. Se non sapete come installare nuove versioni del PHP o le sue estensioni, contattate l\'amministratore del vostro server.'; // ORPHANED
$string['errorsinenvironment'] = 'Ci sono problemi nel vostro ambiente'; // ORPHANED
$string['installation'] = 'Installazione';
$string['language'] = 'Lingua';
$string['parentlanguage'] = '<< TRADUTTORI: Se la vostra lingua ha una \"Parent language\" che Moodle deve usare quando mancano stringhe nel vostro language pack, allora dovete specificare qui il suo codice. Se il campo viene lasciato vuoto verrà usato l\'inglese. Esempio: it>>';
$string['paths'] = 'Percorsi'; // ORPHANED
$string['pathserrcreatedataroot'] = 'Lo script di installazione non ha potuto creare la Cartella dei dati ($a->dataroot).'; // ORPHANED
$string['pathshead'] = 'Conferma percorsi'; // ORPHANED
$string['pathsrodataroot'] = 'La Cartella dei dati non è scrivibile.'; // ORPHANED
$string['pathsroparentdataroot'] = 'La cartella superiore ($a->parent) non è scrivibile. Lo script di installazione non può creare la Cartella dei dati ($a->dataroot).'; // ORPHANED
$string['pathssubadmindir'] = 'Alcuni web host utilizzano la cartella /admin come URL di accesso a pannelli di controllo od altre funzioni particolari. Tuttavia questo nome coincide con il nome della cartella che Moodle utilizza per i propri file di amministrazione. Per evitare conflitti, è possibile specificare un nome alternativo per la cartella Admin di Moodle. Ad esempio:<p><b>moodleadmin</b></p>
Tutti i link che puntano ai file di amministrazione di Moodle terranno conto di questa variazione.'; // ORPHANED
$string['pathssubdataroot'] = 'E\' necessario specificare una cartella dove Moodle inserirà i file caricati dagli utenti. Il web server (in genere \'nobody\' o \'apache\') DEVE avere i permessi di lettura e di scrittura su questa cartella. In aggiunta, la cartella dei dati NON DEVE essere direttamente accessibile via web. Se la Cartella dei dati non esiste, lo script di installazione tenterà di crearla.'; // ORPHANED
$string['pathssubdirroot'] = 'Percorso assoluto della installazione Moodle. Modificatelo solamente se avete bisogno di usare link simbolici.'; // ORPHANED
$string['pathssubwwwroot'] = 'Indirizzo web per accedere a questa installazione di Moodle. Non è possibile accedere a Moodle usando indirizzi multipli. Se il vpstro sito ha indirizzi web pubblici multipli, dovete configurare dei re-indirizzamenti permanenti su tutti gli altri indirizzi.
Se il vostro sito è accessibile sia dalla Internet che dalla Intranet, allora usate l\'indirizzo Internet pubblico ed impostate il DNS in modo che anche gli utenti intranet possano accedere all\'indirizzo pubblico.'; // ORPHANED
$string['pathsunsecuredataroot'] = 'La posizione della Cartella dei dati non è sicura'; // ORPHANED
$string['pathswrongadmindir'] = 'La cartella Admin non esiste'; // ORPHANED
$string['pathswrongdirroot'] = 'La posizione della cartella Dirroot è errata'; // ORPHANED
$string['phpextension'] = '$a estensioni PHP'; // ORPHANED
$string['phpversion'] = 'Versione PHP';
$string['reload'] = 'Ricarica';
$string['thischarset'] = 'UTF-8';
$string['thislanguage'] = 'Italiano';
$string['welcomep10'] = '$a->installername ($a->installerversion)';
$string['welcomep20'] = 'Se vedete questa pagina avete installato correttamente e lanciato il pacchetto <strong>$a->packname $a->packversion</strong>. Complimenti!';
$string['welcomep30'] = 'La release di <strong>$a->installername</strong> include un applicazione per creare l\'ambiente dive girerà <strong>Moodle</strong>:';
$string['welcomep40'] = 'Il pacchetto include anche <strong>Moodle $a->moodlerelease ($a->moodleversion)</strong>.';
$string['welcomep50'] = 'L\'utilizzo delle applicazioni incluse in questo pacchetto è regolato dalle rispettive licenze. L\'intero pacchetto <strong>$a->installername</strong> è <a href=\"http://www.opensource.org/docs/definition_plain.html\">open source</a> ed è distribuito in accordo alla licenza <a href=\"http://www.gnu.org/copyleft/gpl.html\">GPL</a>.';
$string['welcomep60'] = 'Le prossime pagine vi guideranno attraverso semplici passi per installare e configurare <strong>Moodle</strong> nel vostro computer. Potete utilizzare le impostazioni di default oppure modificarle per adeguarle alle vostre esigenze.';
$string['welcomep70'] = 'Fate click sul pulsante \"Avanti\" per continuare l\'installazione di <strong>Moodle</strong>.';
$string['wwwroot'] = 'Indirizzo web';
?>
