memory_limit = 512M
max_execution_time = 300
max_input_vars = 5000
post_max_size = 100M
upload_max_filesize = 100M
opcache.enable = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000

