<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
///
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!
///
/// File generated by cvs://contrib/lang2installer/installer_builder
/// using strings defined in stringnames.txt (same dir)

$string['admindirerror'] = 'The admin directory specified is incorrect';
$string['admindirname'] = 'Admin Directory';
$string['admindirsettinghead'] = 'Setting the admin directory ...';
$string['admindirsettingsub'] = 'A very few webhosts use /admin as a special URL for you to access a
control panel or something. Unfortunately this conflicts with the
standard location for the Moodle admin pages. You can fix this by
renaming the admin directory in your installation, and putting that
new name here. For example: <br /> <br /><b>moodleadmin</b><br /> <br />
This will fix admin links in Moodle.';
$string['cannotcreatelangdir'] = 'Ngekhe ukhande i lang directory';
$string['cannotcreatetempdir'] = 'Ngeke ukhande i temp directory';
$string['cannotdownloadcomponents'] = 'Ngeke u downloade ama components.';
$string['cannotdownloadzipfile'] = 'Ngeke u downloade ifayela le ZIP';
$string['cannotfindcomponent'] = 'Awatholakali ama component';
$string['cannotsavemd5file'] = 'Aligcineki ifayela le md5';
$string['cannotsavezipfile'] = 'Aligcineki ifayela le ZIP.';
$string['cannotunzipfile'] = 'Alivuleki iafayela';
$string['caution'] = 'Caution';
$string['chooselanguagehead'] = 'Khetha ulwimi';
$string['chooselanguagesub'] = 'Sicela ukhethe ulwimi ozolufaka kuphela.You will be able to choose site and user languages on a later screen.';
$string['compatibilitysettingshead'] = 'Ukubhekwa kwe PHP settings....';
$string['compatibilitysettingssub'] = 'Your server should pass all these tests to make Moodle run properly';
$string['componentisuptodate'] = 'Component is up-to-date';
$string['configfilenotwritten'] = 'The installer script was not able to automatically create a config.php file containing your chosen settings, probably because the Moodle directory is not writeable. You can manually copy the following code into a file named config.php within the root directory of Moodle.';
$string['configurationcompletehead'] = 'Configuration completed';
$string['configurationcompletesub'] = 'Moodle made an attempt to save your configuration in a file in the root of your Moodle installation.';
$string['database'] = 'Database';
$string['downloadedfilecheckfailed'] = 'Ukubhekwa kwefayela elidownloadiwe akuphumelelanga.';
$string['invalidmd5'] = 'i md5 okungeyona';
$string['missingrequiredfield'] = 'I field edingekayo ayiphelele';
$string['remotedownloaderror'] = 'Download of component to your server failed, please verify proxy settings, PHP cURL extension is highly recommended.<br /><br />You must download the <a href=\"$a->url\">$a->url</a> file manually, copy it to \"$a->dest\" in your server and unzip it there.';
$string['remotedownloadnotallowed'] = 'Download of components to your server isn\'t allowed (allow_url_fopen is disabled).<br /><br />You must download the <a href=\"$a->url\">$a->url</a> file manually, copy it to \"$a->dest\" in your server and unzip it there.';
$string['thischarset'] = 'UTF-8';
$string['thisdirection'] = 'ltr';
$string['thislanguage'] = 'isiZulu';
$string['wrongdestpath'] = 'Indawo okungeyona';
$string['wrongsourcebase'] = 'I URL base source okungeyona';
$string['wrongzipfilename'] = 'Igama lefayela le ZIP okungelona.';
?>
