// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Cyffredinol',
popup_tab : 'Ffenest Naid',
events_tab : 'Digwyddiadau',
advanced_tab : 'Uwch',
general_props : 'Priodoleddau cyffredinol',
popup_props : 'Priodoleddau ffenest naid',
event_props : 'Digwyddiadau',
advanced_props : 'Priodoleddau uwch',
popup_opts : 'Dewisiadau',
anchor_names : 'Angorau',
target_same : 'Agor yn y ffenest / ffr&acirc;m yma',
target_parent : 'Agor yn rhiant y ffenest / ffr&acirc;m',
target_top : 'Agor yn y ffr&acirc;m uchaf (disodli pob ffr&acirc;m)',
target_blank : 'Agor mewn ffenest newydd',
popup : 'Ffenest naid Javascript',
popup_url : 'URL ffenest naid',
popup_name : 'Enw ffenest',
popup_return : 'Mewnosod \'return false\'',
popup_scrollbars : 'Dangos bariau sgrolio',
popup_statusbar : 'Dangos bar statws',
popup_toolbar : 'Dangos bariau offer',
popup_menubar : 'Dangos bar dewislen',
popup_location : 'Dangos bar lleoliad',
popup_resizable : 'Caniat&aacute;u newid maint y ffenest',
popup_dependent : 'Dibynnol (Mozilla/Firefox yn unig)',
popup_size : 'Maint',
popup_position : 'Lleoliad (X/Y)',
id : 'Id',
style: 'Arddull',
classes : 'Dosbarthiadau',
target_name : 'Enw targed',
langdir : 'Cyfeiriad iaith',
target_langcode : 'Iaith y targed',
langcode : 'C&ocirc;d iaith',
encoding : 'Amgodio testun y targed',
mime : 'Math MIME y targed',
rel : 'Perthynas tudalen i\'r targed',
rev : 'Perthynas targed i\'r dudalen',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Chwith i\'r dde',
rtl : 'Dde i\'r chwith'
});
