// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'כללי',
popup_tab : 'חלון קופץ',
events_tab : 'ארועים',
advanced_tab : 'מתקדם',
general_props : 'מאפיינים כלליים',
popup_props : 'מאפייני החלון הקופץ',
event_props : 'ארועים',
advanced_props : 'מאפיינים מתקדמים',
popup_opts : 'אפשרויות',
anchor_names : 'עוגנים',
target_same : 'פתח בחלון זה או מסגרת זו',
target_parent : 'פתח בחלון או במסגרת המקוריים',
target_top : 'פתח במסגרת הראשית (מחליף את כל המסגרות)',
target_blank : 'פתח בחלון חדש',
popup : 'חלון קופץ של Javascript',
popup_url : 'כתובת החלון הקופץ',
popup_name : 'שם החלון',
popup_return : 'הכנס \'return false\'',
popup_scrollbars : 'הצג פסי גלילה',
popup_statusbar : 'הצג שורת מצב',
popup_toolbar : 'הצג סרגלי כלום',
popup_menubar : 'הצג את שורת התפריטים',
popup_location : 'הצג את שורת הכתובת',
popup_resizable : 'חלון שניתן לשנות את גודלו',
popup_dependent : 'תלוי (Mozilla/Firefox בלבד)',
popup_size : 'גודל',
popup_position : 'מיקום (X/Y)',
id : 'Id',
style: 'סגנון',
classes : 'Classים',
target_name : 'שם יעד',
langdir : 'כיוון שפה',
target_langcode : 'שפת יעד',
langcode : 'קוד שפה',
encoding : 'קידוד תווים של היעד',
mime : 'סוג MIME של היעד',
rel : 'יחס של דף ליעד',
rev : 'יחס של יעד לדף',
tabindex : 'סדר טאבים',
accesskey : 'מקש גישה',
ltr : 'שמאל לימין',
rtl : 'ימין לשמאל'
});