// HU lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Általános',
popup_tab : 'Popup',
events_tab : 'Események',
advanced_tab : 'Haladó',
general_props : 'Általános beállítások',
popup_props : 'Popup beállítások',
event_props : 'Események',
advanced_props : 'Haladó beállítások',
popup_opts : 'Opciók',
anchor_names : 'Horgonyok',
target_same : 'Megnyitás ebben az ablakban / keretben',
target_parent : 'Megnyitás a szülõ ablakban / keretben',
target_top : 'Megnyitás felsõ keretben (minden keretet lecserél)',
target_blank : 'Megnyitás új ablakban',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Ablak név',
popup_return : '\'return false\' beszúrása',
popup_scrollbars : 'Görgetõsávok megjelenítése',
popup_statusbar : 'Állapotsor megjelenítése',
popup_toolbar : 'Eszköztárak megjelenítése',
popup_menubar : 'Menüsor megjelenítése',
popup_location : 'Címsáv megjelenítése',
popup_resizable : 'Ablak átméretezhetõvé tétele',
popup_dependent : 'Függõ (csak Mozilla/Firefox)',
popup_size : 'Méret',
popup_position : 'Pozíció (X/Y)',
id : 'Azonosító',
style: 'Stílus',
classes : 'Osztályok',
target_name : 'Cél neve',
langdir : 'Szöveg pozíció',
target_langcode : 'Cél szöveg',
langcode : 'Szöveg kód',
encoding : 'Cél karakter kódolás',
mime : 'Cél MIME típus',
rel : 'Oldal kapcsolata a céllal',
rev : 'Cél kapcsolat az oldallal',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Balról jobbra',
rtl : 'Jobbról balra'
});
