// Iceland lang variables by Johannes Birgir Jensson

tinyMCE.addToLang('advlink',{
general_tab : 'Almennt',
popup_tab : 'Sprettigluggi',
events_tab : 'Atbur&eth;ir',
advanced_tab : 'S&eacute;rstillingar',
general_props : 'Almennar stillingar',
popup_props : 'Stillingar sprettiglugga',
event_props : 'Atbur&eth;ir',
advanced_props : 'S&eacute;rstillingar',
popup_opts : 'Valkostir',
anchor_names : 'Akkeri',
target_same : 'Opna &iacute; &thorn;essum glugga / ramma',
target_parent : 'Opna &iacute; glugga / ramma foreldris',
target_top : 'Opna í efsta ramma (kemur í sta&eth; allra ramma)',
target_blank : 'Opna &iacute; n&yacute;jum glugga',
popup : 'Javascript sprettigluggi',
popup_url : 'Sl&oacute;&eth; sprettiglugga',
popup_name : 'Nafn glugga',
popup_return : 'Setja \'return false\'',
popup_scrollbars : 'S&yacute;na skrunsl&aacute;r',
popup_statusbar : 'S&yacute;na st&ouml;&eth;ustiku',
popup_toolbar : 'S&yacute;na t&oacute;lastiku',
popup_menubar : 'S&yacute;na valstiku',
popup_location : 'S&yacute;na sl&oacute;&eth;arstiku',
popup_resizable : 'Leyfa glugga a&eth; breyta st&aelig;r&eth;',
popup_dependent : 'H&aacute;&eth;ur (eing&ouml;ngu Mozilla/Firefox)',
popup_size : 'St&aelig;r&eth;',
popup_position : 'Sta&eth;setning (X/Y)',
id : 'Id',
style: 'St&iacute;ll',
classes : 'Klassi',
target_name : 'Nafn tengils',
langdir : 'Rith&aacute;ttur tungum&aacute;ls',
target_langcode : 'Tungum&aacute; tengils',
langcode : 'Tungum&aacute;lskenni',
encoding : 'Textak&oacute;&eth;un tengils',
mime : 'MIME-tegund tengils',
rel : 'Tengsl s&iacute;&eth;u til tengils',
rev : 'Tengsl tengils til s&iacute;&eth;u',
tabindex : 'R&ouml;&eth;un',
accesskey : 'Fl&yacute;tilykill',
ltr : 'Vinstri til h&aelig;gri',
rtl : 'H&aelig;gri til vinstri'
});
