// NL lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Algemeen',
popup_tab : 'Popup',
events_tab : 'Gebeurtenissen',
advanced_tab : 'Geavanceerd',
general_props : 'Algemene eigenschappen',
popup_props : 'Popup eigenschappen',
event_props : 'Gebeurtenissen',
advanced_props : 'Geavanceerde eigenschappen',
popup_opts : 'Opties',
anchor_names : 'Bladwijzers',
target_same : 'Openen in dit venster/frame',
target_parent : 'Openen in hgerliggend frame',
target_top : 'Openen in bovenste frame (vervangt alle frames)',
target_blank : 'Openen in nieuw venster',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Vensternaam',
popup_return : 'Voeg \'return false\' toe',
popup_scrollbars : 'Toon scrollbalken',
popup_statusbar : 'Toon statusbalk',
popup_toolbar : 'Toon werkbalk',
popup_menubar : 'Toon menubalk',
popup_location : 'Toon adresbalk',
popup_resizable : 'Maak venster schaalbaar',
popup_dependent : 'Afhankelijk (Mozilla/Firefox only)',
popup_size : 'Afmetingen',
popup_position : 'Positie (x/y)',
id : 'Id',
style: 'Stijl',
classes : 'Stijlen',
target_name : 'Naam doelframe',
langdir : 'Taalrichting',
target_langcode : 'Taal van doel',
langcode : 'Taalcode',
encoding : 'Doel character encoding',
mime : 'Doel MIME type',
rel : 'Relatie van pagina tot doel',
rev : 'Relatie van doel tot pagina',
tabindex : 'Tabindex',
accesskey : 'Toegangstoets',
ltr : 'Links naar rechts',
rtl : 'Rechts naar links'
});
