// nn = Norwegian (nynorsk) lang variables by Knut B. Jacobsen

tinyMCE.addToLang('advlink',{
general_tab : 'Generelle innstillinger',
popup_tab : 'Popup',
events_tab : 'Hendelser',
advanced_tab : 'Avanserte innstillinger',
general_props : 'Generelle innstillinger',
popup_props : 'Popup innstillinger',
event_props : 'Hendelser',
advanced_props : 'Generelle innstillinger',
popup_opts : 'Innstillinger',
anchor_names : 'Bokmerke',
target_same : '&Aring;pne i samme vindauge / ramme',
target_parent : '&Aring;pne i underliggende vindauge / ramme',
target_top : '&Aring;pne i topprammen (erstatter alle rammer)',
target_blank : '&Aring;pne i eit nytt vindauge',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Vindauge navn',
popup_return : 'Sett inn \'return false\'',
popup_scrollbars : 'Vis scrollbars',
popup_statusbar : 'Vis status bar',
popup_toolbar : 'Vis toolbars',
popup_menubar : 'Vis meny bar',
popup_location : 'Vis location bar',
popup_resizable : 'Gjer vindauget skalerbart',
popup_dependent : 'Avhengig vindauge (Bare i Mozilla/Firefox)',
popup_size : 'St&oslash;rrelse',
popup_position : 'Posisjon (X/Y)',
id : 'Id',
style: 'Stil',
classes : 'CSS klasser',
target_name : 'M&aring;l navn',
langdir : 'Skrift retning',
target_langcode : 'M&aring;l spr&aring;k',
langcode : 'Spr&aring;k kode',
encoding : 'Tekken konvertering',
mime : 'M&aring;lets MIME type',
rel : 'Relasjon side til m&aring;l',
rev : 'Relasjon m&aring;l til side',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Venstre mot h&oslash;gre',
rtl : 'H&oslash;gre mot venstre'
});
