// PL lang variables
// fixed by Wooya
// http://www.mfusion.prv.pl
// fixed by lemiel 14.11.2005

tinyMCE.addToLang('advlink',{
general_tab : 'G³ówne ustawienia',
popup_tab : 'Okienko popup',
events_tab : 'Zdarzenia',
advanced_tab : 'Zaawansowane',
general_props : 'G³ówne',
popup_props : 'Ustawienia popup',
event_props : 'Zdarzenia',
advanced_props : 'Zaawansowane opcje',
popup_opts : 'Opcje',
anchor_names : 'Kotwice',
target_same : 'Otwórz w tym oknie / ramce',
target_parent : 'Otwórz w poprzednim oknie / ramce',
target_top : 'Otwórz w g³ównej ramce (zamienia wszystkie ramki)',
target_blank : 'Otwórz w nowym oknie',
popup : 'Okienko popup Javascript',
popup_url : 'URL dla popup',
popup_name : 'Nazwa okna',
popup_return : 'Wstaw \'return false\'',
popup_scrollbars : 'Poka¿ paski przewijania',
popup_statusbar : 'Poka¿ pasek statusu',
popup_toolbar : 'Poka¿ pasek narzêdzi',
popup_menubar : 'Poka¿ pasek menu',
popup_location : 'Poka¿ pasek adresu',
popup_resizable : 'Pozwalaj na zmianê wielko¶ci okna',
popup_dependent : 'Zale¿ne (tylko Mozilla/Firefox)',
popup_size : 'Rozmiar',
popup_position : 'Pozycja (X/Y)',
id : 'Id',
style: 'Styl',
classes : 'Klasa',
target_name : 'Nazwa celu',
langdir : 'Kierunek tekstu',
target_langcode : 'Jêzyk celu',
langcode : 'Kod jêzyka',
encoding : 'Kodowanie znaków celu',
mime : 'Typ MIME celu',
rel : 'Zale¿no¶æ strony do celu',
rev : 'Zale¿no¶æ celu do strony',
tabindex : 'Indeks tabeli',
accesskey : 'Klawisz dostêpu',
ltr : 'Lewy do prawego',
rtl : 'Prawy do lewego'
});
