// SI lang variables ISO-8859-2

tinyMCE.addToLang('advlink',{
general_tab : 'Splo&#353;no',
popup_tab : 'Popup okno',
events_tab : 'Dogodki',
advanced_tab : 'Napredno',
general_props : 'Splo&#353;ne lastnosti',
popup_props : 'Lastnosti popup okna',
event_props : 'Lastnosti dogodkov',
advanced_props : 'Napredne lastnosti',
popup_opts : 'Mo&#382;nosti',
anchor_names : 'Sidra',
target_same : 'Odpri v tem oknu / okvirju',
target_parent : 'Odpri v star&#353;evem oknu / okvirju',
target_top : 'Odpri v najvi&#353;jem okvirju(nadomesti vse okvirje)',
target_blank : 'Odpri v novem oknu',
popup : 'Javascript popup okno',
popup_url : 'URL naslov popup okna',
popup_name : 'Ime okna',
popup_return : 'Vstavi \'return false\'',
popup_scrollbars : 'Poka&#382;i drsnike',
popup_statusbar : 'Poka&#382;i statusno vrstico',
popup_toolbar : 'Poka&#382;i orodno vrstico',
popup_menubar : 'Poka&#382;i menu',
popup_location : 'Poka&#382;i naslovno vrstico',
popup_resizable : 'Naj se da oknu spreminjati velikost',
popup_dependent : 'Odvisno okno (le v Mozilla/Firefox)',
popup_size : 'Velikost',
popup_position : 'Pozicija (X/Y)',
id : 'Id',
style: 'Stili',
classes : 'Razredi',
target_name : 'Ime tar&#269;e',
langdir : 'Smer jezika',
target_langcode : 'Jezik tar&#269;e',
langcode : 'Koda jezika',
encoding : 'Kodna tabela tar&#269;e',
mime : 'MIME type tar&#269;e',
rel : 'Razmerje strani do tar&#269;e',
rev : 'Razmerje tar&#269;e do strani',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Od leve proti desni',
rtl : 'Od desne proti levi'
});
