// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Generella inst&auml;llningar',
popup_tab : 'Popup',
events_tab : 'H&auml;ndelser',
advanced_tab : 'Avancerade inst&auml;llningar',
general_props : 'Generella inst&auml;llningar',
popup_props : 'Popup inst&auml;llningar',
event_props : 'H&auml;ndelser',
advanced_props : 'Generella inst&auml;llningar',
popup_opts : 'Inst&auml;llningar',
anchor_names : 'Bokm&auml;rken',
target_same : '&Ouml;ppna i samma f&ouml;nster / ram',
target_parent : '&Ouml;ppna i underliggande f&ouml;nster / ram',
target_top : '&Ouml;ppna i toppramen (ers&auml;tter alla ramar)',
target_blank : '&Ouml;ppna i ett nytt f&ouml;nster',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'F&ouml;nster namn',
popup_return : 'S&auml;ttin \'return false\'',
popup_scrollbars : 'Visa scrollbars',
popup_statusbar : 'Visa status bar',
popup_toolbar : 'Visa toolbars',
popup_menubar : 'Visa menu bar',
popup_location : 'Visa location bar',
popup_resizable : 'G&ouml;r f&ouml;nstret skalbart',
popup_dependent : 'Beroende f&ouml;nster (&Auml;ndast i Mozilla/Firefox)',
popup_size : 'Storek',
popup_position : 'Position (X/Y)',
id : 'Id',
style: 'Stil',
classes : 'CSS Classer',
target_name : 'M&aring;l namn',
langdir : 'Skrift riktning',
target_langcode : 'M&aring;l spr&aring;k',
langcode : 'Spr&aring;k k&aring;d',
encoding : 'Tecken konvertering',
mime : 'M&aring;lets MIME typ',
rel : 'Relation sida till m&aring;l',
rev : 'Relation m&aring;l till sida',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'V&auml;nster till h&ouml;ger',
rtl : 'H&ouml;ger till v&auml;nster'
});
