// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Genel',
popup_tab : 'Popup',
events_tab : 'Olaylar',
advanced_tab : 'Geliþmiþ',
general_props : 'Genel özellikler',
popup_props : 'Popup özellikleri',
event_props : 'Olaylar',
advanced_props : 'Geliþmiþ özellikler',
popup_opts : 'Seçenekler',
anchor_names : 'Baðlantýlar',
target_same : 'Bu pencerede/çerçevede aç',
target_parent : 'Ana pencerede/çerçevede aç',
target_top : 'Üst çercçevede aç(bütün çerçeveleri deðiþtirir)',
target_blank : 'Yeni pencerede aç',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Pencere ismi',
popup_return : '\'return false\' ekle',
popup_scrollbars : 'Kaydýrma çubuðunu göster',
popup_statusbar : 'Durum çubuðunu göster',
popup_toolbar : 'Araç çubuklarýný göster',
popup_menubar : 'Menü çubuðunu göster',
popup_location : 'Adres satýrýný göster',
popup_resizable : 'Pencereyi yeniden boyutlandýrýlabilir yap',
popup_dependent : 'Ana pencereye baðýmlý (sadece Mozilla/Firefox)',
popup_size : 'Büyüklük',
popup_position : 'Posizyon (X/Y)',
id : 'Id',
style: 'Stil',
classes : 'Sýnýflar',
target_name : 'Hedef isim',
langdir : 'Dil yönü',
target_langcode : 'Hedef dil',
langcode : 'Dil kodu',
encoding : 'Hedef karakter kodlamasý',
mime : 'Hedef MIME tipi',
rel : 'Sayfa - hedef iliþkisi',
rev : 'Hedef - sayfa iliþkisi',
tabindex : 'Tabindeks',
accesskey : 'Eriþim anahtarý',
ltr : 'Soldan saða',
rtl : 'Saðdan sola'
});
