language: php

os: linux
dist: xenial

services:
  - mysql
  - postgresql
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm

jobs:
  include:
    - php: 8.0
      env: MOODLE_BRANCH=master            DB=pgsql
    - php: 8.0
      env: MOODLE_BRANCH=master            DB=mysqli
    - php: 8.0
      env: MOODLE_BRANCH=MOODLE_311_STABLE DB=pgsql
    - php: 8.0
      env: MOODLE_BRANCH=MOODLE_311_STABLE DB=mysqli
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_310_STABLE DB=pgsql
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_39_STABLE  DB=mysqli
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_38_STABLE  DB=pgsql

    - php: 7.3
      env: MOODLE_BRANCH=master            DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=master            DB=mysqli
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_311_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_311_STABLE DB=mysqli
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_37_STABLE  DB=mysqli

    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_310_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_39_STABLE  DB=mysqli

    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_38_STABLE  DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_37_STABLE  DB=mysqli

    # Cannot test with Moodle 3.2 and 3.3 any more because the new composer 2
    # does require all components to be named properly (case-sensitively) and
    # those branches have phpunit/Dbunit, failing. See MDL-64725.

    # Cannot test with Moodle 3.4, 3.5, 3.6 because the use phpunit 6.x that
    # does not contain the new stringContainsString() assertions.

    # Cannot test with PHP 7.0 any more because we are now using the :void return type.
    # Note that, still, the plugin will work ok, it's just the phpunit tests which cannot
    # be executed with that PHP versions.

before_install:
  # The following line is only needed if you're going to run php8 jobs and your
  # plugin needs xmlrpc services.
  - if [[ ${TRAVIS_PHP_VERSION:0:1} -gt 7 ]]; then pecl install xmlrpc-beta; fi
  - echo 'max_input_vars=5000' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - >
    if [ -n "$DOCKER_USER" ] && [ -n "$DOCKER_TOKEN" ]; then
        echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
        echo "Using authenticated connection (no pull limits)"
    else
        echo "Using unauthenticated docker (pull limits may apply). Setup DOCKER_USER and DOCKER_TOKEN if needed."
    fi

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker --max-warnings 0
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  #- moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
