<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle 2.1 installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.moodle.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['cannotcreatelangdir'] = 'ލޭންގް (lang) ޑައިރެކްޓްރީއެއް ނުހެދުނު';
$string['cannotcreatetempdir'] = 'ޓެމްޕް ޑައިރެކްޓްރީ ނުހެދުނު';
$string['cannotdownloadcomponents'] = 'ކޮމްޕޯނަންޓްތައް ޑައުންލޯޑެއް ނުކުރެވޭ';
$string['cannotdownloadzipfile'] = 'ޒިޕް ފައިލް ޑައުންލޯޑެއް ނުކުރެވުނު';
$string['cannotfindcomponent'] = 'ކޮމްޕޯނަންޓް ނުފެނުނު';
$string['cannotsavemd5file'] = 'އެމްޑީފައިވް ފައިލް ސޭވެއް ނުކުރެވުނު';
$string['cannotsavezipfile'] = 'ޒިޕް ފައިލް ސޭވެއް ނުކުރެވުނު';
$string['cannotunzipfile'] = 'ފައިލް އަންޒިޕެއް ނުކުރެވުނު';
$string['componentisuptodate'] = 'ކޮމްޕޯނަންޓް އިނީ އަޕްޑޭޓްކޮށް';
$string['downloadedfilecheckfailed'] = 'ޑައުންލޯޑް ކުރެވުނު ފައިލްގެ ޗެކް ފެއިލްވެއްޖެ';
$string['invalidmd5'] = 'އެމްޑީފައިވް ކަމަކުނުދޭ';
$string['missingrequiredfield'] = 'ކޮންމެހެން ބޭނުންވާ ފީލްޑެއް އިނީ ހުސްކޮށް';
$string['remotedownloaderror'] = '"{$a->url}">{$a->url}</a> file manually, copy it to "{$a->dest}" in your server and unzip it there.';
$string['wrongdestpath'] = 'މަންޒިލް ނުބައި';
$string['wrongsourcebase'] = 'ސޯރސް ޔޫއާރްއެލް ބޭސް ނުބައި';
$string['wrongzipfilename'] = 'ޒިޕްފައިލްގެ ނަން ނުބައި';
