<?php
class Baz {}
class abstract {}
class and {}
class array {}
class as {}
class break {}
class callable {}
class case {}
class catch {}
class class {}
class clone {}
class const {}
class continue {}
class declare {}
class default {}
class die {}
class do {}
class echo {}
class else {}
class elseif {}
class empty {}
class enddeclare {}
class endfor {}
class endforeach {}
class endif {}
class endswitch {}
class endwhile {}
class eval {}
class exit {}
class extends {}
class final {}
class finally {}
class for {}
class foreach {}
class function {}
class global {}
class goto {}
class if {}
class implements {}
class include {}
class include_once {}
class instanceof {}
class insteadof {}
class interface {}
class isset {}
class list {}
class namespace {}
class new {}
class or {}
class print {}
class private {}
class protected {}
class public {}
class require {}
class require_once {}
class return {}
class static {}
class switch {}
class throw {}
class trait {}
class try {}
class unset {}
class use {}
class var {}
class while {}
class xor {}
class yield {}
class __CLASS__ {}
class __DIR__ {}
class __FILE__ {}
class __FUNCTION__ {}
class __METHOD__ {}
class __NAMESPACE__ {}
