<?php
trait Baz {}
trait abstract {}
trait and {}
trait array {}
trait as {}
trait break {}
trait callable {}
trait case {}
trait catch {}
trait class {}
trait clone {}
trait const {}
trait continue {}
trait declare {}
trait default {}
trait die {}
trait do {}
trait echo {}
trait else {}
trait elseif {}
trait empty {}
trait enddeclare {}
trait endfor {}
trait endforeach {}
trait endif {}
trait endswitch {}
trait endwhile {}
trait eval {}
trait exit {}
trait extends {}
trait final {}
trait finally {}
trait for {}
trait foreach {}
trait function {}
trait global {}
trait goto {}
trait if {}
trait implements {}
trait include {}
trait include_once {}
trait instanceof {}
trait insteadof {}
trait interface {}
trait isset {}
trait list {}
trait namespace {}
trait new {}
trait or {}
trait print {}
trait private {}
trait protected {}
trait public {}
trait require {}
trait require_once {}
trait return {}
trait static {}
trait switch {}
trait throw {}
trait trait {}
trait try {}
trait unset {}
trait use {}
trait var {}
trait while {}
trait xor {}
trait yield {}
trait __CLASS__ {}
trait __DIR__ {}
trait __FILE__ {}
trait __FUNCTION__ {}
trait __METHOD__ {}
trait __NAMESPACE__ {}
