<?PHP // $Id$

// This file is generally only included from admin/index.php
// It defines default values for any important configuration variables

   $defaults = array (
       "allowunenroll"            =>  true,
       "allusersaresitestudents"  =>  true,
       "auth"                     => 'email',
       "auth_pop3mailbox"         => 'INBOX',
       "autologinguests"          => 0,
       "cachetext"                =>  60,
       "changepassword"           =>  true,
       "country"                  => "",
       "debug"                    =>  7,
       "deleteunconfirmed"        => 168,
       "digestmailtime"           => 17,
       "displayloginfailures"     => '',
       "enablerssfeeds"           => 0,
       "enrol"                    => 'internal',
       "extendedusernamechars"    => false,
       "editorbackgroundcolor"    => '#ffffff',
       "editorfontfamily"         => 'Trebuchet MS,Verdana,Arial,Helvetica,sans-serif',
       "editorfontsize"           => '',
       "editorkillword"           => 1,
       "editorspelling"           => 0,
       "editorfontlist"           => "Trebuchet:Trebuchet MS,Verdana,Arial,Helvetica,sans-serif;Arial:arial,helvetica,sans-serif;Courier New:courier new,courier,monospace;Georgia:georgia,times new roman,times,serif;Tahoma:tahoma,arial,helvetica,sans-serif;Times New Roman:times new roman,times,serif;Verdana:verdana,arial,helvetica,sans-serif;Impact:impact;Wingdings:wingdings",
       "filteruploadedfiles"      =>  true,
       "forcelogin"               =>  false,
       "forceloginforprofiles"    =>  false,
       "fullnamedisplay"          => "firstname lastname",
       "framename"                => "_top",
       "frontpage"                =>  0,
       "gdversion"                =>  1,
       "guestloginbutton"         =>  1,
       "htmleditor"               =>  true,
       "lang"                     => "en",
       "langmenu"                 =>  1,
       "langlist"                 => "",
       "locale"                   => "en",
       "loginhttps"               =>  false,
       "loglifetime"              =>  0,
       "longtimenosee"            =>  100,
       "maxbytes"                 =>  0,
       "maxeditingtime"           =>  1800,
       "noreplyaddress"           => 'noreply@'.$_SERVER['HTTP_HOST'],
       "notifyloginfailures"      => '',
       "notifyloginthreshold"     =>  10,
       "opentogoogle"             =>  false,
       "prefix"                   => "",
       "proxyhost"                => "",
       "proxyport"                => "",
       "secureforms"              =>  false,
       "sessioncookie"            => "",
       "sessiontimeout"           =>  7200,
       "showsiteparticipantslist" => 0,
       "slasharguments"           =>  1,
       "smtphosts"                => "",
       "smtppass"                 => "",
       "smtpuser"                 => "",
       "style"                    => "default",
       "teacherassignteachers"    => true,
       "template"                 => "default",
       "textfilters"              => "mod/glossary/dynalink.php",
       "timezone"                 => 99,
       "theme"                    => "standard",
       "unzip"                    => "",
       "zip"                      => ""
    );

?>
