<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!

$string['closewindow'] = 'Închide fereastra';
$string['continue'] = 'Continua';
$string['error'] = 'Eroare';
$string['help'] = 'Ajutor';
$string['language'] = 'Limba';
$string['name'] = 'Nume';
$string['ok'] = 'OK';
$string['password'] = 'Parola';
$string['status'] = 'Status';
$string['thischarset'] = 'UTF-8';
$string['thislanguage'] = 'Română';
?>
