#!/usr/bin/php
<?php
/**
 * This script will run PHP CodeSniffer across given Moodle directories and 
 * produce reports of coding standard violations.
 *
 * HOW TO USE:
 *    php lib/pear/PHP/runsniffer mod/forum
 *
 * @package   PHP_CodeSniffer
 * @copyright 2006 Squiz Pty Ltd (ABN 77 084 670 600)
 * @license   http://matrix.squiz.net/developer/tools/php_cs/licence BSD Licence
 * @link      http://pear.php.net/package/PHP_CodeSniffer
 */

error_reporting(E_ALL | E_STRICT);

if (is_file(dirname(__FILE__).'/CodeSniffer/CLI.php') === true) {
    include_once dirname(__FILE__).'/CodeSniffer/CLI.php';
} else {
    include_once 'lib/pear/PHP/CodeSniffer/CLI.php';
}

$phpcs = new PHP_CodeSniffer_CLI();
$phpcs->checkRequirements();

$numErrors = $phpcs->process();
if ($numErrors === 0) {
    exit(0);
} else {
    exit(1);
}

?>
