<?php
// Sequence of get_string calls for page http://tim.moodle.com/moodle/course/view.php?id=2&edit=1&sesskey=1NzQu8osJ5
old_get_string('locale', '', NULL);
old_get_string('thisdirection', '', NULL);
old_get_string('locale', '', NULL);
old_get_string('thisdirection', '', NULL);
old_get_string('course', '', NULL);
old_get_string('youarehere', 'access', NULL);
old_get_string('thisdirection', '', NULL);
old_get_string('switchroleto', '', NULL);
old_get_string('switchroleto', '', NULL);
old_get_string('go', '', NULL);
old_get_string('helpprefix2', '', 'Switch role to');
old_get_string('newwindow', '', NULL);
old_get_string('turneditingoff', '', NULL);
old_get_string('loggedinas', 'moodle', '<a  href="http://tim.moodle.com/moodle/user/view.php?id=2&amp;course=2">Admin User</a>');
old_get_string('logout', '', NULL);
old_get_string('thisdirection', '', NULL);
old_get_string('thisdirection', '', NULL);
old_get_string('tocontent', 'access', NULL);
old_get_string('modulenameplural', 'forum', NULL);
old_get_string('modulenameplural', 'quiz', NULL);
old_get_string('modulenameplural', 'choice', NULL);
old_get_string('modulename', 'assignment', NULL);
old_get_string('modulenameplural', 'assignment', NULL);
old_get_string('modulename', 'choice', NULL);
old_get_string('modulenameplural', 'choice', NULL);
old_get_string('modulename', 'data', NULL);
old_get_string('modulenameplural', 'data', NULL);
old_get_string('modulename', 'forum', NULL);
old_get_string('modulenameplural', 'forum', NULL);
old_get_string('modulename', 'glossary', NULL);
old_get_string('modulenameplural', 'glossary', NULL);
old_get_string('modulename', 'label', NULL);
old_get_string('modulenameplural', 'label', NULL);
old_get_string('modulename', 'resource', NULL);
old_get_string('modulenameplural', 'resource', NULL);
old_get_string('modulename', 'scorm', NULL);
old_get_string('modulenameplural', 'scorm', NULL);
old_get_string('modulename', 'survey', NULL);
old_get_string('modulenameplural', 'survey', NULL);
old_get_string('modulename', 'lesson', NULL);
old_get_string('modulenameplural', 'lesson', NULL);
old_get_string('modulename', 'quiz', NULL);
old_get_string('modulenameplural', 'quiz', NULL);
old_get_string('modulename', 'chat', NULL);
old_get_string('modulenameplural', 'chat', NULL);
old_get_string('modulename', 'feedback', NULL);
old_get_string('modulenameplural', 'feedback', NULL);
old_get_string('editsummary', '', NULL);
old_get_string('add', '', NULL);
old_get_string('activities', '', NULL);
old_get_string('showallweeks', '', NULL);
old_get_string('week', '', NULL);
old_get_string('groups', '', NULL);
old_get_string('groupmy', '', NULL);
old_get_string('hideweekfromothers', '', NULL);
old_get_string('showweekfromothers', '', NULL);
old_get_string('moveup', '', NULL);
old_get_string('movedown', '', NULL);
old_get_string('people', '', NULL);
old_get_string('listofallpeople', '', NULL);
old_get_string('participants', '', NULL);
old_get_string('delete', '', NULL);
old_get_string('moveup', '', NULL);
old_get_string('movedown', '', NULL);
old_get_string('moveright', '', NULL);
old_get_string('moveleft', '', NULL);
old_get_string('hide', '', NULL);
old_get_string('show', '', NULL);
old_get_string('configuration', '', NULL);
old_get_string('assignroles', 'role', NULL);
old_get_string('listofallpeople', '', NULL);
old_get_string('participants', '', NULL);
old_get_string('showblocka', 'access', 'People');
old_get_string('hideblocka', 'access', 'People');
old_get_string('skipa', 'access', 'People');
old_get_string('showblocka', 'access', 'People');
old_get_string('hideblocka', 'access', 'People');
old_get_string('activities', '', NULL);
old_get_string('delete', '', NULL);
old_get_string('moveup', '', NULL);
old_get_string('movedown', '', NULL);
old_get_string('moveright', '', NULL);
old_get_string('moveleft', '', NULL);
old_get_string('hide', '', NULL);
old_get_string('show', '', NULL);
old_get_string('configuration', '', NULL);
old_get_string('assignroles', 'role', NULL);
old_get_string('showblocka', 'access', 'Activities');
old_get_string('hideblocka', 'access', 'Activities');
old_get_string('skipa', 'access', 'Activities');
old_get_string('showblocka', 'access', 'Activities');
old_get_string('hideblocka', 'access', 'Activities');
old_get_string('blocktitle', 'block_search_forums', NULL);
old_get_string('delete', '', NULL);
old_get_string('moveup', '', NULL);
old_get_string('movedown', '', NULL);
old_get_string('moveright', '', NULL);
old_get_string('moveleft', '', NULL);
old_get_string('hide', '', NULL);
old_get_string('show', '', NULL);
old_get_string('configuration', '', NULL);
old_get_string('assignroles', 'role', NULL);
old_get_string('advancedsearch', 'block_search_forums', NULL);
old_get_string('search', '', NULL);
old_get_string('helpprefix2', '', 'Advanced search');
old_get_string('newwindow', '', NULL);
old_get_string('showblocka', 'access', 'Search Forums');
old_get_string('hideblocka', 'access', 'Search Forums');
old_get_string('skipa', 'access', 'Search Forums');
old_get_string('showblocka', 'access', 'Search Forums');
old_get_string('hideblocka', 'access', 'Search Forums');
old_get_string('administration', '', NULL);
old_get_string('delete', '', NULL);
old_get_string('moveup', '', NULL);
old_get_string('movedown', '', NULL);
old_get_string('moveright', '', NULL);
old_get_string('moveleft', '', NULL);
old_get_string('hide', '', NULL);
old_get_string('show', '', NULL);
old_get_string('configuration', '', NULL);
old_get_string('assignroles', 'role', NULL);
old_get_string('turneditingoff', '', NULL);
old_get_string('settings', '', NULL);
old_get_string('assignroles', 'role', NULL);
old_get_string('grades', '', NULL);
old_get_string('outcomes', 'grades', NULL);
old_get_string('groups', '', NULL);
old_get_string('backup', '', NULL);
old_get_string('restore', '', NULL);
old_get_string('import', '', NULL);
old_get_string('reset', '', NULL);
old_get_string('reports', '', NULL);
old_get_string('questions', 'quiz', NULL);
old_get_string('files', '', NULL);
old_get_string('profile', '', NULL);
old_get_string('showblocka', 'access', 'Administration');
old_get_string('hideblocka', 'access', 'Administration');
old_get_string('skipa', 'access', 'Administration');
old_get_string('showblocka', 'access', 'Administration');
old_get_string('hideblocka', 'access', 'Administration');
old_get_string('courses', '', NULL);
old_get_string('delete', '', NULL);
old_get_string('moveup', '', NULL);
old_get_string('movedown', '', NULL);
old_get_string('moveright', '', NULL);
old_get_string('moveleft', '', NULL);
old_get_string('hide', '', NULL);
old_get_string('show', '', NULL);
old_get_string('configuration', '', NULL);
old_get_string('assignroles', 'role', NULL);
old_get_string('coursecategory', '', NULL);
old_get_string('fulllistofcourses', '', NULL);
old_get_string('categories', '', NULL);
old_get_string('showblocka', 'access', 'Course categories');
old_get_string('hideblocka', 'access', 'Course categories');
old_get_string('skipa', 'access', 'Course categories');
old_get_string('showblocka', 'access', 'Course categories');
old_get_string('hideblocka', 'access', 'Course categories');
old_get_string('latestnews', '', NULL);
old_get_string('addanewtopic', 'forum', NULL);
old_get_string('strftimerecent', '', NULL);
old_get_string('more', 'forum', NULL);
old_get_string('oldertopics', 'forum', NULL);
old_get_string('delete', '', NULL);
old_get_string('moveup', '', NULL);
old_get_string('movedown', '', NULL);
old_get_string('moveright', '', NULL);
old_get_string('moveleft', '', NULL);
old_get_string('hide', '', NULL);
old_get_string('show', '', NULL);
old_get_string('configuration', '', NULL);
old_get_string('assignroles', 'role', NULL);
old_get_string('showblocka', 'access', 'Latest News');
old_get_string('hideblocka', 'access', 'Latest News');
old_get_string('skipa', 'access', 'Latest News');
old_get_string('showblocka', 'access', 'Latest News');
old_get_string('hideblocka', 'access', 'Latest News');
old_get_string('blockname', 'block_online_users', NULL);
old_get_string('delete', '', NULL);
old_get_string('moveup', '', NULL);
old_get_string('movedown', '', NULL);
old_get_string('moveright', '', NULL);
old_get_string('moveleft', '', NULL);
old_get_string('hide', '', NULL);
old_get_string('show', '', NULL);
old_get_string('configuration', '', NULL);
old_get_string('assignroles', 'role', NULL);
old_get_string('periodnminutes', 'block_online_users', 5);
old_get_string('day', '', NULL);
old_get_string('days', '', NULL);
old_get_string('hour', '', NULL);
old_get_string('hours', '', NULL);
old_get_string('min', '', NULL);
old_get_string('mins', '', NULL);
old_get_string('sec', '', NULL);
old_get_string('secs', '', NULL);
old_get_string('year', '', NULL);
old_get_string('years', '', NULL);
old_get_string('showblocka', 'access', 'Online Users');
old_get_string('hideblocka', 'access', 'Online Users');
old_get_string('skipa', 'access', 'Online Users');
old_get_string('showblocka', 'access', 'Online Users');
old_get_string('hideblocka', 'access', 'Online Users');
old_get_string('recentactivity', '', NULL);
old_get_string('delete', '', NULL);
old_get_string('moveup', '', NULL);
old_get_string('movedown', '', NULL);
old_get_string('moveright', '', NULL);
old_get_string('moveleft', '', NULL);
old_get_string('hide', '', NULL);
old_get_string('show', '', NULL);
old_get_string('configuration', '', NULL);
old_get_string('assignroles', 'role', NULL);
old_get_string('strftimedaydatetime', 'langconfig', NULL);
old_get_string('activitysince', '', 'Wednesday, 25 March 2009, 02:39 PM');
old_get_string('recentactivityreport', '', NULL);
old_get_string('publishanonymous', 'choice', NULL);
old_get_string('publishnames', 'choice', NULL);
old_get_string('publishnot', 'choice', NULL);
old_get_string('publishafteranswer', 'choice', NULL);
old_get_string('publishafterclose', 'choice', NULL);
old_get_string('publishalways', 'choice', NULL);
old_get_string('displayhorizontal', 'choice', NULL);
old_get_string('displayvertical', 'choice', NULL);
old_get_string('nothingnew', '', NULL);
old_get_string('showblocka', 'access', 'Recent Activity');
old_get_string('hideblocka', 'access', 'Recent Activity');
old_get_string('skipa', 'access', 'Recent Activity');
old_get_string('showblocka', 'access', 'Recent Activity');
old_get_string('hideblocka', 'access', 'Recent Activity');
old_get_string('feedstitle', 'block_rss_client', NULL);
old_get_string('remotenewsfeed', 'block_rss_client', NULL);
old_get_string('delete', '', NULL);
old_get_string('moveup', '', NULL);
old_get_string('movedown', '', NULL);
old_get_string('moveright', '', NULL);
old_get_string('moveleft', '', NULL);
old_get_string('hide', '', NULL);
old_get_string('show', '', NULL);
old_get_string('configuration', '', NULL);
old_get_string('assignroles', 'role', NULL);
old_get_string('feedsconfigurenewinstance', 'block_rss_client', NULL);
old_get_string('feedsconfigurenewinstance', 'block_rss_client', NULL);
old_get_string('showblocka', 'access', 'Remote News Feed');
old_get_string('hideblocka', 'access', 'Remote News Feed');
old_get_string('skipa', 'access', 'Remote News Feed');
old_get_string('showblocka', 'access', 'Remote News Feed');
old_get_string('hideblocka', 'access', 'Remote News Feed');
old_get_string('html', 'block_html', NULL);
old_get_string('newhtmlblock', 'block_html', NULL);
old_get_string('delete', '', NULL);
old_get_string('moveup', '', NULL);
old_get_string('movedown', '', NULL);
old_get_string('moveright', '', NULL);
old_get_string('moveleft', '', NULL);
old_get_string('hide', '', NULL);
old_get_string('show', '', NULL);
old_get_string('configuration', '', NULL);
old_get_string('assignroles', 'role', NULL);
old_get_string('showblocka', 'access', '(new HTML block)');
old_get_string('hideblocka', 'access', '(new HTML block)');
old_get_string('skipa', 'access', '(new HTML block)');
old_get_string('showblocka', 'access', '(new HTML block)');
old_get_string('hideblocka', 'access', '(new HTML block)');
old_get_string('blocks', '', NULL);
old_get_string('add', '', NULL);
old_get_string('adminbookmarks', '', NULL);
old_get_string('blockmenutitle', 'blog', NULL);
old_get_string('blocktagstitle', 'blog', NULL);
old_get_string('calendar', 'calendar', NULL);
old_get_string('upcomingevents', 'calendar', NULL);
old_get_string('pagedescription', 'block_course_summary', NULL);
old_get_string('blockname', 'block_glossary_random', NULL);
old_get_string('html', 'block_html', NULL);
old_get_string('loancalc', 'block_loancalc', NULL);
old_get_string('blockname', 'block_mentees', NULL);
old_get_string('messages', 'message', NULL);
old_get_string('mnet_hosts', 'block_mnet_hosts', NULL);
old_get_string('formaltitle', 'block_quiz_results', NULL);
old_get_string('feedstitle', 'block_rss_client', NULL);
old_get_string('blockname', 'block_search', NULL);
old_get_string('blockname', 'block_section_links', NULL);
old_get_string('blocktagstitle', 'tag', NULL);
old_get_string('skipa', 'access', '');
old_get_string('showblocka', 'access', '');
old_get_string('hideblocka', 'access', '');
old_get_string('weeklyoutline', '', NULL);
old_get_string('assignroles', 'role', NULL);
old_get_string('delete', '', NULL);
old_get_string('move', '', NULL);
old_get_string('moveup', '', NULL);
old_get_string('movedown', '', NULL);
old_get_string('moveright', '', NULL);
old_get_string('moveleft', '', NULL);
old_get_string('update', '', NULL);
old_get_string('duplicate', '', NULL);
old_get_string('hide', '', NULL);
old_get_string('show', '', NULL);
old_get_string('clicktochange', '', NULL);
old_get_string('forcedmode', '', NULL);
old_get_string('groupsnone', '', NULL);
old_get_string('groupsseparate', '', NULL);
old_get_string('groupsvisible', '', NULL);
old_get_string('modulenameplural', 'assignment', NULL);
old_get_string('typeupload', 'assignment', NULL);
old_get_string('typeonline', 'assignment', NULL);
old_get_string('typeuploadsingle', 'assignment', NULL);
old_get_string('typeoffline', 'assignment', NULL);
old_get_string('resourcetypelabel', 'resource', NULL);
old_get_string('resourcetypetext', 'resource', NULL);
old_get_string('resourcetypehtml', 'resource', NULL);
old_get_string('resourcetypefile', 'resource', NULL);
old_get_string('resourcetypedirectory', 'resource', NULL);
old_get_string('resourcetypeims', 'resource', NULL);
old_get_string('addactivity', '', NULL);
old_get_string('addresource', '', NULL);
old_get_string('helpprefix2', '', 'Add a resource');
old_get_string('newwindow', '', NULL);
old_get_string('helpprefix2', '', 'Add an activity');
old_get_string('newwindow', '', NULL);
old_get_string('strftimedateshort', '', NULL);
old_get_string('showonlyweek', '', 1);
old_get_string('addactivity', '', NULL);
old_get_string('addresource', '', NULL);
old_get_string('helpprefix2', '', 'Add a resource');
old_get_string('newwindow', '', NULL);
old_get_string('helpprefix2', '', 'Add an activity');
old_get_string('newwindow', '', NULL);
old_get_string('showonlyweek', '', 2);
old_get_string('addactivity', '', NULL);
old_get_string('addresource', '', NULL);
old_get_string('helpprefix2', '', 'Add a resource');
old_get_string('newwindow', '', NULL);
old_get_string('helpprefix2', '', 'Add an activity');
old_get_string('newwindow', '', NULL);
old_get_string('currentweek', 'access', NULL);
old_get_string('showonlyweek', '', 3);
old_get_string('addactivity', '', NULL);
old_get_string('addresource', '', NULL);
old_get_string('helpprefix2', '', 'Add a resource');
old_get_string('newwindow', '', NULL);
old_get_string('helpprefix2', '', 'Add an activity');
old_get_string('newwindow', '', NULL);
old_get_string('home', '', NULL);
old_get_string('loggedinas', 'moodle', '<a  href="http://tim.moodle.com/moodle/user/view.php?id=2&amp;course=2">Admin User</a>');
old_get_string('logout', '', NULL);
old_get_string('sizegb', '', NULL);
old_get_string('sizemb', '', NULL);
old_get_string('sizekb', '', NULL);
old_get_string('sizeb', '', NULL);
old_get_string('moodledocslink', '', NULL);
