// UK lang variables

tinyMCE.addToLang('',{
bold_desc : 'Bold (Ctrl+B)',
italic_desc : 'Italig (Ctrl+I)',
underline_desc : 'Tanlinellu (Ctrl+U)',
striketrough_desc : 'Llinell drwodd',
justifyleft_desc : 'Unioni i\'r chwith',
justifycenter_desc : 'Unioni i\'r canol',
justifyright_desc : 'Unioni i\'r dde',
justifyfull_desc : 'Unioni llawn',
bullist_desc : 'Rhestr heb drefn',
numlist_desc : 'Rhestr mewn trefn',
outdent_desc : 'Lleihau mewnoliad',
indent_desc : 'Cynyddu mewnoliad',
undo_desc : 'Dadwneud (Ctrl+Z)',
redo_desc : 'Ailwneud (Ctrl+Y)',
link_desc : 'Mewnosod/golygu dolen',
unlink_desc : 'Dadgysylltu',
image_desc : 'Mewnosod/golygu delwedd',
cleanup_desc : 'Tacluso c&ocirc;d',
focus_alert : 'Rhaid rhoi ffocws i\'r golygydd cyn defnyddio\'r gorchymyn hwn.',
edit_confirm : 'Wyt ti eisiau defnyddio\'r dull WYSIWYG ar gyfer yr ardal destun hon?',
insert_link_title : 'Mewnosod/golygu dolen',
insert : 'Mewnosod',
update : 'Diweddaru',
cancel : 'Diddymu',
insert_link_url : 'URL dolen',
insert_link_target : 'Targed',
insert_link_target_same : 'Agor dolen yn yr un ffenest',
insert_link_target_blank : 'Agor dolen mewn ffenest newydd',
insert_image_title : 'Mewnosod/golygu delwedd',
insert_image_src : 'URL delwedd',
insert_image_alt : 'Disgrifiad delwedd',
help_desc : 'Cymorth',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Dyw Cop&iuml;o/Torri/Gludo ddim ar gael ym Mozilla na Firefox.\nHoffet ti ragor o wybodaeth ynghylch hyn?',
popup_blocked : 'Mae\'n ddrwg gennym, ond mae dy declyn atal ffenestri naid wedi analluogi ffenest sy\'n cynnig nodweddion i\'r rhaglen. Bydd rhaid i ti analluogi atal ffenestri naid ar gyfer y safle hon er mwyn cael y defnydd gorau o\'r rhaglen hwn.'
});
