// Greek lang variables by Jacaranda Bill

tinyMCE.addToLang('',{
bold_desc : 'Έντονη γρα&ouml;ή',
italic_desc : 'Πλάγια γρα&ouml;ή',
underline_desc : 'Υπογράμμιση',
striketrough_desc : '&Auml;ιακριτή &auml;ιαγρα&ouml;ή',
justifyleft_desc : 'Στοίχιση αριστ&aring;ρά',
justifycenter_desc : 'Στοίχιση στο κέντρο',
justifyright_desc : 'Στοίχιση &auml;&aring;ξιά',
justifyfull_desc : 'Πλήρης στοίχιση',
bullist_desc : 'Κουκκί&auml;&aring;ς',
numlist_desc : 'Αρίθμηση',
outdent_desc : 'Μ&aring;ίωση &aring;σοχής',
indent_desc : 'Αύξηση &aring;σοχής',
undo_desc : 'Αναίρ&aring;ση',
redo_desc : 'Ακύρωση αναίρ&aring;σης',
link_desc : '&Auml;ημιουργία/&Auml;ιόρθωση υπ&aring;ρ-σύν&auml;&aring;σης',
unlink_desc : '&Auml;ιαγρα&ouml;ή υπ&aring;ρ-σύν&auml;&aring;σης',
image_desc : '&Aring;ισαγωγή/&Auml;ιόρθωση &aring;ικόνας',
cleanup_desc : 'Καθάρισμα κώ&auml;ικα',
focus_alert : 'Πρέπ&aring;ι να υπάρχ&aring;ι &aring;ν&aring;ργός κάποιος &aring;π&aring;ξ&aring;ργαστής κ&aring;ιμένου πριν να χρησιμοποιήσ&aring;τ&aring; αυτή την &aring;ντολή.',
edit_confirm : 'Θέλ&aring;τ&aring; να χρησιμοποιήσ&aring;τ&aring; την κατάσταση WYSIWYG για το συγκ&aring;κριμένο πλαίσιο κ&aring;ιμένου;',
insert_link_title : '&Auml;ημιουργία/&Auml;ιόρθωση υπ&aring;ρ-σύν&auml;&aring;σης',
insert : '&Aring;ισαγωγή',
update : '&Aring;ισαγωγή',
cancel : 'Ακύρωση',
insert_link_url : '&Auml;ι&aring;ύθυνση',
insert_link_target : 'Στόχος',
insert_link_target_same : '’νοιγμα της &auml;ι&aring;ύθυνσης στο ί&auml;ιο παράθυρο',
insert_link_target_blank : '’νοιγμα της &auml;ι&aring;ύθυνσης σ&aring; νέο παράθυρο',
insert_image_title : '&Aring;ισαγωγή/&Auml;ιόρθωση &aring;ικόνας',
insert_image_src : '&Auml;ι&aring;ύθυνση',
insert_image_alt : 'Π&aring;ριγρα&ouml;ή',
help_desc : 'Βοήθ&aring;ια',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
