// FI lang variables by Urho Konttori from Absolutions
// Updated by Tuomo Aura, Ateco.fi

tinyMCE.addToLang('',{
bold_desc : 'Lihavoi (Ctrl+B)',
italic_desc : 'Kursivoi (Ctrl+I)',
underline_desc : 'Alleviivaa (Ctrl+U)',
striketrough_desc : 'Yliviivaa',
justifyleft_desc : 'Vasen tasaus',
justifycenter_desc : 'Keskitys',
justifyright_desc : 'Oikea tasaus',
justifyfull_desc : 'Pakotettu tasaus',
bullist_desc : 'Luettelo',
numlist_desc : 'Numeroitu lista',
outdent_desc : 'Poista sisennyt',
indent_desc : 'Sisennys',
undo_desc : 'Peruuta (Ctrl+Z)',
redo_desc : 'Tee uudelleen (Ctrl+Y)',
link_desc : 'Lis&auml;&auml; linkki',
unlink_desc : 'Poista linkki',
image_desc : 'Lis&auml;&auml; kuva',
cleanup_desc : 'Siisti koodi',
focus_alert : 'Teksink&auml;sittelyalue t&auml;ytyy olla valittuna ennen t&auml;m&auml;n komennon suorittamista.',
edit_confirm : 'Haluatko k&auml;ytt&auml;&auml; WYSIWYG-tilaa t&auml;h&auml;n tekstialueeseen?',
insert_link_title : 'Lis&auml;&auml;/muokkaa linkki&auml;',
insert : 'Lis‰‰',
update : 'P‰ivit‰',
cancel : 'Peruuta',
insert_link_url : 'Linkin URL',
insert_link_target : 'Kohde',
insert_link_target_same : 'Avaa linkki samassa ikkunassa',
insert_link_target_blank : 'Avaa linkki uudessa ikkunassa',
insert_image_title : 'Lis&auml;&auml;/muokkaa kuvaa',
insert_image_src : 'Kuvan URL',
insert_image_alt : 'Kuvan selite',
help_desc : 'Apua',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Leikkaus/Kopiointi/Liit&auml;minen ei onnistu Mozilla eik&auml; Firefox -selaimilla tietoturvasta johtuen. \n Haluatko lis&auml;tietoa aiheesta?',
popup_blocked : 'Koneellasi oleva popup-ikkunoiden esto-ohjelma est&auml;&auml; tarvittavan ikkunan avaamisen. Sinun pit&auml;&auml; sallia popup-ikkunoiden n&auml;ytt&auml;minen t&auml;ll&auml; sivustolla ohjelman asetuksista.'
});
