// FR lang variables by Pat Boens
// Modify by Laurent Dran
// Modifié par Normand Lamoureux le 2005-11-12

tinyMCE.addToLang('',{
bold_desc : 'Gras',
italic_desc : 'Italique',
underline_desc : 'Souligné',
striketrough_desc : 'Barré',
justifyleft_desc : 'Aligner à gauche',
justifycenter_desc : 'Centrer',
justifyright_desc : 'Aligner à droite',
justifyfull_desc : 'Justifier',
bullist_desc : 'Liste à puces',
numlist_desc : 'Liste numérotée',
outdent_desc : 'Diminuer le retrait',
indent_desc : 'Augmenter le retrait',
undo_desc : 'Annuler',
redo_desc : 'Restaurer',
link_desc : 'Insérer/Modifier un lien',
unlink_desc : 'Supprimer le lien',
image_desc : 'Insérer/Modifier une image',
cleanup_desc : 'Nettoyer le code',
focus_alert : 'Une instance de l\éditeur doit avoir le focus avant d\'utiliser cette commande.',
edit_confirm : 'Voulez-vous utiliser le mode WYSIWYG pour cette zone d\'édition de texte ?',
insert_link_title : 'Gestionnaire d\'hyperlien',
insert : 'Insérer',
update : 'Appliquer',
cancel : 'Annuler',
insert_link_url : 'Lien URL',
insert_link_target : 'Cible',
insert_link_target_same : 'Ouvrir dans la même fenêtre',
insert_link_target_blank : 'Ouvrir dans une nouvelle fenêtre',
insert_image_title : 'Gestionnaire d\'image',
insert_image_src : 'URL de l\'image',
insert_image_alt : 'Équivalent textuel',
help_desc : 'Aide',
bold_img : "bold_fr.gif",
italic_img : "italic.gif",
underline_img : "underline_fr.gif",
clipboard_msg : 'Pour des raisons de sécurité, les fonctions « Copier », « Couper » et « Coller »\nne sont pas disponibles dans Mozilla et Firefox.\n\n\nVoulez-vous plus d\'information à ce sujet?\n',
popup_blocked : 'Désolé, mais votre bloqueur de pop-up empêche le fonctionnement normal de l\'application.\n\n\nPour utiliser cet outil, veuillez régler votre navigateur pour qu\'il accepte les pop-up de ce site.'
});
