// Canadian French lang variables by Virtuelcom

tinyMCE.addToLang('',{
bold_desc : 'Gras',
italic_desc : 'Italique',
underline_desc : 'Souligner',
striketrough_desc : 'Barrer',
justifyleft_desc : 'Aligner à gauche',
justifycenter_desc : 'Aligner au centre',
justifyright_desc : 'Aligner à droite',
justifyfull_desc : 'Justifier',
bullist_desc : 'Puces',
numlist_desc : 'Numérotation',
outdent_desc : 'Réduire le retrait',
indent_desc : 'Augmenter le retrait',
undo_desc : 'Annuler la dernière action',
redo_desc : 'Refaire la dernière action annulée',
link_desc : 'Insérer un hyperlien',
unlink_desc : 'Supprimer un hyperlien',
image_desc : 'Insérer une image',
cleanup_desc : 'Nettoyer le code',
focus_alert : 'Un éditeur doit être sélectionné pour utiliser cette fonction.',
edit_confirm : 'Désirez-vous utiliser l\'éditeur pour modifier cette zone?',
insert_link_title : 'Insérer / Modifier un hyperlien',
insert : 'Insérer',
update : 'Insérer',
cancel : 'Annuler',
insert_link_url : 'Adresse URL',
insert_link_target : 'Destination',
insert_link_target_same : 'Ouvrir dans la même fenêtre',
insert_link_target_blank : 'Ouvrir dans une nouvelle fenêtre',
insert_image_title : 'Insérer / Modifier une image',
insert_image_src : 'Adresse de l\'image',
insert_image_alt : 'Description de l\'image',
help_desc : 'Aide',
bold_img : "bold_fr.gif",
italic_img : "italic.gif",
underline_img : "underline_fr.gif",
clipboard_msg : 'Copier/Couper/Coller ne sont pas disponibles dans Mozilla et FireFox.\nDésirez-vous consulter de plus amples informations à ce sujet?'
});
