// HE lang variables by Liron Newman, http://eesh.net

tinyMCE.addToLang('',{
bold_desc : 'מודגש (Ctrl+B)',
italic_desc : 'נטוי (Ctrl+I)',
underline_desc : 'קו תחתי (Ctrl+U)',
striketrough_desc : 'קו חוצה',
justifyleft_desc : 'ישר לשמאל',
justifycenter_desc : 'ישר למרכז',
justifyright_desc : 'ישר לימין',
justifyfull_desc : 'ישר לשני הצדדים',
bullist_desc : 'רשימה חסרת סדר',
numlist_desc : 'רשימה מסודרת',
outdent_desc : 'הקטן כניסה',
indent_desc : 'הגדל כניסה',
undo_desc : 'בטל (Ctrl+Z)',
redo_desc : 'בצע שוב (Ctrl+Y)',
link_desc : 'הכנס/ערוך קישור',
unlink_desc : 'בטל קישור',
image_desc : 'הכנס/ערוך תמונה',
cleanup_desc : 'נקה קוד מבולגן',
focus_alert : 'יש לבחור בשדה עריכה לפני שניתן להשתמש בפקודה זו.',
edit_confirm : 'האם ברצונך להשתמש במצב עריכה עשירה (WYSIWYG) עבור שדה טקסט זה?',
insert_link_title : 'הכנס/ערוך קישור',
insert : 'הכנס',
update : 'עדכן',
cancel : 'בטל',
insert_link_url : 'כתובת (URL) הקישור',
insert_link_target : 'יעד',
insert_link_target_same : 'פתח את הקישור באותו חלון',
insert_link_target_blank : 'פתח את הקישור בחלון חדש',
insert_image_title : 'הכנס/ערוך תמונה',
insert_image_src : 'כתובת (URL) התמונה',
insert_image_alt : 'תיאור התמונה',
help_desc : 'עזרה',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'פעולות העתקה/גזירה/הדבקה אינן נתמכות תחת Mozilla ו-Firefox.\nהאם ברצונך לקבל מידע נוסף אודות נושא זה?',
popup_blocked : 'סליחה, אך שמנו לב כי חוסם החלונות הקופצים שלך חסם חלון שמהווה חלק מהיישום. תצטרך לבטל את חסימת החלונות הקופצים באתר זה כדי לנצל כלי זה במלואו.'
});
