// HU lang variables

tinyMCE.addToLang('',{
bold_desc : 'Félkövér',
italic_desc : 'Dölt',
underline_desc : 'Aláhúzott',
striketrough_desc : 'Áthúzott',
justifyleft_desc : 'Balra igazított',
justifycenter_desc : 'Középre igazított',
justifyright_desc : 'Jobbra igazított',
justifyfull_desc : 'Telejesen igazított',
bullist_desc : 'Rendezetlen lista',
numlist_desc : 'Rendezett lista',
outdent_desc : 'Kihúzás',
indent_desc : 'Behúzás',
undo_desc : 'visszavonás',
redo_desc : 'Ismét',
link_desc : 'Link hozzáadása/szerkesztése',
unlink_desc : 'Link megszüntetése',
image_desc : 'Kép beillesztése/szerkesztése',
cleanup_desc : 'Rendetlen kód tisztítása',
focus_alert : 'Egy szerkesztõablakra muszáj fókuszálni ennek a parancsnak a használata elõtt.',
edit_confirm : 'Szeretnéd használni ezt a WYSIWYG módot ehhez a szövegmezõhöz?',
insert_link_title : 'Link beillesztése/szerkesztése',
insert : 'Beillesztés',
update : 'Frissítés',
cancel : 'Mégse',
insert_link_url : 'Link URL',
insert_link_target : 'Cél',
insert_link_target_same : 'Link megnyitása ugyanabban az ablakban',
insert_link_target_blank : 'Link megnyitása új ablakban',
insert_image_title : 'Kép beillesztése/szerkesztése',
insert_image_src : 'Kép URL',
insert_image_alt : 'Kép leírása',
help_desc : 'Súgó',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'A Másolás/Kivágás/Beillesztés nem elérhetõ Mozillában and Firefox-ban.\nSzeretnél több információt errõl a problémáról?',
popup_blocked : 'Sajnálom, de észrevettem, hogy a popup-blokkolód letiltotta az ablakot, ami biztosítja ennek az alkalmazásnak a mûködését. Meg kell szüntetned a popup-blokkolást ennek a segédeszköznek a teljes használatához.'
});
