// Variabili lingua IT - fabrix.xm@lombardiacom.it

tinyMCE.addToLang('',{
bold_desc : 'Grassetto',
italic_desc : 'Corsivo',
underline_desc : 'Sottolineato',
striketrough_desc : 'Barrato',
justifyleft_desc : 'Allinea a sinistra',
justifycenter_desc : 'Allinea centrato',
justifyright_desc : 'Allinea a destra',
justifyfull_desc : 'Giustifica',
bullist_desc : 'Lista non ordinata',
numlist_desc : 'Lista ordinata',
outdent_desc : 'Rientra',
indent_desc : 'Indenta',
undo_desc : 'Annulla',
redo_desc : 'Ripeti',
link_desc : 'Inserisci link',
unlink_desc : 'Elimina link',
image_desc : 'Inserisci immagine',
cleanup_desc : 'Pulisci il  codice',
focus_alert : 'Una istanza dell\' editor deve essere selezionata prima di usare questo comando.',
edit_confirm : 'Vuoi usare la modalit\u00E0 WYSIWYG per questa textarea?',
insert_link_title : 'Inserisci/modifica link',
insert : 'Inserisci',
update : 'Inserisci',
cancel : 'Cancella',
insert_link_url : 'Link URL',
insert_link_target : 'Target',
insert_link_target_same : 'Apri il link nella stessa finestra',
insert_link_target_blank : 'Apri il link in una nuova finestra',
insert_image_title : 'Inserisci/modifica immagine',
insert_image_src : 'URL immagine',
insert_image_alt : 'Descrizione dell\'immagine',
help_desc : 'Guida',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copia, Taglia e Incolla non sono disponibili in Mozilla e Firefox.\nVuoi maggiori dettegli su questo problema?',
popup_blocked : 'Spiacenti, un sistema di blocco popup ha impedito l\'apertura di una finestra necessaria per il funzionamento dell\'editor. Disabilita il blocco popup per questo sito se vuoi utilizzare tutte le funzionalità.'
});
