// JP lang variables

tinyMCE.addToLang('',{
bold_desc : '太字',
italic_desc : '斜体',
underline_desc : '下線',
striketrough_desc : '抹消線',
justifyleft_desc : '左詰め',
justifycenter_desc : '中央合わせ',
justifyright_desc : '右詰め',
justifyfull_desc : '行揃え',
bullist_desc : '箇条書',
numlist_desc : '番号付き箇条書',
outdent_desc : '字上げ',
indent_desc : '字下げ',
undo_desc : 'やりなおし',
redo_desc : '再実行',
link_desc : 'リンクの挿入/編集',
unlink_desc : 'リンクの削除',
image_desc : '画像の挿入/編集',
cleanup_desc : 'コード整理',
focus_alert : 'このコマンドを使う前にエディタ上のどこかを選択する必要があります。',
edit_confirm : 'WYSIWYGモードでこのテキストエリアを編集しますか？',
insert_link_title : 'リンクの挿入/編集',
insert : '挿入',
update : '挿入',
cancel : '取り消し',
insert_link_url : 'リンク先URL',
insert_link_target : 'ターゲット',
insert_link_target_same : '同じ窓でリンクを開く',
insert_link_target_blank : '新しい窓でリンクを開く',
insert_image_title : '画像の挿入/編集',
insert_image_src : '画像のURL',
insert_image_alt : '画像の説明',
help_desc : 'ヘルプ',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
