// NL lang variables thanks to "Meint Post"
// Updates by (2.0) Mark van der Sanden

tinyMCE.addToLang('',{
bold_desc : 'Vet (Ctrl+B)',
italic_desc : 'Cursief (Ctrl+I)',
underline_desc : 'Onderstrepen (Ctrl+U)',
striketrough_desc : 'Doorhalen',
justifyleft_desc : 'Links uitlijnen',
justifycenter_desc : 'Centreren',
justifyright_desc : 'Rechts uitlijnen',
justifyfull_desc : 'Volledig uitlijnen',
bullist_desc : 'Opsommingstekens',
numlist_desc : 'Genummerde lijst',
outdent_desc : 'Inspringen verkleinen',
indent_desc : 'Inspringen vergroten',
undo_desc : 'Ongedaan maken (Ctrl+Z)',
redo_desc : 'Opnieuw (Ctrl+Y)',
link_desc : 'Hyperlink invoegen/bewerken',
unlink_desc : 'Hyperlink verwijderen',
image_desc : 'Afbeelding invoegen',
cleanup_desc : 'Code opschonen',
focus_alert : 'Klik op de tekst in de editor voor het uitvoeren van dit commando.',
edit_confirm : 'Wilt u de WYSIWYG modus voor deze textarea gebruiken?',
insert_link_title : 'Hyperlink invoegen/bewerken',
insert : 'OK',
update : 'Toepassen',
cancel : 'Annuleren',
insert_link_url : 'URL link',
insert_link_target : 'Bestemming',
insert_link_target_same : 'Open link in hetzelfde venster',
insert_link_target_blank : 'Open link in een nieuw venster',
insert_image_title : 'Afbeelding invoegen/bewerken',
insert_image_src : 'Afbeelding',
insert_image_alt : 'Beschrijving',
help_desc : 'Help',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Kopiëren/knippen/plakken is niet beschikbaar in Mozilla en Firefox.\nWilt u meer informatie over deze kwestie?',
popup_blocked : 'Uw browser heeft zojuist geweigerd een popup-venster te tonen. Waarschijnlijk gebruikt u een poup-blocker die voor deze editor te streng omgaat met popups. Om het venster toch te tonen, zult u uw popup-blocker zo in moeten stellen dat het popups van deze website toestaat.'
});
