// nn = Norwegian (nynorsk) lang variables by Knut B. Jacobsen

tinyMCE.addToLang('',{
bold_desc : 'Feit',
italic_desc : 'Kursiv',
underline_desc : 'Understreking',
striketrough_desc : 'Gjennomstreking',
justifyleft_desc : 'Venstrestill',
justifycenter_desc : 'Sentrer',
justifyright_desc : 'H&oslash;grestill',
justifyfull_desc : 'Blokkjustering',
bullist_desc : 'Punktliste',
numlist_desc : 'Nummerliste',
outdent_desc : 'Reduser innrykk',
indent_desc : 'Auk innrykk',
undo_desc : 'Angre',
redo_desc : 'Gjer om',
link_desc : 'Opprett/endre lenke',
unlink_desc : 'Fjern lenke',
image_desc : 'Sett inn/endre bilde',
cleanup_desc : 'Rens grisete kode',
focus_alert : 'Editoren m&aring; v&aelig;re i fokus f&oslash;r du benytter denne kommando.',
edit_confirm : 'Vil du benytte WYSIWYG editoren for dette tekstfelt?',
insert_link_title : 'Opprett/endre lenke',
insert : 'Sett inn',
update : 'Oppdater',
cancel : 'Avbryt',
insert_link_url : 'Lenkens URL',
insert_link_target : 'Vindu',
insert_link_target_same : '&Aring;pne i samme vindauge',
insert_link_target_blank : '&Aring;pne i nytt vindauge',
insert_image_title : 'Opprett/endre bilde',
insert_image_src : 'Bildets URL',
insert_image_alt : 'Bildets beskrivelse',
help_desc : 'Hjelp',
bold_img : 'bold_de_se.gif',
italic_img : 'italic_de_se.gif',
underline_img : 'underline.gif',
clipboard_msg : 'Klipp ut/Kopier/Lim inn fungerer ikkje i Mozilla og Firefox. Vil du vite meir om dette?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
