// Russian KOI8-R translation by Vladimir Vitkovsky
// admin@transport.su
// www.webgui.uanet.biz

tinyMCE.addToLang('',{
bold_desc : 'Полужирный',
italic_desc : 'Курсив',
underline_desc : 'Подчеркнутый',
striketrough_desc : 'Перечеркнутый',
justifyleft_desc : 'Выравнивание влево',
justifycenter_desc : 'Выравнивание по центру',
justifyright_desc : 'Выравнивание вправо',
justifyfull_desc : 'Равномерное заполнение',
bullist_desc : 'Маркированный список',
numlist_desc : 'Нумерованный список',
outdent_desc : 'Уменьшить отступ',
indent_desc : 'Увеличить отспут',
undo_desc : 'Отменить',
redo_desc : 'Вернуть',
link_desc : 'Вставить/изменить ссылку',
unlink_desc : 'Убрать ссылку',
image_desc : 'Вставить/изменить изображение',
cleanup_desc : 'Подчистить избыточный код',
focus_alert : 'Для использования данной команды Вы должны находится в поле редактора.',
edit_confirm : 'Хотите ли Вы редактировать в визуальном (WYSIWYG) режиме?',
insert_link_title : 'Вставить/изменить ссылку',
insert : 'Вставить',
update : 'Применить',
cancel : 'Отменить',
insert_link_url : 'Адрес ссылки',
insert_link_target : 'Открыть в...:',
insert_link_target_same : 'том же окне',
insert_link_target_blank : 'новом окне',
insert_image_title : 'Вставить/изменить изображение',
insert_image_src : 'Адрес картинки',
insert_image_alt : 'Описание картинки',
help_desc : 'Помощь',
bold_img : "bold_ru.gif",
italic_img : "italic_ru.gif",
underline_img : "underline_ru.gif",
clipboard_msg : 'Копировать/Вырезать/Вставить недоступны для Mozilla и Firefox.\nХотите узнать об этом подробнее?',
popup_blocked : 'Извините, но в Вашем браузере заблокированы всплывающие окна. Для того, чтобы иметь возможность воспользоваться всеми возможностями редактора, необходимо отключить блокировку всплывающих окон для этого сайта.'
});
