// Russian UTF-8 translation by Vladimir Vitkovsky
// admin@transport.su
// www.webgui.uanet.biz

tinyMCE.addToLang('',{
bold_desc : '',
italic_desc : '',
underline_desc : '',
striketrough_desc : '',
justifyleft_desc : ' ',
justifycenter_desc : '  ',
justifyright_desc : ' ',
justifyfull_desc : ' ',
bullist_desc : ' ',
numlist_desc : ' ',
outdent_desc : ' ',
indent_desc : ' ',
undo_desc : '',
redo_desc : '',
link_desc : '/ ',
unlink_desc : ' ',
image_desc : '/ ',
cleanup_desc : '  ',
focus_alert : '         .',
edit_confirm : '      (WYSIWYG) ?',
insert_link_title : '/ ',
insert : '',
update : '',
cancel : '',
insert_link_url : ' ',
insert_link_target : ' ...:',
insert_link_target_same : '  ',
insert_link_target_blank : ' ',
insert_image_title : '/ ',
insert_image_src : ' ',
insert_image_alt : ' ',
help_desc : '',
bold_img : "bold_ru.gif",
italic_img : "italic_ru.gif",
underline_img : "underline_ru.gif",
clipboard_msg : '//   Mozilla  Firefox.\n    ?',
popup_blocked : ',       .  ,       ,        .'
});
