// SE lang variables

tinyMCE.addToLang('',{
bold_desc : 'Fet',
italic_desc : 'Kursiv',
underline_desc : 'Understruken',
striketrough_desc : 'Genomstruken',
justifyleft_desc : 'V&auml;nsterjustera',
justifycenter_desc : 'Centrera',
justifyright_desc : 'H&ouml;gerjustera',
justifyfull_desc : 'Kantjustera',
bullist_desc : 'Punktlista',
numlist_desc : 'Nummerlista',
outdent_desc : 'Utdrag',
indent_desc : 'Indrag',
undo_desc : '&Aring;ngra',
redo_desc : 'G&ouml;r om',
link_desc : 'Skapa l&auml;nk',
unlink_desc : 'Ta bort l&auml;nk',
image_desc : 'Skapa/redigera bild',
cleanup_desc : 'Rensa skr&auml;pkod',
focus_alert : 'Flytta mark&ouml;ren till en textyta innan du anv&auml;nder detta kommando.',
edit_confirm : 'Vill du anv&auml;nda WYSIWYG-editorn f&ouml;r detta textf&auml;lt?',
insert_link_title : 'Skapa/redigera l&auml;nk',
insert : 'Skapa',
update : 'Uppdatera',
cancel : 'Avbryt',
insert_link_url : 'L&auml;nkens URL',
insert_link_target : 'F&ouml;nster',
insert_link_target_same : '&Ouml;ppna l&auml;nken i samma f&ouml;nster',
insert_link_target_blank : '&Ouml;ppna l&auml;nken i ett nytt f&ouml;nster',
insert_link_delta_width : 20,
insert_link_delta_height : 10,
insert_image_title : 'Skapa/redigera bild',
insert_image_src : 'Bildens URL',
insert_image_alt : 'Bildens beskrivning',
bold_img : 'bold_de_se.gif',
italic_img : 'italic_de_se.gif',
underline_img : "underline.gif",
clipboard_msg : 'Klipput/Kopiera/Klistra fungerar inte Mozilla och Firefox. Vill du veta mer om detta?',
help_desc : "Hj&auml;lp",
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
