// TH lang variables Thai contributed by Innozent

tinyMCE.addToLang('',{
bold_desc : 'ตัวหนา',
italic_desc : 'ตัว้เอียง',
underline_desc : 'ขีดเส้นใต้',
striketrough_desc : 'ขีดค&Aring;่อม',
justifyleft_desc : 'ชิดขอบซ้าย',
justifycenter_desc : 'ก&Ouml;่งก&Aring;าง',
justifyright_desc : 'ชิดขอบขวา',
justifyfull_desc : 'จัดชิดขอบ',
bullist_desc : 'สัญ&Aring;ักษณ์แสดงหัวข้อย่อย',
numlist_desc : '&Aring;ำดับเ&Aring;ข',
outdent_desc : '&Aring;ดการเยื้อง',
indent_desc : 'เพิ่มการเยื้อง',
undo_desc : 'เ&Aring;ิกทำ',
redo_desc : 'ทำใหม่',
link_desc : 'เพิ่ม&Aring;ิงค์',
unlink_desc : '&Aring;บ&Aring;ิงค์',
image_desc : 'ใส่รูป',
cleanup_desc : 'ทำความสะอาดข้อความ',
focus_alert : 'ต้องเ&Aring;ือกก&Aring;่องข้อความก่อนที่จะใช้คำสั่งนี้',
edit_confirm : 'คุณต้องการที่จะใช้ WYSIWYG mode สำหรับก&Aring;่องข้อความนี้หรือ&auml;ม่?',
insert_link_title : 'เพิ่ม/แก้&auml;ข &Aring;ิงค์',
insert : 'เพิ่ม',
cancel : 'ยกเ&Aring;ิก',
insert_link_url : 'Link URL',
insert_link_target : 'เปิด&Aring;ิงค์ใน',
insert_link_target_same : 'หน้าต่างเดียวกัน',
insert_link_target_blank : 'หน้าต่างใหม่',
insert_image_title : 'เพิ่ม/แก้&auml;ข รูป',
insert_image_src : 'URL ของรูป',
insert_image_alt : 'คำอธิบายรูป',
help_desc : 'ช่วยเห&Aring;ือ',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
popup_blocked : 'Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.'
});
