// TR lang variables

tinyMCE.addToLang('',{
bold_desc : 'Kalýn (Ctrl+B)',
italic_desc : 'Ýtalik (Ctrl+I)',
underline_desc : 'Altý çizgili (Ctrl+U)',
striketrough_desc : 'Üstü çizgili',
justifyleft_desc : 'Sola dayalý',
justifycenter_desc : 'Ortalanmýþ',
justifyright_desc : 'Saða dayalý',
justifyfull_desc : 'Ýki kenara yaslanmýþ',
bullist_desc : 'Sýrasýz liste',
numlist_desc : 'Sýralý liste',
outdent_desc : 'Girintiyi azalt',
indent_desc : 'Girintiyi arttýr',
undo_desc : 'Geri al (Ctrl+Z)',
redo_desc : 'Yeniden yap (Ctrl+Y)',
link_desc : 'Link ekle/düzenle',
unlink_desc : 'Linki kaldýr',
image_desc : 'Resim ekle/düzenle',
cleanup_desc : 'Daðýnýk kodu düzenle',
focus_alert : 'Bu komutu kullanmadan önce editör seçilmeli(aktif olmalý).',
edit_confirm : 'Bu text alaný için WYSIWYG modu kullanmak ister misiniz?',
insert_link_title : 'Link ekle/düzenle',
insert : 'Ekle',
update : 'Güncelle',
cancel : 'Ýptal',
insert_link_url : 'Link adresi giriniz',
insert_link_target : 'Hedef adres',
insert_link_target_same : 'Linki ayný sayfada aç',
insert_link_target_blank : 'Linki yeni sayfada aç',
insert_image_title : 'Resim ekle/düzenle',
insert_image_src : 'Resim adresi',
insert_image_alt : 'Resim açýklamasý',
help_desc : 'Yardým',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Mozilla ve Firefox tarayýcýlarýnda kopyala/kes/yapýþtýr komutlarýný kullanamassýnýz.\n Bu konu hakkýnda daha fazla bilgi edinmek ister misiniz?',
popup_blocked : 'Popup engelleyiciniz programýn çalýþmasýný önlemektedir, bu özellikten yararlanabilmeniz için popup engelleyicinizi kapatmanýz gerekiyor.'
});