// Simplified Chinese lang variables contributed by tom_cat (thomaswangyang@gmail.com)

tinyMCE.addToLang('',{
bold_desc : '黑体 (Ctrl+B)',
italic_desc : '斜体 (Ctrl+I)',
underline_desc : '下划线 (Ctrl+U)',
striketrough_desc : '删除线',
justifyleft_desc : '左对齐',
justifycenter_desc : '居中对齐',
justifyright_desc : '右对齐',
justifyfull_desc : '两端对齐',
bullist_desc : '无序列表',
numlist_desc : '有序列表',
outdent_desc : '减少缩进',
indent_desc : '增加缩进',
undo_desc : '撤消 (Ctrl+Z)',
redo_desc : '重做 (Ctrl+Y)',
link_desc : '插入/编辑 链接',
unlink_desc : '删除链接',
image_desc : '插入/编辑 图像',
cleanup_desc : '删除冗余代码',
focus_alert : '请先选择编辑区',
edit_confirm : '您想在编辑区域上使用所见即所得编辑器么？',
insert_link_title : '插入/编辑 链接',
insert : '插入',
update : '更新',
cancel : '取消',
insert_link_url : '链接地址',
insert_link_target : '链接目标',
insert_link_target_same : '在同一窗口中打开链接',
insert_link_target_blank : '在新窗口中打开链接',
insert_image_title : '插入/编辑 图像',
insert_image_src : '图像地址',
insert_image_alt : '图像描述',
help_desc : '帮助',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : '剪切/复制/粘贴功能在 Mozilla 和 Firefox 浏览器中不支持。您希望获得更多的信息吗？',
popup_blocked : '对不起, 您的浏览器禁止了弹出式窗口。为了让您使用到最完善的功能，请对本网站的弹出式窗口解除禁止。'
});
