// Traditional Chinese UTF-8; Twapweb Site translated; twapweb_AT_gmail_DOT_com
// 繁體中文 UTF-8 ；數位應用坊製作； twapweb_AT_gmail_DOT_com

tinyMCE.addToLang('',{
bold_desc : '粗體（Ctrl+B）',
italic_desc : '斜體（Ctrl+I）',
underline_desc : '加底線（Ctrl+U）',
striketrough_desc : '刪除線',
justifyleft_desc : '靠左',
justifycenter_desc : '置中',
justifyright_desc : '靠右',
justifyfull_desc : '整篇對齊',
bullist_desc : '項目方式條列',
numlist_desc : '編號方式條列',
outdent_desc : '擴大縮排',
indent_desc : '減小縮排',
undo_desc : '復原（Ctrl+Z）',
redo_desc : '重複（Ctrl+Y）',
link_desc : '插入或編輯連結',
unlink_desc : '刪除連結',
image_desc : '插入或編輯圖檔',
cleanup_desc : '清除冗碼',
focus_alert : '使用此指令前須先指定編輯器',
edit_confirm : '要於此文字輸入區中採用所視即得模式嗎？',
insert_link_title : '插入或編輯連結',
insert : '插入',
update : '更新',
cancel : '取消',
insert_link_url : '連結網址',
insert_link_target : '對象',
insert_link_target_same : '於同視窗中開啟連結',
insert_link_target_blank : '以新視窗中開啟連結',
insert_image_title : '插入或編輯圖檔',
insert_image_src : '圖檔網址',
insert_image_alt : '圖檔說明',
help_desc : '協助',
bold_img : "bold_tw.gif",
italic_img : "italic_tw.gif",
underline_img : "underline_tw.gif",
clipboard_msg : '在 Mozilla 和 Firefox 中無法使用複製或剪下或貼上功能。\n需要更多關於此的訊息嗎？',
popup_blocked : '喔！您有設置跳現視窗隔絕機制，已將功能跳現視窗給隔絕了。\n請調整跳現視窗隔絕機制的設定，才能正常使用此功能。'
});
