/**
 * Czech lang variables 
 * encoding: utf-8
 *  
 * $Id$ 
 */  


tinyMCE.addToLang('',{
theme_style_select : 'Styly',
theme_code_desc : 'Zobrazit HTML',
theme_code_title : 'Editace HTML',
theme_code_wordwrap : 'Bez dělení slov',
theme_sub_desc : 'Dolní index',
theme_sup_desc : 'Horní index',
theme_hr_desc : 'Vložit vodorovný oddělovač',
theme_removeformat_desc : 'Zrušit formátování',
theme_custom1_desc : 'Libovolný popisek',
insert_image_border : 'Rámeček',
insert_image_dimensions : 'Rozměry',
insert_image_vspace : 'Vertikální okraj',
insert_image_hspace : 'Horizontální okraj',
insert_image_align : 'Zarovnání',
insert_image_align_default : 'Výchozí',
insert_image_align_baseline : 'Na účaří',
insert_image_align_top : 'Nahoru',
insert_image_align_middle : 'Na střed',
insert_image_align_bottom : 'Dolů',
insert_image_align_texttop : 'Nejvyšší bod textu',
insert_image_align_absmiddle : 'Střed řádku',
insert_image_align_absbottom : 'Spodek řádku',
insert_image_align_left : 'Vlevo',
insert_image_align_right : 'Vpravo',
theme_font_size : '-- Velikost textu --',
theme_fontdefault : '-- Písmo --',
theme_block : '-- Formát --',
theme_paragraph : 'Odstavec',
theme_div : 'Div',
theme_address : 'Adresa',
theme_pre : 'Předformát',
theme_h1 : 'Nadpis 1',
theme_h2 : 'Nadpis 2',
theme_h3 : 'Nadpis 3',
theme_h4 : 'Nadpis 4',
theme_h5 : 'Nadpis 5',
theme_h6 : 'Nadpis 6',
theme_colorpicker_title : 'Výběr barvy',
theme_colorpicker_apply : 'Vybrat',
theme_forecolor_desc : 'Barva popředí',
theme_backcolor_desc : 'Barva pozadí',
theme_charmap_title : 'Výběr znaku',
theme_charmap_desc : 'Vložit znak',
theme_visualaid_desc : 'Zapnout značky/neviditelné prvky',
insert_anchor_title : 'Vložení/editace záložky',
insert_anchor_name : 'Název',
theme_anchor_desc : 'Vložit/editovat záložku',
theme_insert_link_titlefield : 'Název',
theme_clipboard_msg : 'Funkce Kopírovat/vyjmout/vložit nejsou použitelné v Mozille a Firefoxu.\nChcete více informací o tomto problému?',
theme_path : 'Cesta',
cut_desc : 'Vyjmout',
copy_desc : 'Kopírovat',
paste_desc : 'Vložit',
link_list : 'Seznam',
image_list : 'Seznam',
browse : 'Procházet',
image_props_desc : 'Vlastnosti obrázku',
newdocument_desc : 'Nový dokument',
newdocument : 'Jste si opravdu jistý(á), že chcete vymazat veškerý obsah?'
});

