// UK lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Arddulliau --',
theme_code_desc : 'Golygu c&ocirc;d HTML',
theme_code_title : 'Golygydd C&ocirc;d HTML',
theme_code_wordwrap : 'Amlapio geiriau',
theme_sub_desc : 'Is-sgript',
theme_sup_desc : 'Uwch-sgript',
theme_hr_desc : 'Mewnosod llinell llorweddol',
theme_removeformat_desc : 'Diddymu fformatio',
theme_custom1_desc : 'Dy ddisgrifiad fan hyn',
insert_image_border : 'Ymyl',
insert_image_dimensions : 'Meintiau',
insert_image_vspace : 'Gofod fertigol',
insert_image_hspace : 'Gofod llorweddol',
insert_image_align : 'Unioniad',
insert_image_align_default : '-- Heb ddewis --',
insert_image_align_baseline : 'Gwaelodlin',
insert_image_align_top : 'Brig',
insert_image_align_middle : 'Canol',
insert_image_align_bottom : 'Gwaelod',
insert_image_align_texttop : 'Brig Testun',
insert_image_align_absmiddle : 'Canol Union',
insert_image_align_absbottom : 'Gwaelod Union',
insert_image_align_left : 'Chwith',
insert_image_align_right : 'Dde',
theme_font_size : '-- Maint ffont --',
theme_fontdefault : '-- Teulu ffont --',
theme_block : '-- Fformat --',
theme_paragraph : 'Paragraff',
theme_div : 'Div',
theme_address : 'Cyfeiriad',
theme_pre : 'Rhag-fformatiwyd',
theme_h1 : 'Pennawd 1',
theme_h2 : 'Pennawd 2',
theme_h3 : 'Pennawd 3',
theme_h4 : 'Pennawd 4',
theme_h5 : 'Pennawd 5',
theme_h6 : 'Pennawd 6',
theme_colorpicker_title : 'Dewis lliw',
theme_colorpicker_apply : 'Gosod',
theme_forecolor_desc : 'Dewis lliw testun',
theme_backcolor_desc : 'Dewis lliw cefndir',
theme_charmap_title : 'Dewis llythyren arbennig',
theme_charmap_desc : 'Gosod llythyren arbennig',
theme_visualaid_desc : 'Gwrthdroi canllawiau/elfennau anweledig',
insert_anchor_title : 'Mewnosod/golygu angor',
insert_anchor_name : 'Enw angor',
theme_anchor_desc : 'Mewnosod/golygu angor',
theme_insert_link_titlefield : 'Teitl',
theme_clipboard_msg : 'Dyw Cop&iuml;o/Torri/Gludo ddim ar gael ym Mozilla na Firefox.\nHoffet ti ragor o wybodaeth ynghylch hyn?',
theme_path : 'Llwybr',
cut_desc : 'Torri',
copy_desc : 'Cop&iuml;o',
paste_desc : 'Gludo',
link_list : 'Rhestr dolenni',
image_list : 'Rhestr delweddau',
browse : 'Pori',
image_props_desc : 'Priodoleddau delwedd',
newdocument_desc : 'Dogfen newydd',
class_name : 'Dosbarth',
newdocument : 'Wyt ti\'n sicr eisiau clirio\'r holl gynnwys?',
about_title : 'Yngl&#375;n &acirc; TinyMCE',
about : 'Yngl&#375;n &acirc;',
license : 'Trwydded',
plugins : 'Ategynnau',
plugin : 'Ategyn',
author : 'Awdur',
version : 'Fersiwn',
loaded_plugins : 'Ategynnau gweithredol',
help : 'Cymorth',
not_set : '-- Heb ddewis --',
close : 'Cau',
toolbar_focus : 'Neidio i fotymau offer - Alt+Q, Neidio i\'r golygydd - Alt+Z, Neidio i lwybr y elfen - Alt+X'
});
