// Greek lang variables by Jacaranda Bill

tinyMCE.addToLang('',{
theme_style_select : 'Θέματα',
theme_code_desc : '&Aring;π&aring;ξ&aring;ργασία HTML κώ&auml;ικα',
theme_code_title : '&Aring;π&aring;ξ&aring;ργαστής HTML',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : '&Auml;&aring;ίκτης',
theme_sup_desc : '&Aring;κθέτης',
theme_hr_desc : '&Aring;ισαγωγή οριζόντιας γραμμής',
theme_removeformat_desc : 'Απαλοι&ouml;ή μορ&ouml;οποίησης',
theme_custom1_desc : 'Π&aring;ριγρα&ouml;ή',
insert_image_border : 'Π&aring;ρίγραμμα',
insert_image_dimensions : '&Auml;ιαστάσ&aring;ις',
insert_image_vspace : 'Κάθ. π&aring;ριθώριο',
insert_image_hspace : 'Οριζ. π&aring;ριθώριο',
insert_image_align : 'Στοίχιση',
insert_image_align_default : 'Προκαθορισμένη',
insert_image_align_baseline : 'Σ&aring; &aring;υθυγράμμιση μ&aring; το κ&aring;ίμ&aring;νο',
insert_image_align_top : 'Πάνω',
insert_image_align_middle : 'Στο κέντρο',
insert_image_align_bottom : 'Κάτω',
insert_image_align_texttop : 'Το κ&aring;ίμ&aring;νο πάνω',
insert_image_align_absmiddle : 'Απόλυτα στο κέντρο',
insert_image_align_absbottom : 'Απόλυτα κάτω',
insert_image_align_left : 'Αριστ&aring;ρά',
insert_image_align_right : '&Auml;&aring;ξιά',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : 'Παράγρα&ouml;ος',
theme_div : 'Div',
theme_address : '&Auml;ι&aring;ύθυνση',
theme_pre : 'Preformatted',
theme_h1 : '&Aring;πικ&aring;&ouml;αλί&auml;α 1',
theme_h2 : '&Aring;πικ&aring;&ouml;αλί&auml;α 2',
theme_h3 : '&Aring;πικ&aring;&ouml;αλί&auml;α 3',
theme_h4 : '&Aring;πικ&aring;&ouml;αλί&auml;α 4',
theme_h5 : '&Aring;πικ&aring;&ouml;αλί&auml;α 5',
theme_h6 : '&Aring;πικ&aring;&ouml;αλί&auml;α 6',
theme_colorpicker_title : 'Χρώματα',
theme_colorpicker_apply : '&Aring;&ouml;αρμογή',
theme_forecolor_desc : '&Aring;πιλογή χρώματος γραμματοσ&aring;ιράς',
theme_backcolor_desc : 'Select background color',
theme_charmap_title : '&Aring;πιλογή &aring;ι&auml;ικού χαρακτήρα',
theme_charmap_desc : '&Aring;ισαγωγή &aring;ι&auml;ικού χαρακτήρα',
theme_visualaid_desc : '&Aring;μ&ouml;άνιση/Απόκρυψη γραμμών',
insert_anchor_title : '&Aring;ισαγωγή/&Auml;ιόρθωση άγκυρας',
insert_anchor_name : 'Ονομασία άγκυρας',
theme_anchor_desc : '&Aring;ισαγωγή/&Auml;ιόρθωση άγκυρας',
theme_insert_link_titlefield : 'Τίτλος',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
class_name : 'Κλάση', 
newdocument : 'Are you sure you want clear all contents?'
});
