// FI lang variables by Urho Konttori from Absolutions
// Updated by Tuomo Aura from Ateco.fi

tinyMCE.addToLang('',{
theme_style_select : '-- Tyylit --',
theme_code_desc : 'Muokkaa HTML-l&auml;hdekoodia',
theme_code_title : 'HTML-L&auml;hdekoodin muokkaus',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : 'Alaindeksi',
theme_sup_desc : 'Yl&auml;indeksi',
theme_hr_desc : 'Lis&auml;&auml; vaakaviiva',
theme_removeformat_desc : 'Poista muotoilu',
theme_custom1_desc : 'Kirjoita oma selityksesi t&auml;h&auml;n',
insert_image_border : 'Reuna',
insert_image_dimensions : 'Mitat',
insert_image_vspace : 'Pystyv&auml;li',
insert_image_hspace : 'Vaakav&auml;li',
insert_image_align : 'Asettelu',
insert_image_align_default : 'Oletus',
insert_image_align_baseline : 'Perustasoon',
insert_image_align_top : 'Yl&auml;laitaan',
insert_image_align_middle : 'Keskelle',
insert_image_align_bottom : 'Alalaitaan',
insert_image_align_texttop : 'Tekstin yl&auml;laitaan',
insert_image_align_absmiddle : 'Absoluuttisen keskelle',
insert_image_align_absbottom : 'Absoluuttisen alas',
insert_image_align_left : 'Vasemmalle',
insert_image_align_right : 'Oikealle',
theme_font_size : '-- Fonttikoko --',
theme_fontdefault : '-- Fontti --',
theme_block : '-- Muotoilu --',
theme_paragraph : 'Kappale',
theme_div : 'Div',
theme_address : 'Osoite',
theme_pre : 'Etuk&auml;teen muotoiltu',
theme_h1 : 'Otsikko 1',
theme_h2 : 'Otsikko 2',
theme_h3 : 'Otsikko 3',
theme_h4 : 'Otsikko 4',
theme_h5 : 'Otsikko 5',
theme_h6 : 'Otsikko 6',
theme_colorpicker_title : 'Valitse v&auml;ri',
theme_colorpicker_apply : 'Aseta v&auml;ri',
theme_forecolor_desc : 'Valitse fontin v&auml;ri',
theme_backcolor_desc : 'Valitse taustav&auml;ri',
theme_charmap_title : 'Valitse erikoismerkki',
theme_charmap_desc : 'Lis&auml;&auml; oma erikoismerkki',
theme_visualaid_desc : 'N&auml;yt&auml;/piilota apuviivat',
insert_anchor_title : 'Lis&auml;&auml;/muokkaa ankkuria',
insert_anchor_name : 'Ankkurin nimi',
theme_anchor_desc : 'Lis&auml;&auml;/muokkaa ankkuria',
theme_insert_link_titlefield : 'Title',
theme_clipboard_msg : 'Leikkaus/Kopiointi/Liit&auml;minen ei onnistu Mozilla eik&auml; Firefox -selaimilla tietoturvasyist&auml;. \n Haluatko lis&auml;tietoa aiheesta?',
theme_path : 'Polku',
cut_desc : 'Leikkaa',
copy_desc : 'Kopioi',
paste_desc : 'Liit&auml;',
link_list : 'Linkkilista',
image_list : 'Kuvalista',
browse : 'Selaa',
image_props_desc : 'Kuvan ominaisuudet',
newdocument_desc : 'Uusi dokumentti',
class_name : 'Luokka',
newdocument : 'Oletko varma, ett&auml; haluat poistaa kaiken sis&auml;ll&ouml;n?',
about_title : 'TinyMCE:n tiedot',
about : 'Tiedot',
license : 'Lisenssi',
plugins : 'Pluginit',
plugin : 'Plugini',
author : 'Tekij&auml;',
version : 'Versio',
loaded_plugins : 'Ladatut pluginit',
help : 'Apua',
not_set : '-- Ei asetettu --',
close : 'Sulje',
toolbar_focus : 'Hypp&auml;&auml; ty&ouml;kalupainikkeisiin - Alt+Q, Hypp&auml;&auml; editoriin - Alt-Z, Hypp&auml;&auml; polkuun - Alt-X'
});
