// Canadian French lang variables by Virtuelcom   last modification: 2005-06-15

tinyMCE.addToLang('',{
theme_style_select : '-- Styles --',
theme_code_desc : 'Modifier le code source HTML',
theme_code_title : 'Éditeur de code source HTML',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : 'Souscrit',
theme_sup_desc : 'Indice supérieur',
theme_hr_desc : 'Insérer un séparateur horizontal',
theme_removeformat_desc : 'Supprimer le formattage',
theme_custom1_desc : 'Votre description personnalisée ici',
insert_image_border : 'Bordure',
insert_image_dimensions : 'Dimensions',
insert_image_vspace : 'VSpace',
insert_image_hspace : 'HSpace',
insert_image_align : 'Alignement',
insert_image_align_default : 'Défaut',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Haut',
insert_image_align_middle : 'Milieu',
insert_image_align_bottom : 'Bas',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Milieu absolu',
insert_image_align_absbottom : 'Bas absolu',
insert_image_align_left : 'Gauche',
insert_image_align_right : 'Droit',
theme_font_size : 'Taille',
theme_fontdefault : '-- Police --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraphe',
theme_div : 'Div',
theme_address : 'Addresse',
theme_pre : 'Préformatté',
theme_h1 : 'Entête 1',
theme_h2 : 'Entête 2',
theme_h3 : 'Entête 3',
theme_h4 : 'Entête 4',
theme_h5 : 'Entête 5',
theme_h6 : 'Entête 6',
theme_colorpicker_title : 'Choisir une couleur',
theme_colorpicker_apply : 'Appliquer',
theme_forecolor_desc : 'Choisir la couleur d\'avant plan',
theme_backcolor_desc : 'Choisir une couleur d\'arrière plan',
theme_charmap_title : 'Sélectionner un charactère spécial',
theme_charmap_desc : 'Insérer un charactère spécial',
theme_visualaid_desc : 'Active/Désactive les lignes guides et les éléments invisibles',
insert_anchor_title : 'Insérer/Modifier une ancre',
insert_anchor_name : 'Nom de l\'ancre',
theme_anchor_desc : 'Insérer / Modifier une ancre',
theme_insert_link_titlefield : 'Titre',
theme_clipboard_msg : 'Copier/Couper/Coller ne sont pas disponibles dans Mozilla et FireFox.\nDésirez-vous consulter de plus amples informations à ce sujet?',
theme_path : 'Chemin',
cut_desc : 'Couper',
copy_desc : 'Copier',
paste_desc : 'Coller',
link_list : 'Liste de liens',
image_list : 'Liste d\'images',
browse : 'Sélectionner',
image_props_desc : 'Propriétés de l\'image',
newdocument_desc : 'Nouveau Document',
class_name : 'Classe',
newdocument : 'Are you sure you want clear all contents?'
});
