// HE lang variables by Liron Newman, http://eesh.net

tinyMCE.addToLang('',{
theme_style_select : '-- סיגנונות --',
theme_code_desc : 'ערוך את קוד ה-HTML',
theme_code_title : 'עורך קוד HTML',
theme_code_wordwrap : 'גלישת שורות',
theme_sub_desc : 'כתב תחתי',
theme_sup_desc : 'כתב עילי',
theme_hr_desc : 'הכנס קו אופקי',
theme_removeformat_desc : 'הסר עיצוב',
theme_custom1_desc : 'התיאור שלך כאן',
insert_image_border : 'גבול',
insert_image_dimensions : 'מימדים',
insert_image_vspace : 'חלל אנכי',
insert_image_hspace : 'חלל אופקי',
insert_image_align : 'יישור',
insert_image_align_default : 'ברירת מחדל',
insert_image_align_baseline : 'לקו הבסיס',
insert_image_align_top : 'למעלה',
insert_image_align_middle : 'לאמצע',
insert_image_align_bottom : 'למטה',
insert_image_align_texttop : 'לראש הטקסט',
insert_image_align_absmiddle : 'לאמצע מוחלט',
insert_image_align_absbottom : 'לקצה תחתון מוחלט',
insert_image_align_left : 'לשמאל',
insert_image_align_right : 'לימין',
theme_font_size : 'גודל גופן',
theme_fontdefault : '-- משפחת גופנים --',
theme_block : '-- עיצוב --',
theme_paragraph : 'פסקה',
theme_div : 'קטע',
theme_address : 'כתובת',
theme_pre : 'מעוצב מראש',
theme_h1 : 'כותרת 1',
theme_h2 : 'כותרת 2',
theme_h3 : 'כותרת 3',
theme_h4 : 'כותרת 4',
theme_h5 : 'כותרת 5',
theme_h6 : 'כותרת 6',
theme_colorpicker_title : 'בחר צבע',
theme_colorpicker_apply : 'החל',
theme_forecolor_desc : 'בחר צבע טקסט',
theme_backcolor_desc : 'בחר צבע רקע',
theme_charmap_title : 'בחר תו מיוחד',
theme_charmap_desc : 'הכנס תו מיוחד',
theme_visualaid_desc : 'החלף מצב קווים מנחים/רכיבים בלתי-נראים',
insert_anchor_title : 'הכנס/ערוך עוגן',
insert_anchor_name : 'שם העוגן',
theme_anchor_desc : 'הכנס/ערוך עוגן',
theme_insert_link_titlefield : 'כותרת',
theme_clipboard_msg : 'פעולות העתקה/גזירה/הדבקה אינן נתמכות תחת Mozilla ו-Firefox.\nהאם ברצונך לקבל מידע נוסף אודות נושא זה?',
theme_path : 'נתיב',
cut_desc : 'גזור',
copy_desc : 'העתק',
paste_desc : 'הדבק',
link_list : 'רשימת קישורים',
image_list : 'רשימת תמונות',
browse : 'סייר',
image_props_desc : 'מאפייני תמונה',
newdocument_desc : 'מסמך חדש',
class_name : 'מחלקה',
newdocument : 'האם אתה בטוח שברצונך לנקות את כל התוכן?',
about_title : 'אודות TinyMCE',
about : 'אודות',
license : 'רישיון',
plugins : 'תוספים',
plugin : 'תוסף',
author : 'מחבר',
version : 'גרסה',
loaded_plugins : 'תוספים פעילים',
help : 'עזרה',
not_set : '-- לא מוגדר --',
close : 'סגירה',
toolbar_focus : 'עבור אל כפתורי הכלים - Alt+Q, עבור אל העורך - Alt-Z, עבור אל נתיב עיצוב - Alt-X'
});
