// HU lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Stílusok --',
theme_code_desc : 'HTML forrás szerkesztése',
theme_code_title : 'HTML forrás szerkesztõ',
theme_code_wordwrap : 'Sortördelés',
theme_sub_desc : 'Alsóindex',
theme_sup_desc : 'Felsõindex',
theme_hr_desc : 'Vizszíntes vonal beszúrása',
theme_removeformat_desc : 'Formázás eltávolítása',
theme_custom1_desc : 'Az egyéni leírásod jön ide',
insert_image_border : 'Keret',
insert_image_dimensions : 'Kiterjedés',
insert_image_vspace : 'Függõleges terület',
insert_image_hspace : 'Vizszintes terület',
insert_image_align : 'Elhelyezkedés',
insert_image_align_default : '-- Nincs beállítva --',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Felül',
insert_image_align_middle : 'Középen',
insert_image_align_bottom : 'Alul',
insert_image_align_texttop : 'Szövegfelett',
insert_image_align_absmiddle : 'Abszolút közép',
insert_image_align_absbottom : 'Abszolút alatt',
insert_image_align_left : 'Balra',
insert_image_align_right : 'Jobbra',
theme_font_size : '-- Betûméret --',
theme_fontdefault : '-- Betûcsalád --',
theme_block : '-- Formátum --',
theme_paragraph : 'Bekezdés',
theme_div : 'Div',
theme_address : 'Cím',
theme_pre : 'Elõreformázott',
theme_h1 : 'Fejléc 1',
theme_h2 : 'Fejléc 2',
theme_h3 : 'Fejléc 3',
theme_h4 : 'Fejléc 4',
theme_h5 : 'Fejléc 5',
theme_h6 : 'Fejléc 6',
theme_colorpicker_title : 'Színválasztás',
theme_colorpicker_apply : 'Alkalmaz',
theme_forecolor_desc : 'Szövegszín választás',
theme_backcolor_desc : 'Háttérszín választás',
theme_charmap_title : 'Egyéni karakter választás',
theme_charmap_desc : 'Egyéni karakter beszúrás',
theme_visualaid_desc : 'Sorjelölõk/láthatatlan elemek kapcsolása',
insert_anchor_title : 'Horgony nbeillesztése/szerkesztése',
insert_anchor_name : 'Horgony név',
theme_anchor_desc : 'Horgony nbeillesztése/szerkesztése',
theme_insert_link_titlefield : 'Cím',
theme_clipboard_msg : 'A Másolás/Kivágás/Beillesztés nem elérhetõ Mozillában and Firefox-ban.\nSzeretnél több információt errõl a problémáról?',
theme_path : 'Útvonal',
cut_desc : 'Kivágás',
copy_desc : 'Másolás',
paste_desc : 'Beillesztés',
link_list : 'Link lista',
image_list : 'Kép lista',
browse : 'Tallózás',
image_props_desc : 'Kép tulajdonságai',
newdocument_desc : 'Új dokumentum',
class_name : 'Osztály',
newdocument : 'Biztos hogy törölni akarod az összes tartalmat?',
about_title : 'TinyMCE névjegye',
about : 'Névjegy',
license : 'Licensz',
plugins : 'Bõvítmények',
plugin : 'Bõvítmény',
author : 'Szerzõ',
version : 'Verzió',
loaded_plugins : 'Betöltött bõvítmények',
help : 'Súgó',
not_set : '-- Nincs beállítva --',
close : 'Bezárás'
});
