// nb = Norwegian (bokm&aring;l) lang variables by Knut B. Jacobsen

tinyMCE.addToLang('',{
theme_style_select : 'Stiler',
theme_code_desc : 'Redigere HTML Koden',
theme_code_title : 'HTML Kildekode Redigering',
theme_code_wordwrap : 'Ord deling',
theme_sub_desc : 'Nedsenket skrift',
theme_sup_desc : 'Opph&oslash;yd skrift',
theme_hr_desc : 'Sett inn horisontal linje',
theme_removeformat_desc : 'Fjern formatering',
theme_custom1_desc : 'Din spesialfunksjons beskrivelse her',
insert_image_border : 'Ramme',
insert_image_dimensions : 'Dimensjoner',
insert_image_vspace : 'Vertikalt tomrom',
insert_image_hspace : 'Horisontalt tomrom',
insert_image_align : 'Justering',
insert_image_align_default : 'Intet',
insert_image_align_baseline : 'Bunnlinjen',
insert_image_align_top : 'Lengst opp',
insert_image_align_middle : 'Midten',
insert_image_align_bottom : 'Lengst ned',
insert_image_align_texttop : 'Tekstens topp',
insert_image_align_absmiddle : 'Absolutt midten',
insert_image_align_absbottom : 'Absolutt lengst ned',
insert_image_align_left : 'Venstre',
insert_image_align_right : 'H&oslash;yre',
insert_image_delta_width : 30,
insert_image_delta_height : 10,
theme_font_size : '-- Font st&oslash;rrelse --',
theme_fontdefault : '-- Font familie --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraf',
theme_div : 'Div',
theme_address : 'Adresse',
theme_pre : 'Pre-formattert',
theme_h1 : 'Overskrift 1',
theme_h2 : 'Overskrift 2',
theme_h3 : 'Overskrift 3',
theme_h4 : 'Overskrift 4',
theme_h5 : 'Overskrift 5',
theme_h6 : 'Overskrift 6',
theme_colorpicker_title : 'Velg en farge',
theme_colorpicker_apply : 'Bruk',
theme_forecolor_desc : 'Velg forgrunnsfarge',
theme_backcolor_desc : 'Velg bakgrunnsfarge',
theme_charmap_title : 'Velg spesialtegn',
theme_charmap_desc : 'Sett inn spesialtegn',
theme_visualaid_desc : 'Sl&aring; av/p&aring; usynlige elementer',
insert_anchor_title : 'Opprette/endre anker',
insert_anchor_name : 'Ankernavn',
theme_anchor_desc : 'Opprette/endre anker',
theme_insert_link_titlefield : 'Tittel',
theme_clipboard_msg : 'Kopier/Klipp ut/Lim inn er ikke tilgjengelig i Mozilla/Firefox.\nVil du ha mere informasjon om dette?',
theme_path : 'S&oslash;kevei',
cut_desc : 'Klipp ut',
copy_desc : 'Kopier',
paste_desc : 'Lim inn',
link_list : 'Lenke liste',
image_list : 'Bilde liste',
browse : 'Bla gjennom',
image_props_desc : 'Bilde egenskaper',
newdocument_desc : 'Nytt dokument',
class_name : 'Stil',
newdocument : 'Er du sikker p&aring; at du vil t&oslash;mme hele redigeringsomr&aring;det?',
about_title : 'Om TinyMCE',
about : 'Om',
license : 'Lisens',
plugins : 'Innstikksprogrammer',
plugin : 'Innstikksprogram',
author : 'Utviklere',
version : 'Versjon',
loaded_plugins : 'Lastet innstikksprogram',
help : 'Hjelp',
not_set : '-- Ikke satt --',
close : 'Stopp'
});
