// NL lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Stijlen --',
theme_code_desc : 'HTML bron bewerken',
theme_code_title : 'HTML code-editor',
theme_code_wordwrap : 'Terugloop',
theme_sub_desc : 'Subscript',
theme_sup_desc : 'Superscript',
theme_hr_desc : 'Horizontale lijn invoegen',
theme_removeformat_desc : 'Opmaak verwijderen',
theme_custom1_desc : 'Tik hier een omschrijving',
insert_image_border : 'Rand',
insert_image_dimensions : 'Afmetingen',
insert_image_vspace : 'Verticale marge',
insert_image_hspace : 'Horizontale marge',
insert_image_align : 'Uitlijning',
insert_image_align_default : '-- geen --',
insert_image_align_baseline : 'Basislijn',
insert_image_align_top : 'Boven',
insert_image_align_middle : 'Midden',
insert_image_align_bottom : 'Onder',
insert_image_align_texttop : 'Bovenkant tekst',
insert_image_align_absmiddle : 'Absoluut midden',
insert_image_align_absbottom : 'Absoluut onder',
insert_image_align_left : 'Links',
insert_image_align_right : 'Rechts',
theme_font_size : '-- Lettergrootte --',
theme_fontdefault : '-- Lettertype --',
theme_block : '-- Paragraaf --',
theme_paragraph : 'Paragraaf',
theme_div : 'Blok',
theme_address : 'Adres',
theme_pre : 'Opgemaakt',
theme_h1 : 'Kop 1',
theme_h2 : 'Kop 2',
theme_h3 : 'Kop 3',
theme_h4 : 'Kop 4',
theme_h5 : 'Kop 5',
theme_h6 : 'Kop 6',
theme_colorpicker_title : 'Selecteer een kleur',
theme_colorpicker_apply : 'Toepassen',
theme_forecolor_desc : 'Een tekstkleur selecteren',
theme_backcolor_desc : 'Een achtergrondkleur selecteren',
theme_charmap_title : 'Speciale tekens invoegen',
theme_charmap_desc : 'Speciale tekens invoegen',
theme_visualaid_desc : 'Onzichtbare elementen en hulplijnen aan/uit',
insert_anchor_title : 'Bladwijzer invoegen/bewerken',
insert_anchor_name : 'Bladwijzer naam',
theme_anchor_desc : 'Bladwijzer invoegen/bewerken',
theme_insert_link_titlefield : 'titel',
theme_clipboard_msg : 'Kopi&euml;ren/Knippen/Plakken is uit veiligheidsoverwegingen niet direct beschikbaar in Mozilla en Firefox.\nWilt u meer informatie over deze kwestie?',
theme_path : 'Pad',
cut_desc : 'Knippen',
copy_desc : 'Kopiëren',
paste_desc : 'Plakken',
link_list : 'Hyperlinklijst',
image_list : 'Afbeeldinglijst',
browse : 'Bladeren',
image_props_desc : 'Eigenschappen van afbeelding',
newdocument_desc : 'Nieuw document',
class_name : 'Stijl',
newdocument : 'Weet u zeker dat u de hele inhoud wilt wissen?',
about_title : 'Over TinyMCE',
about : 'Over',
license : 'Licentie',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Author',
version : 'Versie',
loaded_plugins : 'Ingeladen plugins',
help : 'Help',
not_set : '-- geen --',
close : 'Sluiten',
toolbar_focus : 'Ga naar werkbalk knoppen - Alt+Q, Ga naar editor - Alt-Z, Ga naar pad - Alt-X'
});
