/**
 * pt_br lang variables
 * Brazilian Portuguese
 *
 * Authors : ????
 * Revision and modifications:
 *           Marcio Barbosa (mpg) <mpg@mpg.com.br>
 * Last Updated : November 26, 2005
 * TinyMCE Version : 2.0RC4
 */
tinyMCE.addToLang('',{
theme_style_select : 'Estilos',
theme_code_desc : 'Editar Código HTML',
theme_code_title : 'Editor de Código HTML',
theme_code_wordwrap : 'Quebrar Linhas',
theme_sub_desc : 'Subscrito',
theme_sup_desc : 'Subrescrito',
theme_hr_desc : 'Inserir linha horizontal',
theme_removeformat_desc : 'Remover formatação',
theme_custom1_desc : 'Sua descrição personalizada aqui',
insert_image_border : 'Borda',
insert_image_dimensions : 'Dimensões',
insert_image_vspace : 'Espaço Vertical',
insert_image_hspace : 'Espaço Horizontal',
insert_image_align : 'Alinhamento',
insert_image_align_default : 'Padrão',
insert_image_align_baseline : 'Linha base',
insert_image_align_top : 'Topo',
insert_image_align_middle : 'Centro',
insert_image_align_bottom : 'Fundo',
insert_image_align_texttop : 'Texto ao Topo',
insert_image_align_absmiddle : 'Centro Absoluto',
insert_image_align_absbottom : 'Fundo Absoluto',
insert_image_align_left : 'Esquerda',
insert_image_align_right : 'Direita',
theme_font_size : '-- Corpo --',
theme_fontdefault : '-- Tipo de Fonte --',
theme_block : '-- Formato --',
theme_paragraph : 'Parágrafo',
theme_div : 'Div',
theme_address : 'Endereço',
theme_pre : 'Pré-formatado',
theme_h1 : 'Cabeçalho 1',
theme_h2 : 'Cabeçalho 2',
theme_h3 : 'Cabeçalho 3',
theme_h4 : 'Cabeçalho 4',
theme_h5 : 'Cabeçalho 5',
theme_h6 : 'Cabeçalho 6',
theme_colorpicker_title : 'Selecionar côr',
theme_colorpicker_apply : 'Aplicar',
theme_forecolor_desc : 'Selecionar côr do texto',
theme_backcolor_desc : 'Selecionar côr de fundo',
theme_charmap_title : 'Selecionar caracter especial',
theme_charmap_desc : 'Inserir caracter especial',
theme_charmap_alpha_desc : 'Caracteres alfabéticos',
theme_charmap_arrows_title : 'Flechas',
theme_charmap_arrows_desc : 'Caracteres de flechas',
theme_charmap_greek_title : 'Gregos',
theme_charmap_greek_desc : 'Caracteres Gregos',
theme_charmap_math_title : 'Mathematicos',
theme_charmap_math_desc : 'Caracteres mathematicos',
theme_charmap_misc_title : 'Diversos',
theme_charmap_misc_desc : 'Caracteres diversos',
theme_charmap_money_title : 'Moedas',
theme_charmap_money_desc : 'Caracteres de moedas',
theme_charmap_quotaion_title : 'Apóstrofes',
theme_charmap_quotaion_desc : 'Caracteres de Apóstrofe',
theme_visualaid_desc : 'Trocar as linhas de ajuda por elementos invisíveis',
insert_anchor_title : 'Inserir/editar âncora',
insert_anchor_name : 'Nome da âncora',
theme_anchor_desc : 'Inserir/editar âncora',
theme_insert_link_titlefield : 'Título',
theme_clipboard_msg : 'Não se pode utiliza os comando de Copiar / Cortar / Colar no Mozilla e Firefox.\r\nUse o teclado para Copiar (Ctrl+C) / Cortar (Ctrl+X) / Colar (Ctrl+V)\r\nQuer obter mais informação?',
theme_path : 'Rota',
cut_desc : 'Cortar (Ctrl+X)',
copy_desc : 'Copiar (Ctrl+C)',
paste_desc : 'Colar (Ctrl+V)',
link_list : 'Lista de links',
image_list : 'Lista de imagens',
browse : 'Navegar',
image_props_desc : 'Propriedades da imagem',
newdocument_desc : 'Novo documento',
class_name : 'Classe',
newdocument : 'Tem certesa que deseja apagar todo o conteúdo?',
about_title : 'Sobre o TinyMCE',
about : 'Sobre',
license : 'Licença',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Autor',
version : 'Versão',
loaded_plugins : 'Plugins carregados',
help : 'Ajuda',
not_set : '-- Por padrão --',
close : 'Fechar',
toolbar_focus : 'Ir para a barra de ferramentas - Alt+Q, Ir para o editor - Alt+Z, Ir para o elemento de destino - Alt+X',
theme_visualaid_desc : 'Tornar linhas visíveis/invisíveis',
insert_anchor_title : 'Inserir/editar âncora',
insert_anchor_name : 'Nome da âncora',
theme_anchor_desc : 'Inserir/editar âncora',
theme_insert_link_titlefield : 'Título',
theme_clipboard_msg : 'Copiar/Recortar/Colar não é permitido no Mozilla e Firefox.\nQuer mais informações sobre isso?',
theme_path : 'Caminho',
cut_desc : 'Recortar',
copy_desc : 'Copiar',
paste_desc : 'Colar',
link_list : 'Lista de Links',
image_list : 'Lista de Imagens',
browse : 'Navegar',
image_props_desc : 'Propriedades da Imagem',
newdocument_desc : 'Novo Documento',
class_name : 'Classe',
newdocument : 'Tem certeza que deseja limpar todo o conteúdo?',
theme_advanced_anchor_delta_width : 20
});
