// Russian lang variables UTF-8

tinyMCE.addToLang('',{
theme_style_select : '-- Стили --',
theme_code_desc : 'Редактировать HTML коды',
theme_code_title : 'Редактор HTML кодов',
theme_code_wordwrap : 'Перенос по словам',
theme_sub_desc : 'Нижний индекс',
theme_sup_desc : 'Верхний индекс',
theme_hr_desc : 'Вставить горизонтальный разделитель',
theme_removeformat_desc : 'Убрать форматирование',
theme_custom1_desc : 'Ваше произвольное описание',
insert_image_border : 'Рамка',
insert_image_dimensions : 'Размеры',
insert_image_vspace : 'Вертикальный отступ',
insert_image_hspace : 'Горизонтальный отступ',
insert_image_align : 'Выравнивание',
insert_image_align_default : '-- Не задано --',
insert_image_align_baseline : 'По базовой линии',
insert_image_align_top : 'По верху',
insert_image_align_middle : 'Посредине',
insert_image_align_bottom : 'По низу',
insert_image_align_texttop : 'По верху текста',
insert_image_align_absmiddle : 'Абсолютно посредине',
insert_image_align_absbottom : 'Абсолютно сверху',
insert_image_align_left : 'Влево',
insert_image_align_right : 'Вправо',
theme_font_size : '-- Размер шрифта --',
theme_fontdefault : '-- Семейство шрифтов --',
theme_block : '-- Формат --',
theme_paragraph : 'Абзац',
theme_div : 'Div',
theme_address : 'Стиль адреса',
theme_pre : ':`Предварительно форматированный',
theme_h1 : 'Заголовок 1',
theme_h2 : 'Заголовок 2',
theme_h3 : 'Заголовок 3',
theme_h4 : 'Заголовок 4',
theme_h5 : 'Заголовок 5',
theme_h6 : 'Заголовок 6',
theme_colorpicker_title : 'Выбрать цвет',
theme_colorpicker_apply : 'Применить',
theme_forecolor_desc : 'Выбрать цвет текста',
theme_backcolor_desc : 'Выбрать цвет фона',
theme_charmap_title : 'Выбор произвольного символа',
theme_charmap_desc : 'Вставить произвольный символ',
theme_visualaid_desc : 'Показать границы скрытых элементов',
insert_anchor_title : 'Вставить/редактировать якорь',
insert_anchor_name : 'Имя якоря',
theme_anchor_desc : 'Вставить/редактировать якорь',
theme_insert_link_titlefield : 'Заголовок',
theme_clipboard_msg : 'Копировать/Вырезать/Вставить недоступны для Mozilla и Firefox.\nХотите узнать об этом подробнее?',
theme_path : 'Путь',
cut_desc : 'Вырезать',
copy_desc : 'Копировать',
paste_desc : 'Вставить',
link_list : 'Перечань ссылок',
image_list : 'Перечень картинок',
browse : 'Подобрать',
image_props_desc : 'Свойства картинки',
newdocument_desc : 'Новый документ',
class_name : 'Класс',
newdocument : 'Вы уверены, что хотите очистить всё содержимое?',
about_title : 'О TinyMCE',
about : 'О TinyMCE',
license : 'Лицензия',
plugins : 'Плагины',
plugin : 'Плагин',
author : 'Автор',
version : 'Версия',
loaded_plugins : 'Загруженные плагины',
help : 'Помощь',
not_set : '-- не установлено --',
close : 'Закрыть',
toolbar_focus : 'Переместить фокус на панель инструментов - Alt+Q, Переместить фокус в редактор - Alt-Z, Переместить фокус на элемент пути - Alt-X'
});
