// SI lang variables ISO-8859-2

tinyMCE.addToLang('',{
theme_style_select : '-- Stili --',
theme_code_desc : 'Uredi HTML kodo',
theme_code_title : 'Urejevalnik HTML kode',
theme_code_wordwrap : 'Odre&#382;i vrstice',
theme_sub_desc : 'Podpisano',
theme_sup_desc : 'Nadpisano',
theme_hr_desc : 'Vstavi vodoravno &#269;rto',
theme_removeformat_desc : 'Odstrani oblikovanje',
theme_custom1_desc : 'Va&#353; opis',
insert_image_border : 'Okvir',
insert_image_dimensions : 'Dimenzije',
insert_image_vspace : 'Vertikalni razmak',
insert_image_hspace : 'Horizontalni razmak',
insert_image_align : 'Poravnava',
insert_image_align_default : '-- Brez --',
insert_image_align_baseline : 'Ob osnovni &#269;rti',
insert_image_align_top : 'Na vrh',
insert_image_align_middle : 'Na sredo',
insert_image_align_bottom : 'Na dno',
insert_image_align_texttop : 'Na vrh besedila',
insert_image_align_absmiddle : 'Absolutna sredina',
insert_image_align_absbottom : 'Absolutno dno',
insert_image_align_left : 'Levo',
insert_image_align_right : 'Desno',
theme_font_size : '-- Velikost pisave --',
theme_fontdefault : '-- Pisava --',
theme_block : '-- Format --',
theme_paragraph : 'Odstavek',
theme_div : 'Div',
theme_address : 'Naslov',
theme_pre : 'Oblikovano besedilo',
theme_h1 : 'Naslov 1',
theme_h2 : 'Naslov 2',
theme_h3 : 'Naslov 3',
theme_h4 : 'Naslov 4',
theme_h5 : 'Naslov 5',
theme_h6 : 'Naslov 6',
theme_colorpicker_title : 'Izberite barvo',
theme_colorpicker_apply : 'Uporabi',
theme_forecolor_desc : 'Izberite barvo pisave',
theme_backcolor_desc : 'Izberite barvo ozadja',
theme_charmap_title : 'Izberite poseben znak',
theme_charmap_desc : 'Vstavi poseben znak',
theme_visualaid_desc : 'Prika&#382;i/skrij skrite elemente',
insert_anchor_title : 'Vstavi/uredi povezavo',
insert_anchor_name : 'Ime povezave',
theme_anchor_desc : 'Vstavi/uredi povezavo',
theme_insert_link_titlefield : 'Naslov',
theme_clipboard_msg : 'Kopiraj/Izre&#382;i/Prilepi ni na voljo v brskalnikih Mozilla in Firefox.\nAli &#382;elite ve&#269; informacij glede tega?',
theme_path : 'Pot',
cut_desc : 'Izre&#382;i',
copy_desc : 'Kopiraj',
paste_desc : 'Prilepi',
link_list : 'Seznam povezav',
image_list : 'Seznam slik',
browse : 'Prebrskaj',
image_props_desc : 'Lastnosti slike',
newdocument_desc : 'Nov dokument',
class_name : 'Razred',
newdocument : 'Ali ste prepri&#269;ani, da &#382;elite zbrisati vso vsebino?',
about_title : 'O urejevalniku TinyMCE',
about : 'O urejevalniku',
license : 'Licenca',
plugins : 'Vti&#269;niki',
plugin : 'Vti&#269;nik',
author : 'Avtor',
version : 'Razli&#269;ica',
loaded_plugins : 'Nalo&#382;eni vti&#269;niki',
help : 'Pomo&#269;',
not_set : '-- Ni nastavljeno --',
close : 'Zapri',
toolbar_focus : 'Skok na orodne gumbe - Alt+Q, Skok na urejevalnik - Alt-Z, Skok na pot elementa - Alt-X'
});
