// UK lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Stiller --',
theme_code_desc : 'HTML Kaynaðý Düzenle',
theme_code_title : 'HTML Editörü',
theme_code_wordwrap : 'Sözcük kaydýr',
theme_sub_desc : 'Altsimge',
theme_sup_desc : 'Üstsimge',
theme_hr_desc : 'Yatay çizgi ekle',
theme_removeformat_desc : 'Formatý kaldýr',
theme_custom1_desc : 'Özel açýklamanýz buraya',
insert_image_border : 'Kenar kalýnlýðý',
insert_image_dimensions : 'Boyutlar',
insert_image_vspace : 'Dikey boþluk',
insert_image_hspace : 'Yatay boþluk',
insert_image_align : 'Hizalama',
insert_image_align_default : '-- Atanmamýþ --',
insert_image_align_baseline : 'Taban çizgisi',
insert_image_align_top : 'Üst',
insert_image_align_middle : 'Orta',
insert_image_align_bottom : 'Alt',
insert_image_align_texttop : 'Yazý üstte',
insert_image_align_absmiddle : 'Tam ortada',
insert_image_align_absbottom : 'En altta',
insert_image_align_left : 'Sol',
insert_image_align_right : 'Sað',
theme_font_size : '-- Yazý boyutu --',
theme_fontdefault : '-- Yazý tipi --',
theme_block : '-- Biçim --',
theme_paragraph : 'Paragraf',
theme_div : 'Div etiketi',
theme_address : 'Adres',
theme_pre : 'Önceden düzenlenmiþ',
theme_h1 : 'Baþlýk 1',
theme_h2 : 'Baþlýk 2',
theme_h3 : 'Baþlýk 3',
theme_h4 : 'Baþlýk 4',
theme_h5 : 'Baþlýk 5',
theme_h6 : 'Baþlýk 6',
theme_colorpicker_title : 'Renk seçiniz',
theme_colorpicker_apply : 'Uygula',
theme_forecolor_desc : 'Yazý rengi',
theme_backcolor_desc : 'Arkaplan rengi',
theme_charmap_title : 'Özel karakterler',
theme_charmap_desc : 'Özel karakter ekle',
theme_visualaid_desc : 'Gizli nesneler',
insert_anchor_title : 'Link ekle/düzenle',
insert_anchor_name : 'Link ismi',
theme_anchor_desc : 'Link ekle/düzenle',
theme_insert_link_titlefield : 'Baþlýk',
theme_clipboard_msg : 'Mozilla ve Firefox tarayýcýlarýnda kopyala/kes/yapýþtýr komutlarýný kullanamassýnýz.\n Bu konu hakkýnda daha fazla bilgi edinmek ister misiniz?',
theme_path : 'Etiket yolu',
cut_desc : 'Kes',
copy_desc : 'Kopyala',
paste_desc : 'Yapýþtýr',
link_list : 'Link listesi',
image_list : 'Resim listesi',
browse : 'Gözat',
image_props_desc : 'Resim özellikleri',
newdocument_desc : 'Yeni döküman',
class_name : 'Sýnýf',
newdocument : 'Tüm içeriði silmek istediðinizden emin misiniz?',
about_title : 'TinyMCE Hakkýnda',
about : 'Hakkýnda',
license : 'Lisans',
plugins : 'Pluginler',
plugin : 'Plugin',
author : 'Yazar',
version : 'Versiyon',
loaded_plugins : 'Yüklenen pluginler',
help : 'Yardým',
not_set : '-- Atanmamýþ --',
close : 'Kapat',
toolbar_focus : 'Araç butonlarýna geç - Alt+Q , Editöre geç - Alt-Z, Eleman özelliklerine geç - Alt-X'
});
