// TW lang variables contributed by Jim Kou

tinyMCE.addToLang('',{
bold_desc : '²Ê&Aring;é',
bold_img : "bold.gif",
bullist_desc : '²&Aring;¸¹¶µ¥Ø',
cancel : '¨ú®ø',
cleanup_desc : '²M°£',
help_desc : '»²§U»¡©ú',
image_desc : '¹Ï¤ù',
indent_desc : 'ÁY±Æ',
insert : '·s¼W',
insert_anchor_name : '¼Ðµù¦WºÙ',
insert_anchor_title : '·s¼W¼Ðµù',
insert_image_align : '¹ï»ô',
insert_image_align_absbottom : '±j¨î»ô¤U',
insert_image_align_absmiddle : '±j¨î¸m¤¤',
insert_image_align_baseline : '°ò·Ç½u',
insert_image_align_bottom : '»ô¤U',
insert_image_align_default : '¼Ð·Ç',
insert_image_align_left : '»ô¥ª',
insert_image_align_middle : '¸m¤¤',
insert_image_align_right : '»ô¥k',
insert_image_align_texttop : '¤&aring;¦r¤W¤è',
insert_image_align_top : '»ô¤W',
insert_image_alt : '¹Ï¤ù»¡©ú',
insert_image_border : '¥~®Ø',
insert_image_dimensions : '¤Ø¤o',
insert_image_hspace : '¤ô¥­¶¡»Ø',
insert_image_src : '¹Ï¤ù¨Ó·½',
insert_image_title : '·s¼W¹Ï¤ù',
insert_image_vspace : '««ª½¶¡»Ø',
insert_link_target : '¥Ø¼Ð',
insert_link_target_blank : '&Aring;ã¥Ü©ó·sµøµ¡¤¤',
insert_link_target_same : '&Aring;ã¥Ü©ó¦P¤@µøµ¡¤¤',
insert_link_title : '·s¼W¶W³sµ²',
insert_link_url : '¶W³sµ²',
italic_desc : '±×&Aring;é',
italic_img : "italic.gif",
justifycenter_desc : '»ô¤¤',
justifyfull_desc : '¶ñº¡',
justifyleft_desc : '»ô¥ª',
justifyright_desc : '»ô¥k',
link_desc : '«Ø¥ß³sµ²',
numlist_desc : '¼Æ¦r¶µ¥Ø',
outdent_desc : '¥Y±Æ',
redo_desc : '­«°µ',
striketrough_desc : '§R°£½u',
theme_address : '¦a§}',
theme_anchor_desc : '¼Ðµù',
theme_charmap_desc : '¯S®í¦r¤¸',
theme_charmap_title : '¯S®í¦r¤¸²M³æ',
theme_code_desc : '&Aring;ã¥Ü HTML ­ì©l½X',
theme_code_wordwrap : 'Word wrap',
theme_code_title : 'HTML ­ì©l½X',
theme_colorpicker_apply : '&Aring;Ü§ó',
theme_colorpicker_title : 'ÃC¦â',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_forecolor_desc : '¦r«¬ÃC¦â',
theme_backcolor_desc : 'Select background color',
theme_h1 : '¼ÐÃD1',
theme_h2 : '¼ÐÃD2',
theme_h3 : '¼ÐÃD3',
theme_h4 : '¼ÐÃD4',
theme_h5 : '¼ÐÃD5',
theme_h6 : '¼ÐÃD6',
theme_hr_desc : '·s¼W¾î½u',
theme_paragraph : '¬q¸¨',
theme_pre : '¤º©w®æ¦¡',
theme_removeformat_desc : '²M°£®æ¦¡³]©w',
theme_style_select : '¼Ë¦¡',
theme_sub_desc : '¤U¼Ð',
theme_sup_desc : '¤W¼Ð',
theme_visualaid_desc : '&Aring;ã¥Ü/ÁôÂÃ«D¥i¨£ªº¤¸¯À',
underline_desc : '©³½u',
undo_desc : '´_­ì',
unlink_desc : '¨ú®ø³sµ²',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
newdocument : 'Are you sure you want clear all contents?'
});
