// Simplified Chinese lang variables contributed by tom_cat (thomaswangyang@gmail.com)

tinyMCE.addToLang('',{
theme_style_select : '-- 格式 --',
theme_code_desc : '编辑HTML源代码',
theme_code_title : 'HTML源代码编辑器',
theme_code_wordwrap : '自动换行',
theme_sub_desc : '下标',
theme_sup_desc : '上标',
theme_hr_desc : '插入水平线',
theme_removeformat_desc : '移除格式',
theme_custom1_desc : '这里填写用户自定义描述',
insert_image_border : '边框',
insert_image_dimensions : '维数',
insert_image_vspace : '垂直间距',
insert_image_hspace : '水平间距',
insert_image_align : '对齐方式',
insert_image_align_default : '-- 默认 --',
insert_image_align_baseline : '基线',
insert_image_align_top : '顶端',
insert_image_align_middle : '居中',
insert_image_align_bottom : '底部',
insert_image_align_texttop : '文字上方',
insert_image_align_absmiddle : '绝对居中',
insert_image_align_absbottom : '绝对底部',
insert_image_align_left : '左对齐',
insert_image_align_right : '右对齐',
theme_font_size : '-- 字号 --',
theme_fontdefault : '-- 字体 --',
theme_block : '-- 格式 --',
theme_paragraph : '段落',
theme_div : '层',
theme_address : '地址',
theme_pre : '预格式化',
theme_h1 : '标题 1',
theme_h2 : '标题 2',
theme_h3 : '标题 3',
theme_h4 : '标题 4',
theme_h5 : '标题 5',
theme_h6 : '标题 6',
theme_colorpicker_title : '选择颜色',
theme_colorpicker_apply : '应用',
theme_forecolor_desc : '选择文字颜色',
theme_backcolor_desc : '选择背景颜色',
theme_charmap_title : '选择特殊符号',
theme_charmap_desc : '插入特殊符号',
theme_visualaid_desc : '开关不可见元素',
insert_anchor_title : '插入/编辑 锚点',
insert_anchor_name : '锚点名称',
theme_anchor_desc : '插入/编辑 锚点',
theme_insert_link_titlefield : '标题',
theme_clipboard_msg : '剪切/复制/粘贴功能在 Mozilla 和 Firefox 浏览器中不支持。\n您希望获得更多的信息吗？',
theme_path : '路径',
cut_desc : '剪切',
copy_desc : '复制',
paste_desc : '粘贴',
link_list : '链接列表',
image_list : '图像列表',
browse : '浏览',
image_props_desc : '图像属性',
newdocument_desc : '新建间档',
class_name : '类',
newdocument : '您确认要清除所有内容吗？',
about_title : '关于 TinyMCE',
about : '关于',
license : '授权书',
plugins : '所有插件',
plugin : '插件',
author : '作者',
version : '版本',
loaded_plugins : '读取插件',
help : '帮助',
not_set : '-- 空设定 --',
close : '关闭',
toolbar_focus : '跳到工具按钮 - Alt+Q, 跳到编辑器 - Alt-Z, 跳到元素路径 - Alt-X'
});
