// UK lang variables

tinyMCE.addToLang('table',{
general_tab : 'Cyffredinol',
advanced_tab : 'Uwch',
general_props : 'Priodoleddau cyffredinol',
advanced_props : 'Priodoleddau uwch',
desc : 'Mewnosod tabl newydd',
row_before_desc : 'Mewnosod rhes cyn',
row_after_desc : 'Mewnosod rhes ar &ocirc;l',
delete_row_desc : 'Dileu rhes',
col_before_desc : 'Mewnosod colofn cyn',
col_after_desc : 'Mewnosod colofn ar &ocirc;l',
delete_col_desc : 'Dileu colofn',
rowtype : 'Rhan tabl y rhes',
title : 'Mewnosod/golygu tabl',
width : 'Lled',
height : 'Uchder',
cols : 'Colofnau',
rows : 'Rhesi',
cellspacing : 'Bylchu celloedd',
cellpadding : 'Padio celliodd',
border : 'Ffin',
align : 'Unioni',
align_default : 'Arferol',
align_left : 'Chwith',
align_right : 'Dde',
align_middle : 'Canol',
row_title : 'Priodoleddau rhes tabl',
cell_title : 'Priodoleddau cell tabl',
cell_type : 'Math cell',
row_desc : 'Priodoleddau rhes tabl',
cell_desc : 'Priodoleddau cell tabl',
valign : 'Unioni fertigol',
align_top : 'Brig',
align_bottom : 'Gwaelod',
props_desc : 'Priodoleddau tabl',
bordercolor : 'Lliw ffin',
bgcolor : 'Lliw cefndir',
merge_cells_title : 'Uno celloedd tabl',
split_cells_desc : 'Rhannu celloedd tabl',
merge_cells_desc : 'Uno celloedd tabl',
cut_row_desc : 'Torri rhes tabl',
copy_row_desc : 'Cop&iuml;o rhes tabl',
paste_row_before_desc : 'Gludo rhes tabl cyn',
paste_row_after_desc : 'Gludo rhes tabl ar &ocirc;l',
id : 'Id',
style: 'Arddull',
langdir : 'Cyfeiriad iaith',
langcode : 'C&ocirc;d iaith',
mime : 'Math MIME y targed',
ltr : 'Chwith i\'r dde',
rtl : 'Dde i\'r chwith',
bgimage : 'Delwedd cefndir',
summary : 'Crynodeb',
td : "Data",
th : "Pennawd",
cell_cell : 'Diweddaru\'r gell bresennoll',
cell_row : 'Diweddaru holl gelloedd y rhes',
cell_all : 'Diweddaru holl gelloedd y tabl',
row_row : 'Diweddaru\'r rhes presennol',
row_odd : 'Diweddaru rhesi odrif y tabl',
row_even : 'Diweddaru rhesi eilrif y tabl',
row_all : 'Diweddaru holl rhesi\'r tabl',
thead : 'Pennawd Tabl',
tbody : 'Corff Tabl',
tfoot : 'Troedyn Tabl',
del : 'Dileu tabl',
scope : 'Maes',
row : 'Rhes',
col : 'Colofn',
rowgroup : 'Gr&#373;p Rhesi',
colgroup : 'Gr&#373;p Colofnau',
missing_scope: 'Wyt ti\'n sicr eisiau parhau heb gynnwys maes ar gyfer y cell pennawd tabl hwn? Heb un, gallai fod yn anodd i rai defnyddwyr gydag anableddau ddeall cynnwys neu ddata y tabl.',
cellprops_delta_width : 50
});
