/**
 * ES lang variables
 * 
 * Authors : Alvaro Velasco,
 *           Adolfo Sanz De Diego (asanzdiego) <asanzdiego@yahoo.es>,
 *           Carlos C Soto (eclipxe) <csoto@sia-solutions.com>
 * Last Updated : October 17, 2005
 * TinyMCE Version : 2.0RC3
 */

tinyMCE.addToLang('table',{
general_tab : 'General',
advanced_tab : 'Avanzado',
general_props : 'Propiedades generales',
advanced_props : 'Propiedades avanzadas',
desc : 'Insertar/Modificar tabla',
row_before_desc : 'Insertar una fila antes',
row_after_desc : 'Insert una fila después',
delete_row_desc : 'Eliminar fila',
col_before_desc : 'Insertar una columna antes',
col_after_desc : 'Insertar una columna después',
delete_col_desc : 'Eliminar columna',
rowtype : 'File en parte de tabla',
title : 'Insertar/Modificar tabla',
width : 'Ancho',
height : 'ALto',
cols : 'Columnas',
rows : 'Filas',
cellspacing : 'Espacio entre celdas',
cellpadding : 'Borde interior de las celdas',
border : 'Borde',
align : 'Alineación horizontal',
align_default : 'Defecto',
align_left : 'Izquierda',
align_right : 'Derecha',
align_middle : 'Centrado',
row_title : 'Propiedades de la fila',
cell_title : 'Propiedades de la celda',
cell_type : 'Tipo de celda',
row_desc : 'Propiedades de la fila',
cell_desc : 'Propiedades de la celda',
valign : 'Alineación vertical',
align_top : 'Arriba',
align_bottom : 'Abajo',
props_desc : 'Propiedades de la tabla',
bordercolor : 'Color del borde',
bgcolor : 'Color del fondo',
merge_cells_title : 'Combinar celdas',
split_cells_desc : 'Dividir celdas',
merge_cells_desc : 'Combinar celdas',
cut_row_desc : 'Cortar fila',
copy_row_desc : 'Copiar fila',
paste_row_before_desc : 'Pegar fila antes',
paste_row_after_desc : 'Pegar fila después',
id : 'Id',
style: 'Estilo',
langdir : 'Dirección del texto',
langcode : 'Código del idioma',
mime : 'Tipo MIME del target',
ltr : 'De izquierda a derecha',
rtl : 'De derecha a izquierda',
bgimage : 'Imagen de fondo',
summary : 'Resumen',
td : "Datos",
th : "Cabecera",
cell_cell : 'Actualizar la celda actual',
cell_row : 'Actualizar todas las celdas de la fila',
cell_all : 'Actualizar todas las celdas de la tabla',
row_row : 'Actualizar la fila actual',
row_odd : 'Actualizar las filas impares de la tabla',
row_even : 'Actualizar las filas pares de la tabla',
row_all : 'Actualizar todas las filas de la tabla',
thead : 'Cabecera de la tabla',
tbody : 'Cuerpo de la tabla',
tfoot : 'Pie de la tabla',
del : 'Eliminar tabla',
scope : 'Alcance',
row : 'Fila',
col : 'Columna',
rowgroup : 'Grupo de filas',
colgroup : 'Grupo de columnas',
missing_scope: '¿Estás seguro que quieres continuar sin especificar el alcance para esta celda de tipo cabecera? Sin ello, puede dificultar a algunos usuarios con discapacidades el poder entender el contenido o los datos mostrados en la tabla.',
cellprops_delta_width : 55
});
