// FI lang variables by Urho Konttori from Absolutions
// Updated by Tuomo Aura, Ateco.fi

tinyMCE.addToLang('table',{
general_tab : 'Yleiset',
advanced_tab : 'Edistyneemm&auml;t',
general_props : 'Yleisasetukset',
advanced_props : 'Edistyneemm&auml;t asetukset',
desc : 'Lis&auml;&auml; uusi taulukko',
row_before_desc : 'Lis&auml;&auml; rivi edelle',
row_after_desc : 'Lis&auml;&auml; rivi j&auml;lkeen',
delete_row_desc : 'Poista rivi',
col_before_desc : 'Lis&auml;&auml; sarake edelle',
col_after_desc : 'Lis&auml;&auml; sarake j&auml;lkeen',
delete_col_desc : 'Poista sarake',
rowtype : 'Row in table part',
title : 'Lis&auml;&auml;/Muokkaa taulukkoa',
width : 'Leveys',
height : 'Korkeus',
cols : 'Saraketta',
rows : 'Rivi&auml;',
cellspacing : 'Cellspacing',
cellpadding : 'Cellpadding',
border : 'Reuna',
align : 'Asettelu',
align_default : 'Oletus',
align_left : 'Vasen',
align_right : 'Oikea',
align_middle : 'Keskelle',
row_title : 'Rivin ominaisuudet',
cell_title : 'Sarakkeen ominaisuudet',
cell_type : 'Solun tyyppi',
row_desc : 'Rivin ominaisuudet',
cell_desc : 'Solun ominaisuudet',
valign : 'Pystysuora asettelu',
align_top : 'Yl&auml;reuna',
align_bottom : 'Alareuna',
props_desc : 'Taulukon ominaisuudet',
bordercolor : 'Reunan v&auml;ri',
bgcolor : 'Taustav&auml;ri',
merge_cells_title : 'Yhdist&auml; taulukon solut',
split_cells_desc : 'Erota taulukon solut',
merge_cells_desc : 'Yhdist&auml; taulukon solut',
cut_row_desc : 'Leikkaa taulukon rivi',
copy_row_desc : 'Kopioi taulukon rivi',
paste_row_before_desc : 'Liit&auml; taulukon rivi edelle',
paste_row_after_desc : 'Liit&auml; taulukon rivi j&auml;lkeen',
id : 'Id',
style: 'Tyyli',
langdir : 'Kielen suunta',
langcode : 'Kielikoodi',
mime : 'Kohteen MIME-tyyppi',
ltr : 'Vasemmalta oikealle',
rtl : 'Oikealta vasemmalle',
bgimage : 'Taustakuva',
summary : 'Yhteenveto',
td : "Data",
th : "Otsikko",
cell_cell : 'P&auml;ivit&auml; kyseinen solu',
cell_row : 'P&auml;ivit&auml; kaikki solut riviss&auml;',
cell_all : 'P&auml;ivit&auml; kaikki solut taulukossa',
row_row : 'P&auml;ivit&auml; kyseinen rivi',
row_odd : 'P&auml;ivit&auml; parittomat rivit',
row_even : 'P&auml;ivit&auml; parilliset rivit',
row_all : 'P&auml;ivit&auml; kaikki rivit',
thead : 'Table Head',
tbody : 'Table Body',
tfoot : 'Table Foot',
del : 'Poista taulukko',
scope : 'Scope',
row : 'Rivi',
col : 'Sarake',
rowgroup : 'Riviryhm&auml;',
colgroup : 'Sarakeryhm&auml;',
missing_scope: 'Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.',
cellprops_delta_width : 50
});
