// HE lang variables

tinyMCE.addToLang('table',{
general_tab : 'כללי',
advanced_tab : 'מתקדם',
general_props : 'מאפיינים כלליים',
advanced_props : 'מאפיינים מתקדמים',
desc : 'מכניס טבלה חדשה',
row_before_desc : 'הכנס שורה לפני',
row_after_desc : 'הכנס שורה אחרי',
delete_row_desc : 'מחק שורה',
col_before_desc : 'הכנס טור לפני',
col_after_desc : 'הכנס טור אחרי',
delete_col_desc : 'מחק טור',
rowtype : 'שורה בחלק של הטבלה',
title : 'הכנס/שנה טבלה',
width : 'רוחב',
height : 'גובה',
cols : 'טורים',
rows : 'שורות',
cellspacing : 'ריווח בין תאים',
cellpadding : 'ריפוד תאים',
border : 'גבול',
align : 'ישור',
align_default : 'ברירת מחדל',
align_left : 'שמאל',
align_right : 'ימין',
align_middle : 'מרכז',
row_title : 'מאפייני שורה בטבלה',
cell_title : 'מאפייני תא בטבלה',
cell_type : 'סוג תא',
row_desc : 'מאפייני שורה בטבלה',
cell_desc : 'מאפייני תא בטבלה',
valign : 'ישור אנכי',
align_top : 'למעלה',
align_bottom : 'למטה',
props_desc : 'מאפייני טבלה',
bordercolor : 'צבע גבול',
bgcolor : 'צבע רקע',
merge_cells_title : 'מזג תאים בטבלה',
split_cells_desc : 'פצל תאים בטבלה',
merge_cells_desc : 'מזג תאים בטבלה',
cut_row_desc : 'גזור שורה מהטבלה',
copy_row_desc : 'העתק שורה מהטבלה',
paste_row_before_desc : 'הדבק שורה לפני',
paste_row_after_desc : 'הדבק שורה אחרי',
id : 'Id',
style: 'סגנון',
langdir : 'כיוון שפה',
langcode : 'קוד שפה',
mime : 'סוג MIME של היעד',
ltr : 'שמאל לימין',
rtl : 'ימין לשמאל',
bgimage : 'תמונת רקע',
summary : 'סיכום',
td : "מידע",
th : "כותרת",
cell_cell : 'עדכן תא נוכחי',
cell_row : 'עדכן את כל התאים בשורה',
cell_all : 'עדכן את כל התאים בטבלה',
row_row : 'עדכן שורה נוכחית',
row_odd : 'עדכן שורות אי-זוגיות בטבלה',
row_even : 'עדכן שורות זוגיות בטבלה',
row_all : 'עדכן את כל השורות בטבלה',
thead : 'כותרת הטבלה',
tbody : 'גוף הטבלה',
tfoot : 'סיכום הטבלה',
del : 'מחק טבלה',
scope : 'תחום',
row : 'שורה',
col : 'טור',
rowgroup : 'קבוצת שורות',
colgroup : 'קבוצת טורים',
missing_scope: 'האם אתה בטוח שברצונך להמשיך מבלי לציין את תחום הכותרת של הטבלה? בלי כותרת מוגדרת, יתכן כי משתמשים בעלי מוגבלויות יתקשו להבין את התוכן או המידע המוצגים בטבלה.'
});
