// HU lang variables

tinyMCE.addToLang('table',{
general_tab : 'Általános',
advanced_tab : 'Haladó',
general_props : 'Általános beállítások',
advanced_props : 'Haladó beállítások',
desc : 'Új táblázat beszúrása',
row_before_desc : 'Sor beszúrása elé',
row_after_desc : 'Sor beszúrása mögé',
delete_row_desc : 'Sor törlése',
col_before_desc : 'Oszlop beszúrása elé',
col_after_desc : 'Oszlop beszúrása mögé',
delete_col_desc : 'Oszlop törlése',
rowtype : 'Sor a táblázatrészben',
title : 'Táblázat beszúrása/módosítása',
width : 'Hosszúság',
height : 'Szélesség',
cols : 'Oszlopok',
rows : 'Sorok',
cellspacing : 'Cellaköz',
cellpadding : 'Cellakitöltés',
border : 'Keret',
align : 'Elhelyezkedés',
align_default : 'alapértelmezett',
align_left : 'Bal',
align_right : 'Jobb',
align_middle : 'Közép',
row_title : 'Táblázat sor tulajdonságai',
cell_title : 'Táblázat cella tulajdonságai',
cell_type : 'Cella típus',
row_desc : 'Táblázat sor tulajdonságai',
cell_desc : 'Táblázat cella tulajdonságai',
valign : 'Függõleges elhelyezkedés',
align_top : 'Felül',
align_bottom : 'Alul',
props_desc : 'Táblázat tulajdonságai',
bordercolor : 'Keret szín',
bgcolor : 'Háttér szín',
merge_cells_title : 'Tábla celláinak egyesítése',
split_cells_desc : 'Tábla celláinak felosztása',
merge_cells_desc : 'Tábla celláinak egyesítése',
cut_row_desc : 'Táblázat sor kivágása',
copy_row_desc : 'Táblázat sor másolása',
paste_row_before_desc : 'Táblázat sor beillesztése elé',
paste_row_after_desc : 'Táblázat sor beillesztése mögé',
id : 'Azonodító',
style: 'Stílus',
langdir : 'Szövegpozíció',
langcode : 'Szöveg kód',
mime : 'Cél MIME típus',
ltr : 'Balról jobbra',
rtl : 'Jobbról balra',
bgimage : 'Háttérkép',
summary : 'Összefoglaló',
td : "Adat",
th : "Fejléc",
cell_cell : 'Aktuális cella frissítése',
cell_row : 'Minden cella frissítése a sorban',
cell_all : 'Minden cella frissítése a táblában',
row_row : 'Aktuális sor frissítése',
row_odd : 'Páratlan sorok frissítése a táblában',
row_even : 'páros sorok frissítése a táblában',
row_all : 'Minden sor frissítése a táblában',
thead : 'Táblázat fejléc',
tbody : 'Táblázat test',
tfoot : 'Tálázat lábléc',
del : 'Tábla törlése',
scope : 'Scope',
row : 'Row',
col : 'Col',
rowgroup : 'Row Group',
colgroup : 'Col Group',
missing_scope: 'Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.'
});
