// Iceland lang variables by Johannes Birgir Jensson

tinyMCE.addToLang('table',{
general_tab : 'Almennt',
advanced_tab : 'S&eacute;rt&aelig;kt',
general_props : 'Almennar stillingar',
advanced_props : 'S&eacute;rt&aelig;kar stillingar',
desc : 'Setja inn n&yacute;ja t&ouml;flu',
row_before_desc : 'B&aelig;ta r&ouml;&eth; vi&eth; fyrir framan',
row_after_desc : 'B&aelig;ta r&ouml;&eth; vi&eth; fyrir aftan',
delete_row_desc : 'Ey&eth;a r&ouml;&eth;',
col_before_desc : 'B&aelig;ta d&aacute;lk vi&eth; fyrir framan',
col_after_desc : 'B&aelig;ta d&aacute;lk vi&eth; fyrir aftan',
delete_col_desc : 'Ey&eth;a d&aacute;lki',
rowtype : 'R&ouml;&eth; &iacute; t&ouml;fluhluta',
title : 'B&aelig;ta vi&eth;/breyta t&ouml;flu',
width : 'Breidd',
height : 'H&aelig;&eth;',
cols : 'D&aacute;lkar',
rows : 'Ra&eth;ir',
cellspacing : 'Reitabil',
cellpadding : 'Reitab&oacute;lstrun',
border : 'Rammi',
align : 'Textastilling',
align_default : 'Sj&aacute;lfgild',
align_left : 'Vinstri',
align_right : 'H&aelig;gri',
align_middle : 'Mi&eth;ja',
row_title : 'Stillingar t&ouml;flura&eth;ar',
cell_title : 'Stillingar t&ouml;flud&aacute;lks',
cell_type : 'Reitartegund',
row_desc : 'Stillingar t&ouml;flura&eth;ar',
cell_desc : 'Stillingar t&ouml;flureits',
valign : 'L&oacute;&eth;r&eacute;tt stilling',
align_top : 'Efst',
align_bottom : 'Ne&eth;st',
props_desc : 'Stillingar t&ouml;flu',
bordercolor : 'Rammalitur',
bgcolor : 'Bakgrunnslitur',
merge_cells_title : 'Sameina t&ouml;flureiti',
split_cells_desc : 'Tv&iacute;stra t&ouml;flureitum',
merge_cells_desc : 'Sameina t&ouml;flureiti',
cut_row_desc : 'Klippa t&ouml;flur&ouml;&eth;',
copy_row_desc : 'Afrita t&ouml;flur&ouml;&eth;',
paste_row_before_desc : 'Skeyta t&ouml;flur&ouml;&eth; fyrir ofan',
paste_row_after_desc : 'Skeyta t&ouml;flur&ouml;&eth; fyrir ne&eth;an',
id : 'Id',
style: 'St&iacute;ll',
langdir : 'Rith&aacute;ttur tungum&aacute;ls',
langcode : 'Tungum&aacute;lskenni',
mime : 'MIME-tegund tengils',
ltr : 'Vinstri til h&aelig;gri',
rtl : 'H&aelig;gri til vinstri',
bgimage : 'Bakgrunnsmynd',
summary : 'Samantekt',
td : "G&ouml;gn",
th : "Haus",
cell_cell : 'Uppf&aelig;ra n&uacute;verandi reit',
cell_row : 'Uppf&aelig;ra alla reiti í r&ouml;&eth;inni',
cell_all : 'Uppf&aelig;ra alla reiti t&ouml;flunnar',
row_row : 'Uppf&aelig;ra n&uacute;verandi r&ouml;&eth;',
row_odd : 'Uppf&aelig;ra oddat&ouml;lura&eth;ir',
row_even : 'Uppf&aelig;ra jafnt&ouml;lura&eth;ir',
row_all : 'Uppf&aelig;ra allar ra&eth;ir',
thead : 'Haus t&ouml;flu',
tbody : 'Meginm&aacute;l t&ouml;flu',
tfoot : 'F&oacute;tur t&ouml;flu',
del : 'Ey&eth;a t&ouml;flu',
scope : 'Gildissvi&eth;',
row : 'R&ouml;&eth;',
col : 'D&aacute;lkur',
rowgroup : 'Ra&eth;ah&oacute;pur',
colgroup : 'D&aacute;lkah&oacute;pur',
missing_scope: 'Viltu halda áfram án þess að tilgreina gildissvið fyrir haus töflu? Án þess gæti það valdið sumum notendum, til dæmis sjónskertum, vandkvæðum við að skilja innihald töflunnar.',
cellprops_delta_width : 55
});
