// Variabili di lingua IT - fabrix.xm@lombardiacom.it

tinyMCE.addToLang('',{
table_desc : 'Inserisci una nuova tabella',
table_insert_row_before_desc : 'Inserisci una riga prima',
table_insert_row_after_desc : 'Inserisci una riga dopo',
table_delete_row_desc : 'Cancella riga',
table_insert_col_before_desc : 'Inserisci colonna prima',
table_insert_col_after_desc : 'Inserisci colonna dopo',
table_delete_col_desc : 'Rimuovi colonna',
insert_table_title : 'Inserisci/modifica tabella',
insert_table_width : 'Larghezza',
insert_table_height : 'Altezza',
insert_table_cols : 'Colonne',
insert_table_rows : 'Righe',
insert_table_cellspacing : 'Cellspacing',
insert_table_cellpadding : 'Cellpadding',
insert_table_border : 'Bordo',
insert_table_align : 'Allineamento',
insert_table_align_default : 'Default',
insert_table_align_left : 'Sinistra',
insert_table_align_right : 'Destra',
insert_table_align_middle : 'Centro',
insert_table_class : 'Classe',
table_row_title : 'Proprietà della riga',
table_cell_title : 'Proprietà della cella',
table_row_desc : 'Proprietà della riga',
table_cell_desc : 'Proprietà della cella',
insert_table_valign : 'Allineamento verticale',
insert_table_align_top : 'In alto',
insert_table_align_bottom : 'In basso',
table_props_desc : 'Proprietà della tabella',
table_bordercolor : 'Colore bordo',
table_bgcolor : 'Colore sfondo',
table_merge_cells_title : 'Unisci celle',
table_split_cells_desc : 'Dividi celle',
table_merge_cells_desc : 'Unisci le celle',
table_cut_row_desc : 'Taglia riga',
table_copy_row_desc : 'Copia riga',
table_paste_row_before_desc : 'Incolla riga prima',
table_paste_row_after_desc : 'Incolla riga dopo',
table_insert_desc : 'Inserisci una nuova tabella'
});
