// JP lang variables

tinyMCE.addToLang('',{
table_desc : 'テーブル',
table_insert_row_before_desc : '行挿入(前)',
table_insert_row_after_desc : '行挿入(後)',
table_delete_row_desc : '行削除',
table_insert_col_before_desc : '列挿入(前)',
table_insert_col_after_desc : '列挿入(後)',
table_delete_col_desc : '列削除',
insert_table_title : 'テーブルの挿入/編集',
insert_table_cols : '列数',
insert_table_rows : '行数',
insert_table_cellspacing : 'セル余白',
insert_table_cellpadding : 'セル詰め',
insert_table_align : '位置調整',
insert_table_align_default : '暗黙',
insert_table_align_left : '左詰め',
insert_table_align_right : '右詰め',
insert_table_align_middle : '中央寄せ',
insert_table_width : '幅',
insert_table_height : '高さ',
insert_table_border : '境界線',
insert_table_class : 'クラス',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
