// KO lang variables

tinyMCE.addToLang('',{
table_desc : 'Ç¥ ³&Ouml;±â',
table_insert_row_before_desc : '¾Õ¿¡ Çà ³&Ouml;±â',
table_insert_row_after_desc : 'µÚ¿¡ Çà ³&Ouml;±â',
table_delete_row_desc : 'Çà Á&ouml;¿ì±â',
table_insert_col_before_desc : '¾Õ¿¡ ¿­ ³&Ouml;±â',
table_insert_col_after_desc : 'µÚ¿¡ ¿­ ³&Ouml;±â',
table_delete_col_desc : '¿­ Á&ouml;¿ì±â',
insert_table_title : 'Ç¥ ³&Ouml;±â/°í&Auml;¡±â',
insert_table_width : '³Êºñ',
insert_table_height : '³ôÀÌ',
insert_table_cols : 'Çà',
insert_table_rows : '¿­',
insert_table_cellspacing : '¼¿ °£°Ý',
insert_table_cellpadding : '¼¿ ¿©¹é',
insert_table_border : '&Aring;×µÎ¸®',
insert_table_align : 'Á¤·&Auml;',
insert_table_align_default : '±âº»°ª',
insert_table_align_left : '¿ÞÂÊ',
insert_table_align_right : '¿À¸¥ÂÊ',
insert_table_align_middle : '°¡¿îµ¥',
insert_table_class : '&Aring;¬·¡½º',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
