// NL lang variables

tinyMCE.addToLang('table',{
general_tab : 'Algemeen',
advanced_tab : 'Geavanceerd',
general_props : 'Algemene eigenschappen',
advanced_props : 'Geavanceerde eigenschappen',
desc : 'Nieuwe tabel invoegen',
row_before_desc : 'Rij boven invoegen',
row_after_desc : 'Rij onder invoegen',
delete_row_desc : 'Rij verwijderen',
col_before_desc : 'Kolom links invoegen',
col_after_desc : 'Kolom rechts invoegen',
delete_col_desc : 'Kolom verwijderen',
rowtype : 'Row in table part',
title : 'Tabel invoegen/bewerken',
width : 'Breedte',
height : 'Hoogte',
cols : 'Kolommen',
rows : 'Rijen',
cellspacing : 'Ruimte om cel',
cellpadding : 'Ruimte in cel',
border : 'Rand',
align : 'Uitlijning',
align_default : 'Standaard',
align_left : 'Links',
align_right : 'Rechts',
align_middle : 'Centreren',
row_title : 'Tabelrij-eigenschappen',
cell_title : 'Tabelcel-eigenschappen',
cell_type : 'Celtype',
row_desc : 'Tabelrij-eigenschappen',
cell_desc : 'Tabelcel-eigenschappen',
valign : 'Verticale uitlijning',
align_top : 'Boven',
align_bottom : 'Onder',
props_desc : 'Tabeleigenschappen',
bordercolor : 'Randkleur',
bgcolor : 'Achtergrondkleur',
merge_cells_title : 'Tabelcellen samenvoegen',
split_cells_desc : 'Tabelcellen splitsen',
merge_cells_desc : 'Tabelcellen samenvoegen',
cut_row_desc : 'Tabelrij knippen',
copy_row_desc : 'Tebelrij kopi&euml;ren',
paste_row_before_desc : 'Tabelrij boven plakken',
paste_row_after_desc : 'tabelrij onder plakken',
id : 'Id',
style: 'Stijl',
langdir : 'Taalrichting',
langcode : 'Taalcode',
mime : 'MIME type',
ltr : 'Links naar rechts',
rtl : 'Rechts naar links',
bgimage : 'Achtergrondafbeelding',
summary : 'Samenvatting',
td : "Data",
th : "Kop",
cell_cell : 'Huidige cel bijwerken',
cell_row : 'Alle cellen in rij bijwerken',
cell_all : 'Alle cellen in tabel bijwerken',
row_row : 'Huidige rij bijwerken',
row_odd : 'Oneven rijen in tabel bijwerken',
row_even : 'Even rijen in tabel bijwerken',
row_all : 'Alle rijen in tabel bijwerken',
thead : 'Tabel-kop',
tbody : 'Tabel-body',
tfoot : 'Tabel-voet',
del : 'Tabel verwijderen',
scope : 'Bereik',
row : 'Rij',
col : 'Kolom',
rowgroup : 'Rijgroep',
colgroup : 'Kolomgroep',
missing_scope: 'Zonder een bereik van een tabelkop, is het moeilijk voor mensen met een visuele handicap deze pagina te begrijpen. Weet u zeker dat u zonder bereik verder wilt gaan?'
});
