/**
 * pt_br lang variables
 * Brazilian Portuguese
 *
 * Authors :
 *           Marcio Barbosa (mpg) <mpg@mpg.com.br>
 * Last Updated : November 26, 2005
 * TinyMCE Version : 2.0RC4
 */
tinyMCE.addToLang('table',{
general_tab : 'Geral',
advanced_tab : 'Avançado',
general_props : 'Propriedades Gerais',
advanced_props : 'Propriedades Avançadas',
desc : 'Inserir uma nova tabela',
row_before_desc : 'Inserir uma linha antes',
row_after_desc : 'Inserir uma linha depois',
delete_row_desc : 'Apagar linha',
col_before_desc : 'Inserir uma coluna antes',
col_after_desc : 'Inserir uma coluna depois',
delete_col_desc : 'Remover coluna',
rowtype : 'Linhas na tabela parcial',
title : 'Inserir/Modificar Tabela',
width : 'Largura',
height : 'Altura',
cols : 'Colunas',
rows : 'Linhas',
cellspacing : 'Espaçamento das células',
cellpadding : 'Margem interna',
border : 'Borda',
align : 'Alinhamento',
align_default : 'Padrão',
align_left : 'Esquerda',
align_right : 'Direita',
align_middle : 'Centrado',
row_title : 'Propriedades das linha',
cell_title : 'Propriedades da célula',
cell_type : 'Tipo de célula',
row_desc : 'Propriedades das linhas',
cell_desc : 'Propriedades da célula',
valign : 'Alinhamento vertical',
align_top : 'Superior',
align_bottom : 'Inferior',
props_desc : 'Propriedades da tabela',
bordercolor : 'Côr da borda',
bgcolor : 'Côr do fundo',
merge_cells_title : 'Juntar células',
merge_cells_desc : 'Juntar células da tabela',
split_cells_title : 'Separar células',
split_cells_desc : 'Separar células',
cut_row_desc : 'Apagar linha',
copy_row_desc : 'Copiar linha',
paste_row_before_desc : 'Colar linha antes',
paste_row_after_desc : 'Colar linha depois',
id : 'Id',
style: 'Estilo',
langdir : 'Direção do texto',
langcode : 'Código do idioma',
mime : 'Tipo de MIME do objeto',
ltr : 'Esquerda para direita',
rtl : 'Direita para esquerda',
bgimage : 'Imagem de fundo',
summary : 'Sumário',
td : "Dados",
th : "Cabeçalho",
cell_cell : 'Atulizar célula atual',
cell_row : 'Atualizar todas as cédulas na linha',
cell_all : 'Atualizar todas as cédulas da tabela',
row_row : 'Atualizar linha atual',
row_odd : 'Atualizar linhas ímpares na tabela',
row_even : 'Atualizar linhas pares na tabela',
row_all : 'Atualizar todas as linhas na tabela',
thead : 'Cabeçalho da tabela',
tbody : 'Corpo da tabela',
tfoot : 'Rodapé da tabela',
del : 'Apagar tabela',
dir : 'Direção',
scope : 'Escopo',
row : 'Linha',
col : 'Coluna',
rowgroup : 'Grupo de linhas',
colgroup : 'Grupo de colunas',
missing_scope: 'Tem certeza que deseja continuar sem especificar um escopo para este célula de cabeçalho. Sem isso talvez seja difícil para alguns usuários especiais entender ou conteúdo ou visualizar a tabela.',
cellprops_delta_width : 55
});
