// RU cp1251 lang variables

tinyMCE.addToLang('table',{
general_tab : 'Основные',
advanced_tab : 'Расширенные',
general_props : 'Основные свойства',
advanced_props : 'Расширенные свойства',
desc : 'Вставить новую таблицу',
row_before_desc : 'Вставить строку перед',
row_after_desc : 'Вставить строку после',
delete_row_desc : 'Удалить строку',
col_before_desc : 'Вставить колонку перед',
col_after_desc : 'Вставить колонку после',
delete_col_desc : 'Удалить колонку',
rowtype : 'Строка в части таблицы',
title : 'Вставить/Изменить таблицу',
width : 'Ширина',
height : 'Высота',
cols : 'Колонки',
rows : 'Строки',
cellspacing : 'Расстояние между ячейками',
cellpadding : 'Отступ в ячейках',
border : 'Граница',
align : 'Выравнивание',
align_default : 'По-умолчанию',
align_left : 'Всево',
align_right : 'Вправо',
align_middle : 'По центру',
row_title : 'Свойства строки таблицы',
cell_title : 'Свойства ячейки таблицы',
cell_type : 'Тип ячейки',
row_desc : 'Свойства строки таблицы',
cell_desc : 'Свойства ячейки таблицы',
valign : 'Вертикальное выравнивание',
align_top : 'По верху',
align_bottom : 'По низу',
props_desc : 'Свойства таблицы',
bordercolor : 'Цвет рамки',
bgcolor : 'Цвет фона',
merge_cells_title : 'Объединить ячейки таблицы',
split_cells_desc : 'Разделить ячейки таблицы',
merge_cells_desc : 'Объединить ячейки таблицы',
cut_row_desc : 'Вылезать строку таблицы',
copy_row_desc : 'Скопировать строку таблицы',
paste_row_before_desc : 'Вставить строку таблицы перед',
paste_row_after_desc : 'Вставить строку таблицы после',
id : 'Id',
style: 'Стиль',
langdir : 'Описание языка',
langcode : 'Код языка',
mime : 'Целевой MIME тип',
ltr : 'Слева направо',
rtl : 'Справа налево',
bgimage : 'Фоновое изображение',
summary : 'Краткое описание',
td : "Тело",
th : "Заголовок",
cell_cell : 'Обновить текущую ячейку',
cell_row : 'Обновить текущую строку',
cell_all : 'Обновить все ячейки в таблице',
row_row : 'Обновить текущую строку',
row_odd : 'Update odd rows in table',
row_even : 'Update even rows in table',
row_all : 'Обновить все строки в таблице',
thead : 'Заголовок таблицы',
tbody : 'Тело таблицы',
tfoot : 'Футер таблицы',
del : 'Удалить таблицу',
scope : 'Границы',
row : 'Строка',
col : 'Колонка',
rowgroup : 'Группа строк',
colgroup : 'Группа колонок',
missing_scope: 'Вы уверены, что хотите продолжать не обозначив границы ячеек шапки таблицы? Без этого, возможно, некоторым пользователям будет затруднительно понять, что за данные находятся в таблице.',
table_delta_width : 30,
cellprops_delta_width : 130
});
