// SI lang variables ISO-8859-2

tinyMCE.addToLang('table',{
general_tab : 'Splo&#353;no',
advanced_tab : 'Napredno',
general_props : 'Splo&#353;ne lastnosti',
advanced_props : 'Napredne lastnosti',
desc : 'Vstavi novo tabelo',
row_before_desc : 'Vstavi vrstico pred',
row_after_desc : 'Vstavi vrstico za',
delete_row_desc : 'Zbri&#353;i vrstico',
col_before_desc : 'Vstavi stolpec pred',
col_after_desc : 'Vstavi stolpec za',
delete_col_desc : 'Zbri&#353;i stolpec',
rowtype : 'Vrstica v delu tabele',
title : 'Vstavi/uredi tabelo',
width : '&#352;irina',
height : 'Vi&#353;ina',
cols : '&#352;t. stolpcev',
rows : '&#352;t. vrstic',
cellspacing : 'Razmik med celicami',
cellpadding : 'Odmik med celicami',
border : 'Okvir',
align : 'Poravnava',
align_default : 'Privzeto',
align_left : 'Levo',
align_right : 'Desno',
align_middle : 'Na sredino',
row_title : 'Lastnosti vrstice',
cell_title : 'Lastnosti celice',
cell_type : 'Tip celice',
row_desc : 'Lastnosti vrstice',
cell_desc : 'Lastnosti celice',
valign : 'Navpi&#269;na poravnava',
align_top : 'Na vrh',
align_bottom : 'Na dno',
props_desc : 'Lastnosti tabele',
bordercolor : 'Barva okvirja',
bgcolor : 'Barva ozadja',
merge_cells_title : 'Zdru&#382;i celice',
split_cells_desc : 'Razdeli celice',
merge_cells_desc : 'Zdru&#382;i celice',
cut_row_desc : 'Izre&#382;i vrstico',
copy_row_desc : 'Kopiraj vrstico',
paste_row_before_desc : 'Prilepi tabelo pred',
paste_row_after_desc : 'Prilepi tabelo za',
id : 'Id',
style: 'Stil',
langdir : 'Smer jezika',
langcode : 'Koda jezika',
mime : 'MIME type tar&#269;e',
ltr : 'Od leve proti desni',
rtl : 'Od desne proti levi',
bgimage : 'Slika za ozadje',
summary : 'Naslov',
td : "Podatki",
th : "Glava",
cell_cell : 'Posodobi trenutno celico',
cell_row : 'Posodobi vse celice v vrstici',
cell_all : 'Posodobi vse celice v tabeli',
row_row : 'Posodobi trenutno vrstico',
row_odd : 'Posodobi lihe vrstice v tabeli',
row_even : 'Posodobi sode vrstice v tabeli',
row_all : 'Posodobi vse vrstice v tabeli',
thead : 'Glava tabele',
tbody : 'Telo tabele',
tfoot : 'Dno tabele',
del : 'Zbri&#353;i tabelo',
scope : 'Domena',
row : 'Vrstica',
col : 'Stolpec',
rowgroup : 'Skupina vrstic',
colgroup : 'Skupina stolpcev',
missing_scope: 'Ali ste prepri&#269;ani, da &#382;elite nadaljevati brez domene za to celico v glavi tabele? Brez nje bodo lahko imeli uporabniki s posebnimi potrebami probleme pri razumevanju vsebine tabele.'
});
