// UK lang variables

tinyMCE.addToLang('table',{
general_tab : 'Generella inst&auml;llningar',
advanced_tab : 'Avancerade inst&auml;llningar',
general_props : 'Generella inst&auml;llningar',
advanced_props : 'Avancerade inst&auml;llningar',
desc : 'Skapa ny tabell',
before_desc : 'Skapa rad f&ouml;re',
after_desc : 'Skapa rad efter',
row_before_desc : 'Skapa rad f&ouml;re',
row_after_desc : 'Skapa rad efter',
delete_row_desc : 'Ta bort rad',
col_before_desc : 'Skapa kolumn f&ouml;re',
col_after_desc : 'Skapa kolumn efter',
delete_col_desc : 'Ta bort kolumn',
rowtype : 'Rad typ',
title : 'Skapa/redigera ny tabell',
width : 'Bredd',
height : 'H&ouml;jd',
cols : 'Columner',
rows : 'Rader',
cellspacing : 'Cellmellanrum',
cellpadding : 'Cellutfyllnad',
border : 'Ram',
align : 'Justering',
align_default : 'Ingen',
align_left : 'V&auml;nster',
align_right : 'H&ouml;ger',
align_middle : 'Mitten',
row_title : 'Tabell radsinst&auml;llningar',
cell_title : 'Tabell cellsinst&auml;llningar',
cell_type : 'Cell typ',
row_desc : 'Tabell rads inst&auml;llningar',
cell_desc : 'Tabell cells inst&auml;llningar',
valign : 'Vertical justering',
align_top : 'Toppen',
align_bottom : 'Botten',
props_desc : 'Tabell inst&auml;llningar',
bordercolor : 'Ram f&auml;rg',
bgcolor : 'Bakgrundsf&auml;rg',
merge_cells_title : 'Sammanfoga tabell celler',
split_cells_desc : 'Delaupp tabell celler',
merge_cells_desc : 'Sammanfoga tabell celler',
cut_row_desc : 'Klipput tabell rad',
copy_row_desc : 'Kopiera tabell rad',
paste_row_before_desc : 'Klistra in tabell rad f&ouml;re',
paste_row_after_desc : 'Klistra in tabell rad efter',
id : 'Id',
style: 'Stil',
langdir : 'Skrift riktning',
langcode : 'Spr&aring;k k&aring;d',
ltr : 'V&auml;nster till h&ouml;ger',
rtl : 'H&ouml;ger till v&auml;nster',
bgimage : 'Bakgrundsbild',
summary : 'Sammanfattning',
td : "Data",
th : "Huvud",
cell_cell : 'Updatera nuvarande cell',
cell_row : 'Updatera alla celler i raden',
cell_all : 'Updatera alla celler t tabellen',
row_row : 'Updatera nuvarande rad',
row_odd : 'Updatera udda rader i tabellen',
row_even : 'Updatera j&auml;mna rader i tabellen',
row_all : 'Updatera alla rader i tabellen',
thead : 'Tabell Huvud',
tbody : 'Tabell Kropp',
tfoot : 'Tabell Fot',
del : 'Tabort tabell',
scope : 'Scope',
row : 'Rad',
col : 'Kolumn',
rowgroup : 'Rad grupp',
colgroup : 'Kolumn grupp',
missing_scope: '&Auml;r du s&auml;ker p&aring; att du vill forts&auml;tta utan att specifisera ett scope, utan denna kan det bli sv&aring;rt f&ouml;r handikappade att f&ouml;rst&aring; tabellen.'
});
