// UK lang variables

tinyMCE.addToLang('table',{
general_tab : 'Genel',
advanced_tab : 'Geliþmiþ',
general_props : 'Genel özellikler',
advanced_props : 'Geliþmiþ özellikler',
desc : 'Yeni tablo ekle',
row_before_desc : 'Satýr ekle(öncesinde)',
row_after_desc : 'Satýr ekle(sonrasýnda)',
delete_row_desc : 'Satýrý sil',
col_before_desc : 'Kolon ekle(öncesinde)',
col_after_desc : 'Kolon ekle(sonrasýnda)',
delete_col_desc : 'Kolonu sil',
rowtype : 'Row in table part',
title : 'Tablo ekle/düzenle',
width : 'Geniþlik',
height : 'Yükseklik',
cols : 'Kolonlar',
rows : 'Satýrlar',
cellspacing : 'Hücre boþluðu',
cellpadding : 'Hücre dolðusu',
border : 'Sýnýr kalýnlýk',
align : 'Hizalama',
align_default : 'Varsayýlan',
align_left : 'Sol',
align_right : 'Sað',
align_middle : 'Orta',
row_title : 'Tablo satýr özellikleri',
cell_title : 'Tablo hücre özellikleri',
cell_type : 'Hücre tipi',
row_desc : 'Tablo satýr özellikleri',
cell_desc : 'Tablo hücre özellikleri',
valign : 'Düþey hizalama',
align_top : 'Üst',
align_bottom : 'Alt',
props_desc : 'Tablo özellikleri',
bordercolor : 'Sýnýr rengi',
bgcolor : 'Arkaplan rengi',
merge_cells_title : 'Tablo hücrelerini birleþtir',
split_cells_desc : 'Tablo hücrelerini ayýr',
merge_cells_desc : 'Tablo hücrelerini birleþtir',
cut_row_desc : 'Tablo satýrýný kes',
copy_row_desc : 'Tablo satýrýný kopyala',
paste_row_before_desc : 'Tablo satýrý yapýþtýr(önce)',
paste_row_after_desc : 'Tablo satýrý yapýþtýr(sonra)',
id : 'Id',
style: 'Stil',
langdir : 'Yazým yönü',
langcode : 'Dil kodu',
mime : 'Hedef MIME tipi',
ltr : 'Soldan saða',
rtl : 'Saðdan sola',
bgimage : 'Arkaplan resmi',
summary : 'Özet',
td : "Veri",
th : "Baþlýk",
cell_cell : 'Hücreyi güncelle',
cell_row : 'Satýrdaki tüm hücreleri güncelle',
cell_all : 'Tablodaki tüm hücreleri güncelle',
row_row : 'Satýrý güncelle',
row_odd : 'Tablodaki sýrasý tek olan satýrlarý güncelle',
row_even : 'Tablodaki sýrasý çift olan satýrlarý güncelle',
row_all : 'Tablodaki tüm satýrlarý güncelle',
thead : 'Tablo baþlýðý',
tbody : 'Tablo gövdesi',
tfoot : 'Table altý',
del : 'Tabloyu sil',
scope : 'Kapsam',
row : 'Satýr',
col : 'Kolon',
rowgroup : 'Satýr Gurubu',
colgroup : 'Kolon Gurubu',
missing_scope: 'Tablo baþlýk hüclerlerinin kapsamlarýný belirmeden devam etmek istediðinize emin misiniz? Eðer belirtmesseniz tablo görünümünde problemler olabilir!'
});
