// TW lang variables contributed by Jim Kou

tinyMCE.addToLang('',{
insert_table_align : '對齊',
insert_table_align_default : '標準',
insert_table_align_left : '齊左',
insert_table_align_middle : '置中',
insert_table_align_right : '齊右',
insert_table_border : '框線',
insert_table_cellpadding : '字&Aring;暺P儲存格間隙',
insert_table_cellspacing : '儲存格間隙',
insert_table_class : '樣式',
insert_table_cols : '行',
insert_table_height : '高度',
insert_table_rows : '列',
insert_table_title : '表格標題',
insert_table_width : '寬度',
table_delete_col_desc : '刪除一行儲存格',
table_delete_row_desc : '刪除一列儲存格',
table_desc : '表格',
table_insert_col_after_desc : '新增一行儲存格(後)',
table_insert_col_before_desc : '新增一行儲存格(前)',
table_insert_row_after_desc : '新增一列儲存格(後)',
table_insert_row_before_desc : '新增一列儲存格(前)',
table_row_title : 'Table row properties',
table_cell_title : 'Table cell properties',
table_row_desc : 'Table row properties',
table_cell_desc : 'Table cell properties',
insert_table_valign : 'Vertical alignment',
insert_table_align_top : 'Top',
insert_table_align_bottom : 'Bottom',
table_props_desc : 'Table properties',
table_bordercolor : 'Border color',
table_bgcolor : 'Bg color',
table_merge_cells_title : 'Merge table cells',
table_split_cells_desc : 'Split table cells',
table_merge_cells_desc : 'Merge table cells',
table_cut_row_desc : 'Cut table row',
table_copy_row_desc : 'Copy table row',
table_paste_row_before_desc : 'Paste table row before',
table_paste_row_after_desc : 'Paste table row after',
table_insert_desc : 'Insert a new table'
});
