// Simplified Chinese lang variables contributed by tom_cat (thomaswangyang@gmail.com)

tinyMCE.addToLang('table',{
general_tab : '一般',
advanced_tab : '高级',
general_props : '一般属性',
advanced_props : '高技属性',
desc : '插入一个新表',
row_before_desc : '向前插入一行',
row_after_desc : '向后插入一行',
delete_row_desc : '删除行',
col_before_desc : '向左插入一列',
col_after_desc : '向右插入一列',
delete_col_desc : '删除列',
rowtype : '行种类',
title : '插入/修改 表',
width : '宽',
height : '高',
cols : '列数',
rows : '行数',
cellspacing : '单元格空间',
cellpadding : '单元格填充',
border : '边框',
align : '对齐',
align_default : '默认',
align_left : '居左',
align_right : '居右',
align_middle : '居中',
row_title : '行标题',
cell_title : '单元格标题',
cell_type : '单元格种类',
row_desc : '行描述',
cell_desc : '单元格描述',
valign : '垂直对齐',
align_top : '顶端',
align_bottom : '底端',
props_desc : '表属性',
bordercolor : '边框颜色',
bgcolor : '背景颜色',
merge_cells_title : '合并表中单元格标题',
split_cells_desc : '分类表中单元格描述',
merge_cells_desc : '合并表中单元格描述',
cut_row_desc : '剪切行',
copy_row_desc : '复制行',
paste_row_before_desc : '向前粘贴一行',
paste_row_after_desc : '向后粘贴一行',
id : '表识',
style: '样式',
langdir : '书写方向',
langcode : '语言编码',
mime : '目标 MIME 种类',
ltr : '从左到右',
rtl : '从右到左',
bgimage : '背景图片',
summary : '小结',
td : "数据",
th : "页眉",
cell_cell : '更新当前单元格',
cell_row : '更新行中所有单元格',
cell_all : '更新表中所有单元格',
row_row : '更新当前行',
row_odd : '更新奇数行',
row_even : '更新偶数行',
row_all : '更新表中所有行',
thead : '表头',
tbody : '表中',
tfoot : '表尾',
del : '删除表',
scope : '区域',
row : '行',
col : '列',
rowgroup : '行集团',
colgroup : '列集团',
missing_scope: '您确认要在没有声明编辑区域时继续吗？没有声明编辑区域将使阅读者看起来很费力。'
});
