// Traditional Chinese BIG-5; Twapweb Site translated; twapweb_AT_gmail_DOT_com
// 繁體中文 BIG-5 ；數位應用坊製作； twapweb_AT_gmail_DOT_com

tinyMCE.addToLang('table',{
general_tab : '一般',
advanced_tab : '進階',
general_props : '一般屬性',
advanced_props : '進階屬性',
desc : '插入新表格',
row_before_desc : '在之前插入列',
row_after_desc : '在之後插入列',
delete_row_desc : '刪除列',
col_before_desc : '在之前插入行',
col_after_desc : '在之後插入行',
delete_col_desc : '刪除行',
rowtype : '表格中的列',
title : '插入或調整表格',
width : '寬',
height : '高',
cols : '行',
rows : '列',
cellspacing : '儲存格格線間距',
cellpadding : '儲存格內文與格線間距',
border : '框線',
align : '位置',
align_default : '內定',
align_left : '靠左',
align_right : '靠右',
align_middle : '置中',
row_title : '列屬性',
cell_title : '儲存格屬性',
cell_type : '儲存格類型',
row_desc : '列屬性',
cell_desc : '儲存格屬性',
valign : '垂直位置',
align_top : '頂端',
align_bottom : '底部',
props_desc : '表格屬性',
bordercolor : '框線顏色',
bgcolor : '背景顏色',
merge_cells_title : '合併儲存格',
split_cells_desc : '分割儲存格',
merge_cells_desc : '合併儲存格',
cut_row_desc : '剪下列',
copy_row_desc : '複製列',
paste_row_before_desc : '在之前貼上列',
paste_row_after_desc : '在之後貼上列',
id : '編碼',
style: '式樣',
langdir : '語言用法',
langcode : '語碼',
mime : '對象 MIME 類型',
ltr : '由左至右',
rtl : '由右至左',
bgimage : '背景圖檔',
summary : '一覽',
td : "資料",
th : "標頭",
cell_cell : '更新所在的儲存格',
cell_row : '更新列內的儲存格',
cell_all : '更新表格中的儲存格',
row_row : '更新所在的列',
row_odd : '更新表格中的奇數列',
row_even : '更新表格中的偶數列',
row_all : '更新表格中的列',
thead : '表格標頭',
tbody : '表格實體',
tfoot : '表格底部',
del : '刪除表格',
scope : '範圍',
row : '列',
col : '行',
rowgroup : '群列',
colgroup : '群行',
missing_scope: '確定要在沒有對此表格標頭設定範圍下繼續執行嗎？\n不加以設定的話，可能會導致某些使用者無法順利讀取表格中的部份或是整體資訊。'
});
