<?php

/**
 * libphonenumber-for-php-lite data file
 * This file has been @generated from libphonenumber data
 * Do not modify!
 * @internal
 */

namespace libphonenumber;

class CountryCodeToRegionCodeMap
{
    // A mapping from a country code to the region codes which denote the
    // country/region represented by that country code. In the case of multiple
    // countries sharing a calling code, such as the NANPA countries, the one
    // indicated with "isMainCountryForCode" in the metadata should be first.

    public const COUNTRY_CODE_TO_REGION_CODE_MAP = [
        1 => [
            'US',
            'AG',
            'AI',
            'AS',
            'BB',
            'BM',
            'BS',
            'CA',
            'DM',
            'DO',
            'GD',
            'GU',
            'JM',
            'KN',
            'KY',
            'LC',
            'MP',
            'MS',
            'PR',
            'SX',
            'TC',
            'TT',
            'VC',
            'VG',
            'VI',
        ],
        7 => [
            'RU',
            'KZ',
        ],
        20 => [
            'EG',
        ],
        27 => [
            'ZA',
        ],
        30 => [
            'GR',
        ],
        [
            'NL',
        ],
        [
            'BE',
        ],
        [
            'FR',
        ],
        [
            'ES',
        ],
        36 => [
            'HU',
        ],
        39 => [
            'IT',
            'VA',
        ],
        [
            'RO',
        ],
        [
            'CH',
        ],
        43 => [
            'AT',
        ],
        [
            'GB',
            'GG',
            'IM',
            'JE',
        ],
        [
            'DK',
        ],
        [
            'SE',
        ],
        [
            'NO',
            'SJ',
        ],
        [
            'PL',
        ],
        [
            'DE',
        ],
        51 => [
            'PE',
        ],
        [
            'MX',
        ],
        [
            'CU',
        ],
        [
            'AR',
        ],
        [
            'BR',
        ],
        [
            'CL',
        ],
        [
            'CO',
        ],
        [
            'VE',
        ],
        60 => [
            'MY',
        ],
        [
            'AU',
            'CC',
            'CX',
        ],
        [
            'ID',
        ],
        [
            'PH',
        ],
        [
            'NZ',
        ],
        [
            'SG',
        ],
        [
            'TH',
        ],
        81 => [
            'JP',
        ],
        [
            'KR',
        ],
        84 => [
            'VN',
        ],
        86 => [
            'CN',
        ],
        90 => [
            'TR',
        ],
        [
            'IN',
        ],
        [
            'PK',
        ],
        [
            'AF',
        ],
        [
            'LK',
        ],
        [
            'MM',
        ],
        98 => [
            'IR',
        ],
        211 => [
            'SS',
        ],
        [
            'MA',
            'EH',
        ],
        [
            'DZ',
        ],
        216 => [
            'TN',
        ],
        218 => [
            'LY',
        ],
        220 => [
            'GM',
        ],
        [
            'SN',
        ],
        [
            'MR',
        ],
        [
            'ML',
        ],
        [
            'GN',
        ],
        [
            'CI',
        ],
        [
            'BF',
        ],
        [
            'NE',
        ],
        [
            'TG',
        ],
        [
            'BJ',
        ],
        [
            'MU',
        ],
        [
            'LR',
        ],
        [
            'SL',
        ],
        [
            'GH',
        ],
        [
            'NG',
        ],
        [
            'TD',
        ],
        [
            'CF',
        ],
        [
            'CM',
        ],
        [
            'CV',
        ],
        [
            'ST',
        ],
        [
            'GQ',
        ],
        [
            'GA',
        ],
        [
            'CG',
        ],
        [
            'CD',
        ],
        [
            'AO',
        ],
        [
            'GW',
        ],
        [
            'IO',
        ],
        [
            'AC',
        ],
        [
            'SC',
        ],
        [
            'SD',
        ],
        [
            'RW',
        ],
        [
            'ET',
        ],
        [
            'SO',
        ],
        [
            'DJ',
        ],
        [
            'KE',
        ],
        [
            'TZ',
        ],
        [
            'UG',
        ],
        [
            'BI',
        ],
        [
            'MZ',
        ],
        260 => [
            'ZM',
        ],
        [
            'MG',
        ],
        [
            'RE',
            'YT',
        ],
        [
            'ZW',
        ],
        [
            'NA',
        ],
        [
            'MW',
        ],
        [
            'LS',
        ],
        [
            'BW',
        ],
        [
            'SZ',
        ],
        [
            'KM',
        ],
        290 => [
            'SH',
            'TA',
        ],
        [
            'ER',
        ],
        297 => [
            'AW',
        ],
        [
            'FO',
        ],
        [
            'GL',
        ],
        350 => [
            'GI',
        ],
        [
            'PT',
        ],
        [
            'LU',
        ],
        [
            'IE',
        ],
        [
            'IS',
        ],
        [
            'AL',
        ],
        [
            'MT',
        ],
        [
            'CY',
        ],
        [
            'FI',
            'AX',
        ],
        [
            'BG',
        ],
        370 => [
            'LT',
        ],
        [
            'LV',
        ],
        [
            'EE',
        ],
        [
            'MD',
        ],
        [
            'AM',
        ],
        [
            'BY',
        ],
        [
            'AD',
        ],
        [
            'MC',
        ],
        [
            'SM',
        ],
        380 => [
            'UA',
        ],
        [
            'RS',
        ],
        [
            'ME',
        ],
        [
            'XK',
        ],
        385 => [
            'HR',
        ],
        [
            'SI',
        ],
        [
            'BA',
        ],
        389 => [
            'MK',
        ],
        420 => [
            'CZ',
        ],
        [
            'SK',
        ],
        423 => [
            'LI',
        ],
        500 => [
            'FK',
        ],
        [
            'BZ',
        ],
        [
            'GT',
        ],
        [
            'SV',
        ],
        [
            'HN',
        ],
        [
            'NI',
        ],
        [
            'CR',
        ],
        [
            'PA',
        ],
        [
            'PM',
        ],
        [
            'HT',
        ],
        590 => [
            'GP',
            'BL',
            'MF',
        ],
        [
            'BO',
        ],
        [
            'GY',
        ],
        [
            'EC',
        ],
        [
            'GF',
        ],
        [
            'PY',
        ],
        [
            'MQ',
        ],
        [
            'SR',
        ],
        [
            'UY',
        ],
        [
            'CW',
            'BQ',
        ],
        670 => [
            'TL',
        ],
        672 => [
            'NF',
        ],
        [
            'BN',
        ],
        [
            'NR',
        ],
        [
            'PG',
        ],
        [
            'TO',
        ],
        [
            'SB',
        ],
        [
            'VU',
        ],
        [
            'FJ',
        ],
        [
            'PW',
        ],
        [
            'WF',
        ],
        [
            'CK',
        ],
        [
            'NU',
        ],
        685 => [
            'WS',
        ],
        [
            'KI',
        ],
        [
            'NC',
        ],
        [
            'TV',
        ],
        [
            'PF',
        ],
        [
            'TK',
        ],
        [
            'FM',
        ],
        [
            'MH',
        ],
        800 => [
            '001',
        ],
        808 => [
            '001',
        ],
        850 => [
            'KP',
        ],
        852 => [
            'HK',
        ],
        [
            'MO',
        ],
        855 => [
            'KH',
        ],
        [
            'LA',
        ],
        870 => [
            '001',
        ],
        878 => [
            '001',
        ],
        880 => [
            'BD',
        ],
        [
            '001',
        ],
        [
            '001',
        ],
        [
            '001',
        ],
        886 => [
            'TW',
        ],
        888 => [
            '001',
        ],
        960 => [
            'MV',
        ],
        [
            'LB',
        ],
        [
            'JO',
        ],
        [
            'SY',
        ],
        [
            'IQ',
        ],
        [
            'KW',
        ],
        [
            'SA',
        ],
        [
            'YE',
        ],
        [
            'OM',
        ],
        970 => [
            'PS',
        ],
        [
            'AE',
        ],
        [
            'IL',
        ],
        [
            'BH',
        ],
        [
            'QA',
        ],
        [
            'BT',
        ],
        [
            'MN',
        ],
        [
            'NP',
        ],
        979 => [
            '001',
        ],
        992 => [
            'TJ',
        ],
        [
            'TM',
        ],
        [
            'AZ',
        ],
        [
            'GE',
        ],
        [
            'KG',
        ],
        998 => [
            'UZ',
        ],
    ];

}
