<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.moodle.org/dev/Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['cannotcreatelangdir'] = 'Ei saa luua lang kataloogi';
$string['cannotcreatetempdir'] = 'Ei saa luua temp kataloogi';
$string['cannotdownloadcomponents'] = 'Ei saa alla tõmmata komponente.';
$string['cannotdownloadzipfile'] = 'Ei saa alla tõmmata ZIP-faili.';
$string['cannotfindcomponent'] = 'Ei leia komponenti.';
$string['cannotsavemd5file'] = 'Ei saa salvestada md5-faili.';
$string['cannotsavezipfile'] = 'Ei saa salvestada ZIP-faili.';
$string['cannotunzipfile'] = 'Ei saa faili lahti pakkida.';
$string['componentisuptodate'] = 'Komponent on ajakohane';
$string['downloadedfilecheckfailed'] = 'Alla laetud faili kontroll ebaõnnestus.';
$string['invalidmd5'] = 'Kontrolli muutuja oli vale - proovi uuesti';
$string['missingrequiredfield'] = 'Mõned nõutud väljad on puudu';
$string['remotedownloaderror'] = 'Komponendi alla tõmbamine serverisse ebaõnnestus, palun kontrolli proksi seadeid, PHP cURL laiendus on tungivalt soovitatav.<br /><br />Sa pead tõmbama <a href="{$a->url}">{$a->url}</a> faili käsitsi, kopeerima selle "{$a->dest}" oma serveris ja pakkima lahti sinna.';
$string['wrongdestpath'] = 'Vale sihtrada.';
$string['wrongsourcebase'] = 'Vale allika URL-i baas.';
$string['wrongzipfilename'] = 'Vale ZIP-failinimi.';
