<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Automatically generated strings for Moodle installer
 *
 * Do not edit this file manually! It contains just a subset of strings
 * needed during the very first steps of installation. This file was
 * generated automatically by export-installer.php (which is part of AMOS
 * {@link http://docs.moodle.org/en/Development:Languages/AMOS}) using the
 * list of strings defined in /install/stringnames.txt.
 *
 * @package   installer
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['cliincorrectvalueerror'] = '오류: "{$a->option}" 에 대한 "{$a->value}" 값이 바르지 않음';
$string['cliincorrectvalueretry'] = '잘못된 값, 재 시도 바람';
$string['clitypevalue'] = '유형 값';
$string['clitypevaluedefault'] = '유형에 기본값({$a})을 쓰려면 엔터키를 누르세요';
$string['cliunknowoption'] = '알 수 없는 옵션: {$a}  --help를 사용하기 바람';
