<?php
class Foobar { use BazTrait { oldfunction as final Baz } }
class Foobar { use BazTrait { oldfunction as final abstract } }
class Foobar { use BazTrait { oldfunction as final and } }
class Foobar { use BazTrait { oldfunction as final array } }
class Foobar { use BazTrait { oldfunction as final as } }
class Foobar { use BazTrait { oldfunction as final break } }
class Foobar { use BazTrait { oldfunction as final callable } }
class Foobar { use BazTrait { oldfunction as final case } }
class Foobar { use BazTrait { oldfunction as final catch } }
class Foobar { use BazTrait { oldfunction as final class } }
class Foobar { use BazTrait { oldfunction as final clone } }
class Foobar { use BazTrait { oldfunction as final const } }
class Foobar { use BazTrait { oldfunction as final continue } }
class Foobar { use BazTrait { oldfunction as final declare } }
class Foobar { use BazTrait { oldfunction as final default } }
class Foobar { use BazTrait { oldfunction as final die } }
class Foobar { use BazTrait { oldfunction as final do } }
class Foobar { use BazTrait { oldfunction as final echo } }
class Foobar { use BazTrait { oldfunction as final else } }
class Foobar { use BazTrait { oldfunction as final elseif } }
class Foobar { use BazTrait { oldfunction as final empty } }
class Foobar { use BazTrait { oldfunction as final enddeclare } }
class Foobar { use BazTrait { oldfunction as final endfor } }
class Foobar { use BazTrait { oldfunction as final endforeach } }
class Foobar { use BazTrait { oldfunction as final endif } }
class Foobar { use BazTrait { oldfunction as final endswitch } }
class Foobar { use BazTrait { oldfunction as final endwhile } }
class Foobar { use BazTrait { oldfunction as final eval } }
class Foobar { use BazTrait { oldfunction as final exit } }
class Foobar { use BazTrait { oldfunction as final extends } }
class Foobar { use BazTrait { oldfunction as final final } }
class Foobar { use BazTrait { oldfunction as final finally } }
class Foobar { use BazTrait { oldfunction as final for } }
class Foobar { use BazTrait { oldfunction as final foreach } }
class Foobar { use BazTrait { oldfunction as final function } }
class Foobar { use BazTrait { oldfunction as final global } }
class Foobar { use BazTrait { oldfunction as final goto } }
class Foobar { use BazTrait { oldfunction as final if } }
class Foobar { use BazTrait { oldfunction as final implements } }
class Foobar { use BazTrait { oldfunction as final include } }
class Foobar { use BazTrait { oldfunction as final include_once } }
class Foobar { use BazTrait { oldfunction as final instanceof } }
class Foobar { use BazTrait { oldfunction as final insteadof } }
class Foobar { use BazTrait { oldfunction as final interface } }
class Foobar { use BazTrait { oldfunction as final isset } }
class Foobar { use BazTrait { oldfunction as final list } }
class Foobar { use BazTrait { oldfunction as final namespace } }
class Foobar { use BazTrait { oldfunction as final new } }
class Foobar { use BazTrait { oldfunction as final or } }
class Foobar { use BazTrait { oldfunction as final print } }
class Foobar { use BazTrait { oldfunction as final private } }
class Foobar { use BazTrait { oldfunction as final protected } }
class Foobar { use BazTrait { oldfunction as final public } }
class Foobar { use BazTrait { oldfunction as final require } }
class Foobar { use BazTrait { oldfunction as final require_once } }
class Foobar { use BazTrait { oldfunction as final return } }
class Foobar { use BazTrait { oldfunction as final static } }
class Foobar { use BazTrait { oldfunction as final switch } }
class Foobar { use BazTrait { oldfunction as final throw } }
class Foobar { use BazTrait { oldfunction as final trait } }
class Foobar { use BazTrait { oldfunction as final try } }
class Foobar { use BazTrait { oldfunction as final unset } }
class Foobar { use BazTrait { oldfunction as final use } }
class Foobar { use BazTrait { oldfunction as final var } }
class Foobar { use BazTrait { oldfunction as final while } }
class Foobar { use BazTrait { oldfunction as final xor } }
class Foobar { use BazTrait { oldfunction as final yield } }
class Foobar { use BazTrait { oldfunction as final __CLASS__ } }
class Foobar { use BazTrait { oldfunction as final __DIR__ } }
class Foobar { use BazTrait { oldfunction as final __FILE__ } }
class Foobar { use BazTrait { oldfunction as final __FUNCTION__ } }
class Foobar { use BazTrait { oldfunction as final __METHOD__ } }
class Foobar { use BazTrait { oldfunction as final __NAMESPACE__ } }
