<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
///
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!
///
/// File generated by cvs://contrib/lang2installer/installer_builder
/// using strings defined in stringnames.txt (same dir)

$string['admindirerror'] = 'Әкімшіліктің көрсетілген каталогы қате';
$string['admindirname'] = 'Әкімшіліктер каталогы';
$string['caution'] = 'Ескерту';
$string['check'] = 'Болдырмау';
$string['closewindow'] = 'Терезені жабу';
$string['configfilewritten'] = 'config.php сәтті жасалды';
$string['continue'] = 'Жалғастыру';
$string['database'] = 'Мәліметтер қоры';
$string['dataroot'] = 'Мәліметтер каталогы';
$string['dbhost'] = 'Сервер хосты';
$string['dbprefix'] = 'Кестелердің префиксі';
$string['dbtype'] = 'Түр';
$string['dirroot'] = 'Moodle каталогы';
$string['download'] = 'Жүктеу';
$string['error'] = 'Қате';
$string['fail'] = 'Қате';
$string['gdversion'] = 'GD нұсқа';
$string['help'] = 'Көмек';
$string['info'] = 'Ақпарат';
$string['installation'] = 'Орнату';
$string['language'] = 'Тіл';
$string['memorylimit'] = 'Жадының шегі';
$string['moodledocslink'] = 'Бұл бетке арналған Moodle құжаттамасы';
$string['name'] = 'Атау';
$string['next'] = 'Келесі';
$string['ok'] = 'OK';
$string['parentlanguage'] = 'ru';
$string['password'] = 'Кілтсөз';
$string['previous'] = 'Алдыңғы';
$string['report'] = 'Есеп';
$string['status'] = 'Мәртебе';
$string['thischarset'] = 'UTF-8';
$string['thisdirection'] = 'ltr';
$string['thislanguage'] = 'Қазақша';
$string['user'] = 'Пайдаланушы';
?>
