<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
///
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!
///
/// File generated by cvs://contrib/lang2installer/installer_builder
/// using strings defined in stringnames.txt (same dir)

$string['availablelangs'] = 'حزم اللغة المتوفره';
$string['cannotcreatelangdir'] = 'لم يتم أنشاء دليل اللغة';
$string['cannotdownloadcomponents'] = 'لم يتم تنزيل بعض العناصر';
$string['cannotdownloadzipfile'] = 'لم يتم تنزيل بعض الملف المضغوط';
$string['cannotfindcomponent'] = 'لم يتم العثور على العنصر';
$string['cannotsavemd5file'] = 'لم يتم حفظ ملف  md5';
$string['cannotsavezipfile'] = 'لم يتم حفظ الملف المضغوط';
$string['cannotunzipfile'] = 'لم يتم فك الملف المضغوط';
$string['chooselanguagehead'] = 'اختر اللغة';
$string['dataroot'] = 'دليل البيانات';
$string['dirroot'] = 'دليل مودل';
$string['environment'] = 'بيئة';
$string['environmentrequireinstall'] = 'مطلوب تثبيته/تمكينه';
$string['environmentrequireversion'] = 'مطلوب الأصدار $a->needed ، وانت تستخدم الأصدار $a->current';
$string['installation'] = 'تثبيت';
$string['language'] = 'اللغة';
$string['parentlanguage'] = 'المترجمون: أذا كانت لغتك لها لغة أم والتي يجب على مودل يتخدم ويوجد بعض التعابير مفقودة من حزمة لغتك، لذا يجب عليك تحديد الرمز هناء. لو تركت هذا الحقل فارغا سيتم استخدام اللغة الإنجليزية. على سبيل المثال : nl>>';
$string['phpversion'] = 'أصدار PHP';
$string['thischarset'] = 'UTF-8';
$string['thislanguage'] = 'عربي';
$string['wwwroot'] = 'WWW';
?>
