<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
///
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!
///
/// File generated by cvs://contrib/lang2installer/installer_builder
/// using strings defined in stringnames.txt (same dir)

$string['cannotcreatelangdir'] = 'lang dir બનાવી શકાતી નથી.';
$string['cannotcreatetempdir'] = 'temp dir બનાવી શકાતી નથી.';
$string['cannotdownloadcomponents'] = 'કમ્પોનન્ટ્સ ડાઊનલોડ કરી શકાતા નથી.';
$string['cannotdownloadzipfile'] = 'ઝિપ ફાઈલ ડાઊનલોડ કરી શકાતી નથી.';
$string['cannotfindcomponent'] = 'કમ્પોનન્ટ શોધી શકાતા નથી';
$string['cannotsavemd5file'] = 'md5 file સેવ કરી શકાતી નથી.';
$string['cannotsavezipfile'] = 'ZIP file સેવ કરી શકાતી નથી.';
$string['cannotunzipfile'] = 'ફાઈલને અનઝિપ કરી શકાતી નથી';
$string['check'] = 'તપાસ';
$string['closewindow'] = 'આ વિન્ડોને બંધ કરો.';
$string['componentisuptodate'] = 'કમ્પોનન્ટ અપ ડેઈટ છે.';
$string['continue'] = 'શરુ રાખો';
$string['downloadedfilecheckfailed'] = 'ડાઊનલોડ કરેલ ફાઈલનું ચેક નિષ્ફળ રહ્યું';
$string['error'] = 'ક્ષતિ (Error)';
$string['help'] = 'મદદ';
$string['info'] = 'માહિતિ';
$string['invalidmd5'] = 'અમન્ય md5';
$string['language'] = 'ભાષા';
$string['missingrequiredfield'] = 'કેટલાક જરૂરી ફિલ્ડ ગુમ છે';
$string['moodledocslink'] = 'આ પેજ માટેના મૂડલ ડોક્યુમેન્ટ';
$string['name'] = 'નામ';
$string['next'] = 'આગળ';
$string['password'] = 'પાસવર્ડ';
$string['previous'] = 'પહેલાનું';
$string['report'] = 'રિપોર્ટ';
$string['restricted'] = 'પ્રતિબંધિત';
$string['thischarset'] = 'UTF-8';
$string['thisdirection'] = 'ltr';
$string['thislanguage'] = 'ગુજરાતી';
$string['user'] = 'યુઝર';
$string['wrongdestpath'] = 'ખોટો ડેસ્ટીનેશન પાથ.';
$string['wrongzipfilename'] = 'ખોટું ઝિપ ફાઈલ નામ.';
?>
