<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
///
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!
///
/// File generated by cvs://contrib/lang2installer/installer_builder
/// using strings defined in stringnames.txt (same dir)

$string['availablelangs'] = 'Saatavilla olevat kielipaketit';
$string['cannotcreatelangdir'] = 'Kielihakemistoa ei voitu luoda';
$string['cannotdownloadcomponents'] = 'Komponentteja ei voitu ladata';
$string['cannotdownloadzipfile'] = 'ZIP-tiedostoa ei voitu ladata';
$string['cannotfindcomponent'] = 'Komponenttia ei löytynyt';
$string['cannotsavemd5file'] = 'MD5-tiedostoa ei voitu tallentaa';
$string['cannotsavezipfile'] = 'Zip-tiedosta ei voitu tallentaa';
$string['cannotunzipfile'] = 'Zip-tiedostoa ei voitu purkaa';
$string['chooselanguagehead'] = 'Valitse kieli';
$string['chooselanguagesub'] = 'Valitse kieli asennusohjelmaa varten. Voit valita muita kieliä käyttöösi myöhemmin.';
$string['dataroot'] = 'Datahakemisto';
$string['dirroot'] = 'Moodle hakemisto';
$string['environment'] = 'Ympäristö';
$string['environmentrequireinstall'] = 'vaaditaan asennettavaksi/käyttöönotettavaksi';
$string['environmentrequireversion'] = 'versio $a->needed vaaditaan ja käytössä on versio $a->current';
$string['installation'] = 'Asennus';
$string['language'] = 'Kieli';
$string['phpversion'] = 'PHP versio';
$string['reload'] = 'Lataa uudelleen';
$string['thischarset'] = 'UTF-8';
$string['thislanguage'] = 'Suomi';
$string['welcomep70'] = 'Napsauta \"Seuraava\"-painiketta jatkaaksesi moodlen asennusta';
$string['wwwroot'] = 'Web-osoite';
?>
