################################################################################
#  $Id$
#  
#  Copyright(c) 2004-2006, SpikeSource Inc. All Rights Reserved.
#  Licensed under the Open Software License version 2.1
#  (See http://www.spikesource.com/license.html)
################################################################################
To build PHPCoverage Distribution archives from source...

  $ cd trunk/corestackbase/spike/util/coverage/php
  $ svn update
  $ source /opt/oss/env.sh
  $ sudo pear install phpDocumentor ## Plus any other dependencies like
                                    ## * Archive_Tar
                                    ## * XML_Beautifier
  $ ant distribute -Dcomp.version=x.y.z

