<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
///
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!
///
/// File generated by cvs://contrib/lang2installer/installer_builder
/// using strings defined in stringnames.txt (same dir)

$string['closewindow'] = 'Затваряне на прозореца';
$string['continue'] = 'Напред';
$string['error'] = 'Грешка';
$string['help'] = 'Помощ';
$string['info'] = "Information";
$string['language'] = 'Език';
$string['name'] = 'Име';
$string['next'] = 'Напред';
$string['ok'] = 'OK';
$string['password'] = 'Парола';
$string['previous'] = 'Предишен';
$string['status'] = 'Състояние';
$string['thischarset'] = 'UTF-8';
$string['thisdirection'] = 'ltr';
$string['thislanguage'] = 'Български';
$string['user'] = 'Потребител';
?>
