<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
///
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!
///
/// File generated by cvs://contrib/lang2installer/installer_builder
/// using strings defined in stringnames.txt (same dir)

$string['availablelangs'] = 'Списак доступних језика';
$string['cannotcreatelangdir'] = 'Није могуће креирање директоријума језика';
$string['cannotdownloadcomponents'] = 'Није могуће преузети компоненте.';
$string['cannotdownloadzipfile'] = 'Није могуће преузимање архиве.';
$string['cannotfindcomponent'] = 'Није могуће пронаћи компоненту.';
$string['cannotsavemd5file'] = 'Није могуће сачувати md5 датотеку.';
$string['cannotsavezipfile'] = 'Није могуће сачувти ZIP архиву.';
$string['cannotunzipfile'] = 'Није могуће распаковати ZIP датотеку.';
$string['chooselanguagehead'] = 'Изаберите језик';
$string['chooselanguagesub'] = 'Молимо изаберите језик који ће се користити само током инсталације. Касније ћете моћи да изаберете језичка подешавања на нивоу сајта и корисника.';
$string['cliincorrectvalueerror'] = 'Грешка, неисправна вредност \"$a->value\" за \"$a->option\"';
$string['cliincorrectvalueretry'] = 'Неисправна вреднос, молим покушајте поново';
$string['cliinstallheader'] = 'Moodle $a програм за инсталацију из командне линије';
$string['clitypevalue'] = 'откуцај вредност';
$string['clitypevaluedefault'] = 'откуцај вредност, притисни Ентер да бисте употребили подразумевану вредност ($a)';
$string['cliunknowoption'] = 'Непрепозната опција:
$a';
$string['dataroot'] = 'Директоријум података';
$string['dirroot'] = 'Moodle директоријум';
$string['environment'] = 'Окружење';
$string['environmentrequireinstall'] = 'је неопходно инсталирати/омогућити';
$string['environmentrequireversion'] = 'неопходна верзија је $a->needed а Ви тренутно користите верзију $a->current';
$string['environmentsub2'] = 'Свака верзија Moodlea има минимум захтева по питању одговарајуће PHP верѕије и неколико обавезних PHP екстензија.
Пуна провера окружења се врши пре сваке инсталације или ажурирања постојеће верзије. Уколико не знате како да инсталирате нову верзију или омогућите PHP ектензије контактирајте Вашег сервер администратора.';
$string['errorsinenvironment'] = 'Грешке у окружењу';
$string['installation'] = 'Инсталација';
$string['language'] = 'Језик';
$string['parentlanguage'] = '<< ПРЕВОДИОЦИ: Ако Ваш језик има надређени језик који Moodle треба да користи када неки изрази недостају Вашем језичком пакету, специфицирајте његов код. Ако ово поље оставите празно биће коришћен енглески језик. Пример: nl >>';
$string['paths'] = 'Путање';
$string['pathserrcreatedataroot'] = 'Инсталциона процедура не може да креира директоријум базе података ($a->dataroot)';
$string['pathshead'] = 'Потврди путање';
$string['pathsrodataroot'] = 'У директоријум за податке није могућ упис';
$string['pathsroparentdataroot'] = 'У надређени директоријум ($a->parent) није могућ упис. Директоријум за податке ($a->dataroot) не може креирати инсталациони програм.';
$string['pathssubadmindir'] = 'Неколико сајтова за вебхостинг користи /admin као специјални УРЛ за приступ контролном панелу. На жалост, то може да да доведе до конфликта са стандардним директоријумом у којем су смештен Moodle администраторске странице. Овај проблем можете решити тако што ћете током инсталације преименовати admin директоријум у, на пример <em>moodleadmin</em>.';
$string['pathssubdataroot'] = 'Потребан вам је простор где ће Moodle чувати поставњене датотеке. Овај директоријум би требало да буде подешен тако да се може читати и у њега уписивати од стране корисника веб сервера (обично \'nobody\' или \'apache\'), али истовремено мора бити доступан директно преко веба. Уколико овај директоријум не постоји Moodle ће пикушати да га креира током инсталације,';
$string['pathssubdirroot'] = 'Пуна путања до директотијума за инсталацију Moodlea. Промените само уколико желите да користите синболичне линкове.';
$string['pathssubwwwroot'] = 'Пуна вер адреса преко које ће се приступати Moodleu. Није могуће приступати Moodleu користећи вишњ адреса. Уколико Ваш сајт има више јавних адреса онда на свима морате да подесите перманентну дирекцију ка једној адреси. Уколико је Ваш сајт доступам са Интернета али и из Интранет окружеања користите јавну адресу и подесите ДНС тако да и Интранет корисници могу да користе ту јавну адресу.';
$string['pathsunsecuredataroot'] = 'Dataroot локација није безбедна';
$string['pathswrongadmindir'] = 'Админ директоријум не постоји';
$string['pathswrongdirroot'] = 'Неисправна dirroot локација';
$string['phpextension'] = '$a PHP екстенѕија';
$string['phpversion'] = 'PHP верзија';
$string['reload'] = 'Учитај поново';
$string['thischarset'] = 'UTF-8';
$string['thislanguage'] = 'Српски';
$string['welcomep10'] = '$a->installername ($a->installerversion)';
$string['welcomep20'] = 'Приказана Вам је ова страница јер сте успешно инсталирали и покренули <strong>$a->packname $a->packversion</strong> пакет на Вашем рачунару. Честитамо!';
$string['welcomep30'] = 'Ово издање <strong>$a->installername</strong> укључује апликације за креирање окружења у ком ће <strong>Moodle</strong> успешно функционисати, конкретно:';
$string['welcomep40'] = 'Овај пакет обухвата и <strong>Moodle $a->moodlerelease ($a->moodleversion)</strong>.';
$string['welcomep50'] = 'Коришћење апликација из овог пакета је условљено њховим лиценцама. Комплетан <strong>$a->installername</strong> пакет је <a href=\"http://www.opensource.org/docs/definition_plain.html\">отвореног кода</a> и дистрибуира се под <a href=\"http://www.gnu.org/copyleft/gpl.html\">GPL</a> лиценцом.';
$string['welcomep60'] = 'Наредне странице ће Вас провести кроз неколико једноставних корака током којих ћете конфигурисати <strong>Moodle</strong> на Вашем рачунару. Можете прихватити подразумевана подешавања или их, опционо, прилагодити сопственим потребама.';
$string['welcomep70'] = 'Кликните на дугме за наставак да бисте даље подешавали <strong>Moodle</strong>.';
$string['wwwroot'] = 'Веб адреса';
?>
