<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
///
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!
///
/// File generated by cvs://contrib/lang2installer/installer_builder
/// using strings defined in stringnames.txt (same dir)

$string['admindirerror'] = 'Абраны каталог адміністратара няслушны';
$string['admindirname'] = 'Каталог адміністратара';
$string['caution'] = 'Папярэджанне';
$string['closewindow'] = 'Згарнуць вакно';
$string['configfilenotwritten'] = 'Скрыпт ўстаноўкі не змог аўтаматычна стварыць файл config.php, які ўтрымлівае Вамі абраныя настроўкі, па прычыне, што нельга пісаць у папку з устаноўкай Moodle. Вы можаце ўручную скапіяваць наступны код ў файл з назвай config.php і змясць яго ў карнявую папку ўстаноўкі Moodle.';
$string['configfilewritten'] = 'config.php быў паспяхова створаны';
$string['continue'] = 'Працягнуць';
$string['database'] = 'База Дадзеных';
$string['dataroot'] = 'Каталог дадзеных';
$string['dbhost'] = 'Хост сэрвера';
$string['dbprefix'] = 'Прэфікс табліцаў';
$string['dbtype'] = 'Тып';
$string['dirroot'] = 'Каталог Moodle';
$string['download'] = 'Загрузіць';
$string['error'] = 'Памылка';
$string['fail'] = 'Памылка';
$string['gdversion'] = 'GD версія';
$string['help'] = 'Дапамога';
$string['installation'] = 'Ладаванне';
$string['language'] = 'Мова';
$string['memorylimit'] = 'Мяжа памяці';
$string['name'] = 'Назва';
$string['next'] = 'Далей';
$string['ok'] = 'OK';
$string['password'] = 'Пароль';
$string['previous'] = 'Папярэдні';
$string['status'] = 'Статус';
$string['thischarset'] = 'UTF-8';
$string['thisdirection'] = 'ltr';
$string['thislanguage'] = 'Беларуская';
$string['user'] = 'Карыстальнік';
?>
