<?php
/// Please, do not edit this file manually! It's auto generated from
/// contents stored in your standard lang pack files:
/// (langconfig.php, install.php, moodle.php, admin.php and error.php)
///
/// If you find some missing string in Moodle installation, please,
/// keep us informed using http://moodle.org/bugs Thanks!
///
/// File generated by cvs://contrib/lang2installer/installer_builder
/// using strings defined in installer_strings (same dir)

$string['admindirerror'] = '명시된 관리 디렉토리가 맞지 않습니다';
$string['admindirname'] = '관리 디렉토리';
$string['admindirsettinghead'] = '관리자 디렉토리 설정 ...';
$string['admindirsettingsub'] = '몇개의 웹사이트만이 제어판 등을 제공하는 특별한 URL으로서 /admin을 사용합니다. 불행하게도 이것은 무들 관리페이지를 위한 표준 위치와 충돌을 일으킵니다. 설치도중 admin디렉토리 이름을 바꿈으로서 이런문제를 고칠수 있습니다. 새이름을 여기에 넣을 수 있습니다. 예: <br /> <br /><b>moodleadmin</b><br /> <br /> 이렇게 하면 무들에서 관리자 링크문제가 해결됩니다.';
$string['bypassed'] = '건너뜀';
$string['cannotcreatelangdir'] = 'lang 디렉토리를 만들 수 없습니다.';
$string['cannotcreatetempdir'] = 'temp 디렉토리를 만들 수 없습니다.';
$string['cannotdownloadcomponents'] = '구성요소를 내려받기 할 수 없습니다.';
$string['cannotdownloadzipfile'] = 'ZIP파일을 내려받기 할 수 없습니다.';
$string['cannotfindcomponent'] = '구성요소를 찾을 수 없습니다.';
$string['cannotsavemd5file'] = 'md5  파일을 저장할 수 없습니다.';
$string['cannotsavezipfile'] = 'ZIP 파일을 저장할 수 없습니다.';
$string['cannotunzipfile'] = '파일 압축풀기를 할 수 없습니다.';
$string['caution'] = '주의';
$string['check'] = '점검';
$string['chooselanguagehead'] = '언어를 선택하시오';
$string['chooselanguagesub'] = '설치를 위한 언어를 선택하시오. 추후 화면에 사이트와 사용자 언어를 선택할 수 있습니다.';
$string['closewindow'] = '이 창을 닫기';
$string['compatibilitysettingshead'] = 'PHP 설정을 검사하는 중 ..';
$string['compatibilitysettingssub'] = '당신의 서버는 무들이 잘 돌아가도록 하는데 필요한 모든 테스트를 통과해야 합니다.';
$string['componentisuptodate'] = '구성 요소가 최신의 것입니다.';
$string['configfilenotwritten'] = '설치 스크립트는 당신이 선택한 설정으로 config.php파일을 자동적으로 생성할수 없습니다. 아마도 무들의 경로에 쓰기 허용이 되어 있지 않은 모양입니다.  당신은 수동적으로 다음의 코드를 무들의 루트디렉토리안의 config.php파일로 복사할수 있습니다.';
$string['configfilewritten'] = '성공적으로 contig.php가 생성되었음.';
$string['configurationcompletehead'] = '초기 설정 완료';
$string['configurationcompletesub'] = '무들이 당신의 무들 설치 루트디렉토리에 있는 파일에 당신의 설정을 저장하도록 시도하였습니다.';
$string['continue'] = '계속';
$string['database'] = '데이타 베이스';
$string['databasecreationsettingshead'] = '대부분의 무들 데이터가 저장될 데이터베이스를 설정하는 것이 필요합니다. 아래에 명시된 설정대로 데이터베이스가 자동으로 설치프로그램에 의해 생성될 것입니다.';
$string['databasecreationsettingssub'] = '<b>종류:</b> 설치프로그램에 의해 \"mysql\" 로 고정됨 <br />
<b>호스트:</b>설치프로그램에 의해 \"localhost\"로 고정됨<br />
<b>이름:</b>데이터베이스이름, 예:moodle<br />
<b>사용자:</b> 설치프로그램에 의해 \"root\" 로 고정됨 <br />
<b>암호:</b> 데이터베이스 암호 <br />
<b>테이블 첨두어:</b> 모든 테이블에 사용되는 선택적 첨두어';
$string['databasesettingshead'] = '모든 무들데이터가 저장되는 데이터베이스를 설정할 필요가 있습니다. 이 데이터베이스는 이미 만들어졌으며 데이터베이스를 접근할 수 있는사용자 이름과 암호가 생성되었습니다.';
$string['databasesettingssub'] = '<b>종류:</b> mysql 또는 postgres7<br />
<b>호스트:</b>예: localhost 또는 db.isp.com <br />
<b>이름:</b> 데이터베이스 이름, 예:moodle<br />
<b>사용자:</b> 데이터베이스 사용자이름<br />
<b>암호:</b> 데이터베이스 암호<br />
<b>테이블 첨두어:</b> 모든 테이블에 사용되는 선택적 첨두어';
$string['dataroot'] = '데이타 디렉토리';
$string['datarooterror'] = '당신이 지정한 \'데이타 디렉토리\'가 없거나 생성되지 않았습니다. 정확한 경로를 적거나 수동으로 그 디렉토리를 생성해 놓으시오.';
$string['dbconnectionerror'] = '지정한 데이터베이스에 연결할 수 없습니다. 데이타베이스의 설정을 점검하시오.';
$string['dbcreationerror'] = '데이터베이스 생성 오류. 주어진 설정값으로 데이터베이스 이름을 생성할 수 없습니다.';
$string['dbhost'] = '호스트 서버';
$string['dbprefix'] = '접두사';
$string['dbtype'] = '형태';
$string['dbwrongencoding'] = '선택된 데이터베이스는 추천되지 않는 엔코딩 방법($a)에 의해 동작하고 있습니다. 유니코드 UTF-8로 인코딩 되는 데이터베이스를 사용하는 것이 좋습니다. 아래의\"DB 엔코딩 테스트 건너뛰기\"를 선택하여 이 테스트를 건너뛸 수 있지만 추후 문제를 경험할 수 있습니다.';
$string['directorysettingshead'] = '무들 설치 위치를 확인하기 바랍니다.';
$string['directorysettingssub'] = '<b>웹 주소:</b>
무들이 접속될 완전한 웹주소를 기입하시오.
만일 다중 URL을 통하여 웹사이트가 접근할 수 있다면 학습자가 사용하기 쉬운 자연스런 주소를 선택하시오. 끝에 슬래시를 포함하지 마십시요.
<br />
<br />
<b>무들 경로:</b>
이 설치에 대한 완전한 디렉토리 경로를 명시하시오. 대문자/소문자가 맞는지 확인하시오.
<br />
<br />
<b>데이터 디렉토리:</b>
무들이 올리기한 파일을 저장할 곳이 필요합니다. 이 디렉토리는 웹서버 사용자(\'nobody 나 \'apache\')들이 읽고 쓸 수 있어야 합니다. 그러나 직접 접근할 수 있어서는 안됩니다.';
$string['dirroot'] = '무들 디렉토리';
$string['dirrooterror'] = '무들 경로의 위치가 바르지 않은 것 같습니다 - 모들설치 프로그램을 찾을 수 없습니다. 아래의 값들은 초기화 되었습니다.';
$string['download'] = '다운로드';
$string['downloadedfilecheckfailed'] = '내려받기 한 파일 체크가 실패하였습니다.';
$string['downloadlanguagebutton'] = '\"$a\" 언어팩 내려받기';
$string['downloadlanguagehead'] = '언어팩 다운로드';
$string['downloadlanguagenotneeded'] = '기본 언어팩인 \"$a\"을 사용하여 설치과정을 계속할 수 있습니다.';
$string['downloadlanguagesub'] = '이제 언어팩 선택을 하셨기 때문에 추후에는 선택한 언어로 설치를 계속할 수 있습니다.<br /><br />만일 해당 언어팩을 내려받지 못한다면, 영문으로 설치가 계속될 것입니다.(일단 영문으로 프로그램을 깐 후, 다시 또 다른 언어팩을 선택하여 설정할 수 있는 기회가 있습니다) ';
$string['environmenterrortodo'] = '이 무들버전을 설치하기 전에 위에서 발견된 모든 환경설정 문제들을 해결해야 합니다.';
$string['environmenthead'] = '환경변수를 점검하십시요.';
$string['environmentrecommendinstall'] = '은 설치하거나 활성화되는 것을 추천합니다.';
$string['environmentrecommendversion'] = '$a->needed 버전을 추천합니다.당신은 $a->currentversion 을 사용하고 있습니다. ';
$string['environmentrequireinstall'] = '이 설치되거나 활성화 되어야 합니다.';
$string['environmentrequireversion'] = '$a->needed 버전을 사용하여야 합니다.당신은 $a->currentversion 을 사용하고 있습니다.';
$string['environmentsub'] = '당신의 시스템의 여러 구성요소가 시스템 요구조건을 만족하는지 점검합니다.';
$string['environmentxmlerror'] = '환경 설정 데이터 불러들이기 오류 ($a->error_code)';
$string['error'] = '오류';
$string['fail'] = '실패';
$string['fileuploads'] = '업로드된 파일 ';
$string['fileuploadserror'] = '이것은 켜져야 합니다.';
$string['gdversion'] = 'GD 의 버전';
$string['gdversionerror'] = 'GD 라이브러리는 진행과정과 사진을 만드는 것을 보여주어야 합니다.';
$string['globalsquotes'] = '전역변수 조작 안전성 결여';
$string['globalsquoteserror'] = '여러분의 PHP 설정을 다음과 같이 고쳤습니다:  register_globals 및 enable magic_quotes_gpc 을 껐습니다.';
$string['help'] = '도움';
$string['iconvrecommended'] = '당신의 사이트가 라틴언어계열이 아닌 언어를 지원하는 경우 사이트의 성능을 향상시키기 위해서는 ICONV라이브러리를 설치하는것을 권장합니다.';
$string['info'] = '정보';
$string['installation'] = '설치';
$string['invalidmd5'] = '잘못된 md5';
$string['langdownloaderror'] = '안타깝게도 \"$a\" 언어팩이 설치되지 않았습니다. 대신 영어를 이용하여 설치될 것입니다.';
$string['langdownloadok'] = '\"$a\" 언어팩이 성공적으로 설치되었습니다. 해당 언어를 이용하여 설치가 진행될 것입니다.';
$string['language'] = '언어';
$string['magicquotesruntime'] = '매직 코트 실행 시간';
$string['magicquotesruntimeerror'] = '이것은 꺼져야 합니다.';
$string['mbstringrecommended'] = '당신의 사이트가 라틴언어계열이 아닌 언어를 지원하는 경우 사이트의 성능을 향상시키기 위해서는 MBSTRING 라이브러리를 설치하는것을 권장합니다.';
$string['memorylimit'] = '기억 제한';
$string['memorylimiterror'] = '이 php 기억 제한은 매우 낮게 설치되어 있습니다. 당신은 후에 문제를 닥치게 될 것입니다.';
$string['memorylimithelp'] = '<p>서버의 PHP 메모리한계가 최근 $a 로 설정되었습니다.</p>

<p>이것은 아마 무들이 나중에 기억의 문제를 갖게 되는 것을 야기시킬것입니다. 특히 만약 당신이 사용할 수 있는 많은 무들을 가지고 있거나 그런 사용자를 가지고 있다면 그러할 것입니다.</p>

<p>우리는 당신이 16M 와 같은 가능하면 더 높은 제한을 가지고 있는 PHP를 형성하기를 요구합니다.
당신이 시도 할 수 잇는 여러가지 방법들이 있습니다.</p>
<ol>
<li>만약 당신이 할 수 있다면 기억제한이 가능한 파일과 함께 PHP를 번역하세요. 이것은 무들이 자기 스스로 기억제한을 설치하는데 허락할 것입니다</li>

<li>만약 다신이 php.ini.파일에 접속했다면 당신은 <b>memory_limit</b>을  16M와 같은 어떤 것으로 바꿔설치 할 수 있을것입니다. 만약 당신이 접속하지 않았다면 이것을 실행하기 위한 당신의관리자에게 문의하실 수 있습니다.</li>

<li>당신이 만들어 낼수 있는 몇개의 PHP서버들에서 무들 주소성명록에 있는 접속파일은 이 라인을 포함하고 있습니다.
<P><blockquote>php_value memory_limit 16M<blockquote></p>
<p>그러나 모든 php페이지가 (당신이 페이지를 살펴보았을때 문제를 찾을 것이다) 일하는 것으로부터 방해 할 이 몇개의 서버들이 있기때문에 당신은 .htaccess 를 제거해야 할 것입니다.</p></li></ol>';
$string['missingrequiredfield'] = '필요한 항목이 빠져 있습니다.';
$string['mysql416bypassed'] = '당신의 사이트가 iso-8859-1 (라틴) 언어만을 사용하는 경우 현재 설치된 MySQL 4.1.12 혹은 그 이상버전을 사용할 수 있습니다. ';
$string['mysql416required'] = '모든 데이터가 향후 UTF-8로 변환될 수 있도록 하기위해서는 MySQL 4.1.16 이상 버전이 무들 1.6버전에 필요합니다. ';
$string['mysqlextensionisnotpresentinphp'] = 'php는 php가 mysql과 연결할 수 있기 위해서 적절하게 형성됐다. 당신의 php.ini 파일이나 recompile php를 확인하세요.';
$string['name'] = '이름';
$string['next'] = '다음으로';
$string['ok'] = 'OK';
$string['parentlanguage'] = 'en';
$string['pass'] = '통과하세요.';
$string['password'] = '비밀번호';
$string['phpversion'] = 'php버젼';
$string['phpversionerror'] = 'php 버젼은 틀림없이 적어도 4.1.0.이어야합니다.';
$string['phpversionhelp'] = '무들은 적어도 4.1.0의 php버젼을 요구합니다.';
$string['previous'] = '이전으로';
$string['remotedownloadnotallowed'] = '서버로 구성요소를 내려받는 것이 허용되지 않습니다. (allow_url_fopen 이 비활성화 됨).<br /><br /> 수동으로  <a href=\"$a->url\">$a->url</a> 파일을 다운로드 하고,  서버의 \"$a->dest\" 에 복사한 후 압축을 푸셔야 합니다.';
$string['report'] = '보고';
$string['safemode'] = 'Safe Mode';
$string['safemodeerror'] = '아마 Safe Mode가 작동되어서 문제가 있을 것입니다.';
$string['sessionautostart'] = '세션의 활동을 시작하세요.';
$string['sessionautostarterror'] = '이것은 종료되어야 합니다.';
$string['skipdbencodingtest'] = 'DB 엔코딩 테스트 생략';
$string['status'] = '상태';
$string['thischarset'] = 'UTF-8';
$string['thislanguage'] = '한국어';
$string['user'] = '사용자';
$string['welcomep10'] = '$a->installername ($a->installerversion)';
$string['welcomep20'] = '당신의 컴퓨터에 <strong>$a->packname $a->packversion</strong> 패키지를 성공적으로 설치한 것을 축하합니다! ';
$string['welcomep30'] = '<strong>$a->installername</strong> 의 이 릴리스는 <strong>무들</strong>이 그 속에서 동작하는 환경을 생성하기 위한 어플리케이션을 포함하고 있습니다.';
$string['welcomep40'] = '이 패키지는 <strong>무들 $a->moodlerelease ($a->moodleversion)</strong> 을 포함하고 있습니다.';
$string['welcomep50'] = '이 패키지에 있는 모든 어플리케이션을 사용하는 것은 각각의 라이선스에의해 지배받습니다. 완전한<strong>$a->installername</strong> 패키지는
<a href=\"http://www.opensource.org/docs/definition_plain.html\">공개 소스이며 </a> <a href=\"http://www.gnu.org/copyleft/gpl.html\">GPL</a> 라이선스에 의해 배포됩니다.';
$string['welcomep60'] = '다음 페이지들은 당신의 컴퓨터에 <strong>무들</strong>을 설정하고 설치하는데 따라하기 쉬운 방법으로 당신을 안내할 것입니다. 당신은 기본 설정을 선택하거나 당신의 목적에 맞게 선택적으로 수정할 수 있습니다.';
$string['welcomep70'] = '<strong>무들</strong> 설정을 계속하기 위해서는 \"다음\" 버튼을 클릭하세요.';
$string['wrongdestpath'] = '잘못된 목적 경로';
$string['wrongsourcebase'] = '잘못된 소스 URL  베이스';
$string['wrongzipfilename'] = '잘못된 ZIP 파일이름';
$string['wwwroot'] = '웹 주소';
$string['wwwrooterror'] = '이 웹 주소는 유효한 것 같지 않습니다 - 무들 설치 프로그램이 거기에 없습니다.';
?>
